const lekce ={
    1: {
        0: ["der Abend", "večer"],
        1: ["du", "ty"],
        2: ["gut", "dobrý"],
        3: ["Guten Abend!", "Dobrý večer!"],
        4: ["(Es) Freut mich.", "Těší mě."],
        5: ["Hallo!", "Ahoj!"],
        6: ["heißen", "jmenovat se"],
        7: ["Hi!", "Ahoj!"],
        8: ["ich", "já"],
        9: ["ihr", "vy"],
        10: ["ja", "ano"],
        11: ["der Morgen", "ráno"],
        12: ["Guten Morgen!", "Dobré ráno!"],
        13: ["der Tag /-e", "den"],
        14: ["Guten Tag!", "Dobrý den!"],
        15: ["und", "a"],
        16: ["wer", "kdo"],
        17: ["Wer bist du?", "Kdo jsi?"],
        18: ["wie", "jak"],
        19: ["Wie heißt du?", "Jak se jmenuješ?"],
        20: ["wir", "my"],
        21: ["in", "v"],
        22: ["das Spiel /-e", "hra"],
        23: ["wo", "kde"],
        24: ["Wo wohnst du?", "Kde bydlíš?"],
        25: ["wohnen", "bydlet"],
        26: ["null", "0"],
        27: ["eins", "1"],
        28: ["zwei", "2"],
        29: ["drei", "3"],
        30: ["vier", "4"],
        31: ["fünf", "5"],
        32: ["sechs", "6"],
        33: ["sieben", "7"],
        34: ["acht", "8"],
        35: ["neun", "9"],
        36: ["zehn", "10"],
        37: ["elf", "11"],
        38: ["zwölf", "12"],
        39: ["dreizehn", "13"],
        40: ["vierzehn", "14"],
        41: ["fünfzehn", "15"],
        42: ["sechzehn", "16"],
        43: ["siebzehn", "17"],
        44: ["achtzehn", "18"],
        45: ["neunzehn", "19"],
        46: ["zwanzig", "20"],
        47: ["alt", "starý"], 
        48: ["er", "on"],
        49: ["der Monat /-e", "měsíc"], 
        50: ["sie", "ona"],
        51: ["sie", "oni"], 
        52: ["aber", "ale"],
        53: ["das Alter", "věk"], 
        54: ["auch", "také"],
        55: ["aus", "z"],      
        56: ["die Band /-s", "(hudební) skupina"],        
        57: ["chatten", "chatovat"],      
        58: ["das Computerspiel /-e", "počítačová hra"],        
        59: ["das E-Mail /-s", "e-mail"],      
        60: ["das Englisch", "angličtina"],        
        61: ["der Fan /-s", "fanoušek"],      
        62: ["das Französisch", "francouzština"],        
        63: ["der Freund /-e", "kamarád"],      
        64: ["die Freundin /-nen", "kamarádka"],        
        65: ["der Fußball", "fotbal"],      
        66: ["gehen", "jít"],        
        67: ["gern", "rád(a)"],      
        68: ["die Gitarre /-n", "kytara"],        
        69: ["das Handy /-s", "mobil"],      
        70: ["das Hobby /-s", "koníček"],        
        71: ["hören", "poslouchat"],      
        72: ["im internet surfen", "surfovat na internetu"],        
        73: ["immer", "pořád, neustále"],      
        74: ["das Jahr /-e", "rok"],        
        75: ["kein/keine/kein", "žádný/žádná/žádné"],      
        76: ["das Klavier /-e", "klavír"],        
        77: ["kommen (aus)", "pocházet (z)"],      
        78: ["das Konzert /-e", "koncert"],        
        79: ["lernen", "učit se"],      
        80: ["liegen", "ležet"],        
        81: ["der Nachname /-n", "příjmení"],      
        82: ["nicht weit von", "nedaleko (koho, čeho)"],        
        83: ["reisen", "cestovat"],      
        84: ["schreiben", "psát"],        
        85: ["die Schule /-n", "škola"],      
        86: ["spielen", "hrát"],        
        87: ["tanzen", "tancovat"],      
        88: ["der Vorname /-n", "křestní jméno"],        
        89: ["der Wohnort /-e", "bydliště"],      
        90: ["falsch", "nesprávně, chybně"],        
        91: ["die Flöte /-n", "flétna"],      
        92: ["haben", "mít"],        
        93: ["das Instrument /-e", "(hudební) nástroj"],      
        94: ["jetzt", "nyní"],        
        95: ["machen", "dělat"],      
        96: ["richtig", "správně"],        
        97: ["der Sport", "sport"],      
        98: ["Sport treiben", "sportovat"],        
        99: ["das Squash", "squash"],      
        100: ["das/der Yoga", "jóga"],      
        101: ["bald", "brzy"],          
        102: ["bis", "do"],          
        103: ["Bis bald!", "Tak zatím!"],          
        104: ["die Frau /-en", "paní"],          
        105: ["der Herr /-en", "pan"],          
        106: ["das Museum /Museen", "muzeum"],          
        107: ["schön", "hezký"],           
        108: ["Servus!", "Ahoj!"],          
        109: ["Tschüs!", "Ahoj! (při loučení)"],          
        110: ["das Wiedersehen", "shledání"],                 
        "počet": 111
    },
    2: {
        0: ["arbeiten", "pracovat"],
        1: ["das Auto /-s", "auto"],
        2: ["brauchen", "potřebovat"],
        3: ["die Britin /-nen", "Britka"],
        4: ["britisch", "britský"],
        5: ["deutsch", "německý"],
        6: ["das Deutsch", "němčina"],
        7: ["die Eisschnellläuferin /-nen", "rychlobruslařka"],
        8: ["fahren", "jet, jezdit"],
        9: ["Frankreich", "Francie"],
        10: ["für", "pro, za"],
        11: ["der Fußballspieler", "fotbalista"],
        12: ["das Jahrhunderttalent /-e", "talent století"],
        13: ["das Kind /-er", "dítě"],
        14: ["lesen", "číst"],
        15: ["das Model /-s", "model, modelka"],
        16: ["die Nummer /-n", "číslo"],
        17: ["die Schauspielerin /-nen", "herečka"],
        18: ["der Schüler", "žák"],
        19: ["die Sportinitiative /-n", "sportovní iniciativa"],
        20: ["sprechen", "mluvit"],
        21: ["der Trainer", "trenér"],
        22: ["besuchen", "navštěvovat, navštívit"],
        23: ["dort", "tam"],
        24: ["dreifach", "trojnásobný"],
        25: ["gewinnen", "vyhrát, vyhrávat"],
        26: ["die Goldmedaille /-n", "zlatá medaile"],
        27: ["das Gymnasium /Gymnasien", "gymnázium"],
        28: ["heute", "dnes"],
        29: ["das Kroatisch", "chorvatština"],
        30: ["leben", "žít"],
        31: ["die Muttersprache /-n", "mateřský jazyk"],
        32: ["oft", "často"],
        33: ["Österreich", "Rakousko"],
        34: ["die Rad(renn)fahrerin /-nen", "cyklistka"],
        35: ["das Spanisch", "španělština"],
        36: ["die Sportlerin /-nen", "sportovkyně"],
        37: ["sportlich", "sportovní"],
        38: ["tschechisch", "český"],
        39: ["das Tschechisch", "čeština"],
        40: ["das Amerika", "Amerika"],
        41: ["die Assistentin /-nen", "asistentka"],
        42: ["der Beruf /-e", "povolání"],
        43: ["Deutschland", "Německo"],
        44: ["England", "Anglie"],
        45: ["die Flagge /-n", "vlajka"],
        46: ["Griechenland", "Řecko"],
        47: ["das Griechisch", "řečtina"], 
        48: ["Großbritannien", "Velká Británie"],
        49: ["die Herkunft", "původ"], 
        50: ["Italien", "Itálie"],
        51: ["das Italienisch", "italština"], 
        52: ["Kroatien", "Chorvatsko"],
        53: ["das Land /Länder", "země, stát"], 
        54: ["der Lehrer", "učitel"],
        55: ["die Lehrerin /-nen", "učitelka"],      
        56: ["der Manager", "manažer"],        
        57: ["Polen", "Polsko"],      
        58: ["das Polnisch", "polština"],        
        59: ["das Russisch", "ruština"],      
        60: ["Russland", "Rusko"],        
        61: ["die Schweiz", "Švýcarsko"],      
        62: ["die Slowakei", "Slovensko"],        
        63: ["das Slowakisch", "slovenština"],      
        64: ["Spanien", "Španělsko"],        
        65: ["die Sprache /-n", "jazyk, řeč"],      
        66: ["der Student /-en", "student"],        
        67: ["die Studentin /-nen", "studentka"],      
        68: ["Tschechien", "Česko"],        
        69: ["die Türkei", "Turecko"],      
        70: ["das Türkisch", "turečtina"],        
        71: ["das Ungarisch", "maďarština"],      
        72: ["Ungarn", "Maďarsko"],        
        73: ["die Verkäuferin /-nen", "prodavačka"],      
        74: ["welcher/welche/welches", "jaký/jaká/jaké"],        
        75: ["das Abitur /-e", "maturita"],      
        76: ["der Austausch /-e", "výměna"],        
        77: ["ein bisschen", "trochu"],      
        78: ["finden", "shlédavat, myslet si"],        
        79: ["interessant", "zajímavý"],      
        80: ["der Kurs /-e", "kurz"],        
        81: ["leider", "bohužel"],      
        82: ["mein/meine/mein", "můj/moje/moje"],        
        83: ["der Mensch /-en", "člověk"],      
        84: ["die Mutter /Mütter", "matka"],        
        85: ["noch", "ještě"],      
        86: ["Portugal", "Portugalsko"],        
        87: ["das Portugiesisch", "portugalština"],      
        88: ["Schweden", "Švédsko"],        
        89: ["das Schwedisch", "švédština"],      
        90: ["sehr", "velmi"],        
        91: ["studieren", "studovat"],      
        92: ["super", "super, skvělý"],        
        93: ["wenig", "málo"],      
        94: ["das Wort /Wörter", "slovo"],        
        95: ["Deutscher/Deutsche", "Němec/Němka"],      
        96: ["Engländer/Engländerin", "Angličan/Angličanka"],        
        97: ["Franzose/Französin", "Prancouz/Francouzka"],      
        98: ["Italiener/Italienerin", "Ital/Italka"],        
        99: ["die Natiolität /-en", "národnost"],      
        100: ["Österreicher/Österreicherin", ""],          
        101: ["Russe/Russin", ""],          
        102: ["Schweizer/Schweizerin", ""],          
        103: ["Slowake/Slowakin", ""],          
        104: ["Spanier/Spanierin", ""],          
        105: ["Tscheche/Tschechin", ""],          
        106: ["dreißig", ""],          
        107: ["vierzig", ""],          
        108: ["fünfzig", ""],          
        109: ["sechzig", ""],          
        110: ["siebzig", ""],          
        111: ["achtzig", ""],          
        112: ["neunzig", ""],          
        113: ["(ein) hundert", ""],          
        114: ["(ein) tausend", ""],          
        115: ["das Afrika", ""],          
        116: ["die Arbeit /-en", ""],          
        117: ["das Asien", ""],          
        118: ["das Australien", ""],          
        119: ["beginnen", ""],          
        120: ["danke", ""],          
        121: ["das Europa", ""],          
        122: ["ganz", ""],          
        123: ["gehen", ""],          
        124: ["genau", ""],          
        125: ["morgen", ""],          
        126: ["nur", ""],          
        127: ["der Rekord /-e", ""],          
        128: ["schon", ""],              
        129: ["das Semester", ""],             
        130: ["das Südamerika", ""],             
        131: ["die USA (mn.č.)", ""],             
        132: ["viel", ""],             
        133: ["die Welt", ""],             
        "počet": 134
    },
    3: {
        0: ["die Geburtstagsparty", "narozeninová oslava"],
        1: ["das Haustier /-e", "domácí zvíře"],
        2: ["die Aktivität /-en", "aktivita"],
        3: ["der Staummbaum /Staubäume", "rodokmen"],
        4: ["der Bruder /Brüder", "bratr"],
        5: ["der Cousin /-s", "bratranec"],
        6: ["die Cousine /-n", "sestřenice"],
        7: ["die Ehefrau /-en", "manželka"],
        8: ["der Ehemann /Ehemänner", "manžel"],
        9: ["das Einzelkind /-er", "jedináček"],
        10: ["die Eltern", "rodiče"],
        11: ["die Familie /-n", "rodina"],
        12: ["feiern", "slavit, oslavovat"],
        13: ["das Fest /-e", "oslava, slavnost"],
        14: ["der Garten /Gärten", "zahrada"],
        15: ["gehören", "patřit"],
        16: ["geschieden", "rozvedený"],
        17: ["die Geschwister", "sourozenec"],
        18: ["gleich", "stejný"],
        19: ["groß", "velký"],
        20: ["haben", "mít"],
        21: ["", ""],
        22: ["", ""],
        23: ["", ""],
        24: ["", ""],
        25: ["", ""],
        26: ["", ""],
        27: ["", ""],
        28: ["", ""],
        29: ["", ""],
        30: ["", ""],
        31: ["", ""],
        32: ["", ""],
        33: ["", ""],
        34: ["", ""],
        35: ["", ""],
        36: ["", ""],
        37: ["", ""],
        38: ["", ""],
        39: ["", ""],
        40: ["", ""],
        41: ["", ""],
        42: ["", ""],
        43: ["", ""],
        44: ["", ""],
        45: ["", ""],
        46: ["", ""],
        47: ["", ""], 
        48: ["", ""],
        49: ["", ""], 
        50: ["", ""],
        51: ["", ""], 
        52: ["", ""],
        53: ["", ""], 
        54: ["", ""],
        55: ["", ""],      
        56: ["", ""],        
        57: ["", ""],      
        58: ["", ""],        
        59: ["", ""],      
        60: ["", ""],        
        61: ["", ""],      
        62: ["", ""],        
        63: ["", ""],      
        64: ["", ""],        
        65: ["", ""],      
        66: ["", ""],        
        67: ["", ""],      
        68: ["", ""],        
        69: ["", ""],      
        70: ["", ""],        
        71: ["", ""],      
        72: ["", ""],        
        73: ["", ""],      
        74: ["", ""],        
        75: ["", ""],      
        76: ["", ""],        
        77: ["", ""],      
        78: ["", ""],        
        79: ["", ""],      
        80: ["", ""],        
        81: ["", ""],      
        82: ["", ""],        
        83: ["", ""],      
        84: ["", ""],        
        85: ["", ""],      
        86: ["", ""],        
        87: ["", ""],      
        88: ["", ""],        
        89: ["", ""],      
        90: ["", ""],        
        91: ["", ""],      
        92: ["", ""],        
        93: ["", ""],      
        94: ["", ""],        
        95: ["", ""],      
        96: ["", ""],        
        97: ["", ""],      
        98: ["", ""],        
        99: ["", ""],      
        100: ["", ""],    
        "počet": 21
    },
    4: {
        0: ["die Freizeit", "volný čas"],
        1: ["", ""],
        2: ["", ""],
        3: ["", ""],
        4: ["", ""],
        5: ["", ""],
        6: ["", ""],
        7: ["", ""],
        8: ["", ""],
        9: ["", ""],
        10: ["", ""],
        11: ["", ""],
        12: ["", ""],
        13: ["", ""],
        14: ["", ""],
        15: ["", ""],
        16: ["", ""],
        17: ["", ""],
        18: ["", ""],
        19: ["", ""],
        20: ["", ""],
        21: ["", ""],
        22: ["", ""],
        23: ["", ""],
        24: ["", ""],
        25: ["", ""],
        26: ["", ""],
        27: ["", ""],
        28: ["", ""],
        29: ["", ""],
        30: ["", ""],
        31: ["", ""],
        32: ["", ""],
        33: ["", ""],
        34: ["", ""],
        35: ["", ""],
        36: ["", ""],
        37: ["", ""],
        38: ["", ""],
        39: ["", ""],
        40: ["", ""],
        41: ["", ""],
        42: ["", ""],
        43: ["", ""],
        44: ["", ""],
        45: ["", ""],
        46: ["", ""],
        47: ["", ""], 
        48: ["", ""],
        49: ["", ""], 
        50: ["", ""],
        51: ["", ""], 
        52: ["", ""],
        53: ["", ""], 
        54: ["", ""],
        55: ["", ""],      
        56: ["", ""],        
        57: ["", ""],      
        58: ["", ""],        
        59: ["", ""],      
        60: ["", ""],        
        61: ["", ""],      
        62: ["", ""],        
        63: ["", ""],      
        64: ["", ""],        
        65: ["", ""],      
        66: ["", ""],        
        67: ["", ""],      
        68: ["", ""],        
        69: ["", ""],      
        70: ["", ""],        
        71: ["", ""],      
        72: ["", ""],        
        73: ["", ""],      
        74: ["", ""],        
        75: ["", ""],      
        76: ["", ""],        
        77: ["", ""],      
        78: ["", ""],        
        79: ["", ""],      
        80: ["", ""],        
        81: ["", ""],      
        82: ["", ""],        
        83: ["", ""],      
        84: ["", ""],        
        85: ["", ""],      
        86: ["", ""],        
        87: ["", ""],      
        88: ["", ""],        
        89: ["", ""],      
        90: ["", ""],        
        91: ["", ""],      
        92: ["", ""],        
        93: ["", ""],      
        94: ["", ""],        
        95: ["", ""],      
        96: ["", ""],        
        97: ["", ""],      
        98: ["", ""],        
        99: ["", ""],      
        100: ["", ""],    
        "počet": 1
    },
    5: {
        0: ["die Lebensmittel (mn.č.)", "potraviny"],
        1: ["", ""],
        2: ["", ""],
        3: ["", ""],
        4: ["", ""],
        5: ["", ""],
        6: ["", ""],
        7: ["", ""],
        8: ["", ""],
        9: ["", ""],
        10: ["", ""],
        11: ["", ""],
        12: ["", ""],
        13: ["", ""],
        14: ["", ""],
        15: ["", ""],
        16: ["", ""],
        17: ["", ""],
        18: ["", ""],
        19: ["", ""],
        20: ["", ""],
        21: ["", ""],
        22: ["", ""],
        23: ["", ""],
        24: ["", ""],
        25: ["", ""],
        26: ["", ""],
        27: ["", ""],
        28: ["", ""],
        29: ["", ""],
        30: ["", ""],
        31: ["", ""],
        32: ["", ""],
        33: ["", ""],
        34: ["", ""],
        35: ["", ""],
        36: ["", ""],
        37: ["", ""],
        38: ["", ""],
        39: ["", ""],
        40: ["", ""],
        41: ["", ""],
        42: ["", ""],
        43: ["", ""],
        44: ["", ""],
        45: ["", ""],
        46: ["", ""],
        47: ["", ""], 
        48: ["", ""],
        49: ["", ""], 
        50: ["", ""],
        51: ["", ""], 
        52: ["", ""],
        53: ["", ""], 
        54: ["", ""],
        55: ["", ""],      
        56: ["", ""],        
        57: ["", ""],      
        58: ["", ""],        
        59: ["", ""],      
        60: ["", ""],        
        61: ["", ""],      
        62: ["", ""],        
        63: ["", ""],      
        64: ["", ""],        
        65: ["", ""],      
        66: ["", ""],        
        67: ["", ""],      
        68: ["", ""],        
        69: ["", ""],      
        70: ["", ""],        
        71: ["", ""],      
        72: ["", ""],        
        73: ["", ""],      
        74: ["", ""],        
        75: ["", ""],      
        76: ["", ""],        
        77: ["", ""],      
        78: ["", ""],        
        79: ["", ""],      
        80: ["", ""],        
        81: ["", ""],      
        82: ["", ""],        
        83: ["", ""],      
        84: ["", ""],        
        85: ["", ""],      
        86: ["", ""],        
        87: ["", ""],      
        88: ["", ""],        
        89: ["", ""],      
        90: ["", ""],        
        91: ["", ""],      
        92: ["", ""],        
        93: ["", ""],      
        94: ["", ""],        
        95: ["", ""],      
        96: ["", ""],        
        97: ["", ""],      
        98: ["", ""],        
        99: ["", ""],      
        100: ["", ""],    
        "počet": 1
    },
    6: {
        0: ["die Freizeitaktivität /-en", "volnočasová aktivita"],
        1: ["die Morgenroutine /-n", ""],
        2: ["jobben", "mít brigádu"],
        3: ["die Pflicht", "povinnost"],
        4: ["am liebsten", "nejraději"],
        5: ["an|fangen", "začí(na)t"],
        6: ["an|machen", "zapnout, pustit"],
        7: ["an|rufen", "(za)volat"],
        8: ["sich an|ziehen", "obléknout se"],
        9: ["auf|räumen", "uklízet"],
        10: ["auf|stehen", "vstá(va)t"],
        11: ["auf|wachen", "probudit se"],
        12: ["aus|leeren", "vysypat, vyprázdnit"],
        13: ["aus|räumen", "vyklidit"],
        14: ["aus|sehen", "vypadat"],
        15: ["das Bad /Badër", "koupelna"],
        16: ["das Badezimmer", "koupelna"],
        17: ["das Bild /-er", "obraz"],
        18: ["dabei", "při tom"],
        19: ["drehen", "natáčet"],
        20: ["duschen", "sprchovat se"],
        21: ["ein|kaufen", "nakupovat"],
        22: ["ein|schlafen", "usnout"],
        23: ["das Ende /-n", "konec"],
        24: ["endlich", "konečně"],
        25: ["fern|sehen", "dívat se na televizi"],
        26: ["fertig", "hotový"],
        27: ["halb", "půl"],
        28: ["das Horror (j.č.)", "horor"],
        29: ["Hurra!", "Hurá!"],
        30: ["die Kamera /-s", "kamera, fotoaparát"],
        31: ["klingeln", "zvonit"],
        32: ["das Lieblingsfach /Lieblingsfächer", "oblíbený předmět"],
        33: ["mit|nehmen", "vzít s sebou"],
        34: ["müde", "unavený"],
        35: ["das Mülleimer", "odpadkový koš"],
        36: ["putzen", "(vy)čistit"],
        37: ["saugen", "vysávat"],
        38: ["schlafen", "spát"],
        39: ["(sich) schminken", "líčit se"],
        40: ["die Spülmaschine /-n", "myčka, nádobí"],
        41: ["der Staub (j.č.)", "prach"],
        42: ["der Unterricht (j.č.)", "vyučování"],
        43: ["das/der Viertel", "čtvrt"],
        44: ["vloggen", "natáčet vlog (videoblog)"],
        45: ["(sich) vor|bereiten", "připravovat (se)"],
        46: ["der Wecker", "budík"],
        47: ["zeigen", "ukázat"], 
        48: ["zu|bereiten", "připravit (jídlo)"],
        49: ["züruck|kommen", "vrátit se"], 
        50: ["aus|schalten", "vypnout"],
        51: ["ein|schalten", "zapnout"], 
        52: ["wen", "koho"],
        53: ["die Uhrzeit /-en", "(přesný) čas"], 
        54: ["das Bett /-en", "postel"],
        55: ["der Blogger", "bloger"],      
        56: ["entdecken", "objevit, najít"],        
        57: ["(sich) entschuldigen", "omluvit (se)"],      
        58: ["erzählen", "vyprávět"],        
        59: ["kommentieren", "komentovat"],      
        60: ["liken", "likovat"],        
        61: ["posten", "postovat (příspěvky)"],      
        62: ["der Trend /-s", "trend"],        
        63: ["verbringen", "strávit"],      
        64: ["vergessen", "zapomenout"],        
        65: ["weiter", "dále"],      
        66: ["wissen", "vědět"],        
        67: ["dienstags", "každé úterý"],      
        68: ["donnerstags", "každý čtvrtek"],        
        69: ["freitags", "každý pátek"],      
        70: ["der Kanal /Kanäle", "program, kanál"],        
        71: ["Lieblings-(kanal...)", "oblíbený (kanál)"],      
        72: ["die Mitternacht /Mitternächte", "půlnoc"],        
        73: ["mittwochs", "každou středu"],      
        74: ["montags", "každé pondělí"],        
        75: ["morgens", "každé ráno"],      
        76: ["der Nachmittag /-e", "odpoledne"],        
        77: ["nachmittags", "každé odpoledne"],      
        78: ["samstags", "každou sobotu"],        
        79: ["sonntags", "každou neděli"],      
        80: ["das Training /-s", "trénink"],        
        81: ["der Vormmittag /-e", "dopoledne"],      
        82: ["vormittags", "každé dopoledne"],        
        83: ["die Weltmeisterschaft /-en", "mistrovství světa"],      
        84: ["durch", "přes, skrz"],        
        85: ["die Ecke", "roh"],      
        86: ["gegen", "proti"],        
        87: ["lieb", "milý, milovaný"],      
        88: ["das Mädchen", "dívka"],        
        89: ["ohne", "bez"],      
        90: ["der Park /-s", "park"],        
        91: ["der Schatz /Schätze", "poklad, zlatíčko"],      
        92: ["der Stress /-e", "stres"],        
        93: ["die Berufsschule /-n", "učňovská škola"],      
        94: ["dumm", "hloupý"],        
        95: ["die Fachschule /-n", "odborná škola"],      
        96: ["ab|holen", "vyzvednout"],        
        97: ["der Kindergarten /Kindergärten", "mateřská škola"],      
        98: ["das Krankenhaus /Krankenhäuser", "nemocnice"],        
        99: ["sich treffen", "setkat se"],         
        "počet": 100
    },
    7: {
        0: ["die Beziehung /-en", "vztah"],
        1: ["die Eigenschaft /-en", "vlasnost"],
        2: ["arrogant", "arogantní"],
        3: ["besichtigen", "prohlédnout si"],
        4: ["doof", "pitomý hloupý"],
        5: ["echt", "fakt, opravdu"],
        6: ["einmal", "jednou"],
        7: ["die Freundesliste", "seznam přátel"],
        8: ["gefallen", "líbit se"],
        9: ["gehören", "patřit"],
        10: ["helfen", "pomoci, pomáhat (někomu)"],
        11: ["hilfsbereit", "ochotný pomoci"],
        12: ["hübsch", "hezký, pěkný"],
        13: ["humorvoll", "vtipný"],
        14: ["klicken", "kliknout"],        
        15: ["lachen", "smát se"],
        16: ["laufen", "běhat, běžet"],
        17: ["lieben", "milovat, mít rád"],
        18: ["lustig", "veselý, vtipný"],
        19: ["die Medizin (j.č)", "medicína"],
        20: ["originell", "originální, osobitý"],
        21: ["per", "čím"],
        22: ["das Reisen (j.č)", "cestování"],
        23: ["schenken", "darovat"],   
        24: ["schicken", "poslat"],
        25: ["die Süßigkeit /-en", "sladkost, cukrovinka"], 
        26: ["sympatisch", "sympatický"],
        27: ["das T-Shirt /-s", "tričko"], 
        28: ["unzufrieden", "nespokojený"],
        29: ["der Wald /Waldër", "les"], 
        30: ["das Witz /-e", "vtip"],
        31: ["das Aussehen (j.č.)", "vzhled"], 
        32: ["böse", "zlý"],
        33: ["der Charakter /-e", "charakter"], 
        34: ["dick", "tlustý"],
        35: ["frech", "drzý"], 
        36: ["hässlich", "ošklivý"],
        37: ["klein", "malý"], 
        38: ["die Persönlichkeit /-en", "osobnost"],
        39: ["schlank", "štíhlý"], 
        40: ["verschieden", "různý"],
        41: ["das Problem /-e", "problém"], 
        42: ["das Abonnement /-s", "předplatné"],
        43: ["das Armband /Armbänder", "náramek"], 
        44: ["die Blume /-n", "květina"],
        45: ["der Gutschein /-e", "poukaz"], 
        46: ["die Handyfolie /-n", "obal na mobilní telefon"],
        47: ["der Kalender", "kalendář"], 
        48: ["die Klatmotte /-n", "oblečení(hadry)"], 
        49: ["die Kosmetik (j.č.)", "kosmetika"], 
        50: ["das Kosmetik-Set /-s", "kosmetický balíček"],
        51: ["das Ladegerät", "nabíječka"], 
        52: ["der Lautsprecher", "reproduktor"],
        53: ["leer", "prázdný"], 
        54: ["der Muttertag /-e", "Den matek"],
        55: ["die Selfie-Stange /-n", "selfie tyč"],      
        56: ["das Ticket /-s", "vstupenka"],        
        57: ["das Weihnachten", "Vánoce"],      
        58: ["der Fanatiker", "fanatik"],        
        59: ["geben", "dávat, dát"],      
        60: ["insgesamt", "celkem"],        
        61: ["das Prozent", "procento"],      
        62: ["das Schuljahr", "školní rok"],        
        63: ["witzig", "vtipný"],      
        64: ["fair", "férový, spravedlivý"],        
        65: ["streng", "přísný"],      
        66: ["unfair", "nespravedlivý"],        
        67: ["unsympatisch", "nesympatický"],      
        68: ["Argentinien", "Argentina"],        
        69: ["das Märchen", "pohádka"],      
        70: ["Rad fahren", "jezdit na kole"],        
        71: ["die Sofortbildkamera /-s", "polaroid"],      
        72: ["die Spielkarte /-n", "hrací karta"],        
        73: ["das Fotografieren (j.č.)", "fotografování"],      
        74: ["die Mode /-n", "móda"],        
        75: ["das Radfahren (j.č.)", "jízda na kole (cyklistika)"],   
        76: ["die Zeitschrift /-en", "časopis"],      
        "počet": 77
    },
    8: {
        0: ["das Geshäft/-e", "obchod"],
        1: ["", ""],
        2: ["", ""],
        3: ["", ""],
        4: ["", ""],
        5: ["", ""],
        6: ["", ""],
        7: ["", ""],
        8: ["", ""],
        9: ["", ""],
        10: ["", ""],
        11: ["", ""],
        12: ["", ""],
        13: ["", ""],
        14: ["", ""],
        15: ["", ""],
        16: ["", ""],
        17: ["", ""],
        18: ["", ""],
        19: ["", ""],
        20: ["", ""],
        21: ["", ""],
        22: ["", ""],
        23: ["", ""],
        24: ["", ""],
        25: ["", ""],
        26: ["", ""],
        27: ["", ""],
        28: ["", ""],
        29: ["", ""],
        30: ["", ""],
        31: ["", ""],
        32: ["", ""],
        33: ["", ""],
        34: ["", ""],
        35: ["", ""],
        36: ["", ""],
        37: ["", ""],
        38: ["", ""],
        39: ["", ""],
        40: ["", ""],
        41: ["", ""],
        42: ["", ""],
        43: ["", ""],
        44: ["", ""],
        45: ["", ""],
        46: ["", ""],
        47: ["", ""], 
        48: ["", ""],
        49: ["", ""], 
        50: ["", ""],
        51: ["", ""], 
        52: ["", ""],
        53: ["", ""], 
        54: ["", ""],
        55: ["", ""],      
        56: ["", ""],        
        57: ["", ""],      
        58: ["", ""],        
        59: ["", ""],      
        60: ["", ""],        
        61: ["", ""],      
        62: ["", ""],        
        63: ["", ""],      
        64: ["", ""],        
        65: ["", ""],      
        66: ["", ""],        
        67: ["", ""],      
        68: ["", ""],        
        69: ["", ""],      
        70: ["", ""],        
        71: ["", ""],      
        72: ["", ""],        
        73: ["", ""],      
        74: ["", ""],        
        75: ["", ""],      
        76: ["", ""],        
        77: ["", ""],      
        78: ["", ""],        
        79: ["", ""],      
        80: ["", ""],        
        81: ["", ""],      
        82: ["", ""],        
        83: ["", ""],      
        84: ["", ""],        
        85: ["", ""],      
        86: ["", ""],        
        87: ["", ""],      
        88: ["", ""],        
        89: ["", ""],      
        90: ["", ""],        
        91: ["", ""],      
        92: ["", ""],        
        93: ["", ""],      
        94: ["", ""],        
        95: ["", ""],      
        96: ["", ""],        
        97: ["", ""],      
        98: ["", ""],        
        99: ["", ""],      
        100: ["", ""],    
        "počet": 1
    },
    9: {
        0: ["die Wegbeschreibung/-e", "popis cesty"],
        1: ["", ""],
        2: ["", ""],
        3: ["", ""],
        4: ["", ""],
        5: ["", ""],
        6: ["", ""],
        7: ["", ""],
        8: ["", ""],
        9: ["", ""],
        10: ["", ""],
        11: ["", ""],
        12: ["", ""],
        13: ["", ""],
        14: ["", ""],
        15: ["", ""],
        16: ["", ""],
        17: ["", ""],
        18: ["", ""],
        19: ["", ""],
        20: ["", ""],
        21: ["", ""],
        22: ["", ""],
        23: ["", ""],
        24: ["", ""],
        25: ["", ""],
        26: ["", ""],
        27: ["", ""],
        28: ["", ""],
        29: ["", ""],
        30: ["", ""],
        31: ["", ""],
        32: ["", ""],
        33: ["", ""],
        34: ["", ""],
        35: ["", ""],
        36: ["", ""],
        37: ["", ""],
        38: ["", ""],
        39: ["", ""],
        40: ["", ""],
        41: ["", ""],
        42: ["", ""],
        43: ["", ""],
        44: ["", ""],
        45: ["", ""],
        46: ["", ""],
        47: ["", ""], 
        48: ["", ""],
        49: ["", ""], 
        50: ["", ""],
        51: ["", ""], 
        52: ["", ""],
        53: ["", ""], 
        54: ["", ""],
        55: ["", ""],      
        56: ["", ""],        
        57: ["", ""],      
        58: ["", ""],        
        59: ["", ""],      
        60: ["", ""],        
        61: ["", ""],      
        62: ["", ""],        
        63: ["", ""],      
        64: ["", ""],        
        65: ["", ""],      
        66: ["", ""],        
        67: ["", ""],      
        68: ["", ""],        
        69: ["", ""],      
        70: ["", ""],        
        71: ["", ""],      
        72: ["", ""],        
        73: ["", ""],      
        74: ["", ""],        
        75: ["", ""],      
        76: ["", ""],        
        77: ["", ""],      
        78: ["", ""],        
        79: ["", ""],      
        80: ["", ""],        
        81: ["", ""],      
        82: ["", ""],        
        83: ["", ""],      
        84: ["", ""],        
        85: ["", ""],      
        86: ["", ""],        
        87: ["", ""],      
        88: ["", ""],        
        89: ["", ""],      
        90: ["", ""],        
        91: ["", ""],      
        92: ["", ""],        
        93: ["", ""],      
        94: ["", ""],        
        95: ["", ""],      
        96: ["", ""],        
        97: ["", ""],      
        98: ["", ""],        
        99: ["", ""],      
        100: ["", ""],    
        "počet": 1
    },
    10: {
        0: ["der Sommer", "léto"],
        1: ["", ""],
        2: ["", ""],
        3: ["", ""],
        4: ["", ""],
        5: ["", ""],
        6: ["", ""],
        7: ["", ""],
        8: ["", ""],
        9: ["", ""],
        10: ["", ""],
        11: ["", ""],
        12: ["", ""],
        13: ["", ""],
        14: ["", ""],
        15: ["", ""],
        16: ["", ""],
        17: ["", ""],
        18: ["", ""],
        19: ["", ""],
        20: ["", ""],
        21: ["", ""],
        22: ["", ""],
        23: ["", ""],
        24: ["", ""],
        25: ["", ""],
        26: ["", ""],
        27: ["", ""],
        28: ["", ""],
        29: ["", ""],
        30: ["", ""],
        31: ["", ""],
        32: ["", ""],
        33: ["", ""],
        34: ["", ""],
        35: ["", ""],
        36: ["", ""],
        37: ["", ""],
        38: ["", ""],
        39: ["", ""],
        40: ["", ""],
        41: ["", ""],
        42: ["", ""],
        43: ["", ""],
        44: ["", ""],
        45: ["", ""],
        46: ["", ""],
        47: ["", ""], 
        48: ["", ""],
        49: ["", ""], 
        50: ["", ""],
        51: ["", ""], 
        52: ["", ""],
        53: ["", ""], 
        54: ["", ""],
        55: ["", ""],      
        56: ["", ""],        
        57: ["", ""],      
        58: ["", ""],        
        59: ["", ""],      
        60: ["", ""],        
        61: ["", ""],      
        62: ["", ""],        
        63: ["", ""],      
        64: ["", ""],        
        65: ["", ""],      
        66: ["", ""],        
        67: ["", ""],      
        68: ["", ""],        
        69: ["", ""],      
        70: ["", ""],        
        71: ["", ""],      
        72: ["", ""],        
        73: ["", ""],      
        74: ["", ""],        
        75: ["", ""],      
        76: ["", ""],        
        77: ["", ""],      
        78: ["", ""],        
        79: ["", ""],      
        80: ["", ""],        
        81: ["", ""],      
        82: ["", ""],        
        83: ["", ""],      
        84: ["", ""],        
        85: ["", ""],      
        86: ["", ""],        
        87: ["", ""],      
        88: ["", ""],        
        89: ["", ""],      
        90: ["", ""],        
        91: ["", ""],      
        92: ["", ""],        
        93: ["", ""],      
        94: ["", ""],        
        95: ["", ""],      
        96: ["", ""],        
        97: ["", ""],      
        98: ["", ""],        
        99: ["", ""],      
        100: ["", ""],    
        "počet": 1
    }
}