const lekce ={
    1: {
        0: ["der Abend", "večer"],
        1: ["du", "ty"],
        2: ["gut", "dobrý"],
        3: ["Guten Abend!", "Dobrý večer!"],
        4: ["(Es) Freut mich.", "Těší mě."],
        5: ["Hallo!", "Ahoj!"],
        6: ["heißen", "jmenovat se"],
        7: ["Hi!", "Ahoj!"],
        8: ["ich", "já"],
        9: ["ihr", "vy"],
        10: ["ja", "ano"],
        11: ["der Morgen", "ráno"],
        12: ["Guten Morgen!", "Dobré ráno!"],
        13: ["der Tag /-e", "den"],
        14: ["Guten Tag!", "Dobrý den!"],
        15: ["und", "a"],
        16: ["wer", "kdo"],
        17: ["Wer bist du?", "Kdo jsi?"],
        18: ["wie", "jak"],
        19: ["Wie heißt du?", "Jak se jmenuješ?"],
        20: ["wir", "my"],
        21: ["in", "v"],
        22: ["das Spiel /-e", "hra"],
        23: ["wo", "kde"],
        24: ["Wo wohnst du?", "Kde bydlíš?"],
        25: ["wohnen", "bydlet"],
        26: ["null", "0"],
        27: ["eins", "1"],
        28: ["zwei", "2"],
        29: ["drei", "3"],
        30: ["vier", "4"],
        31: ["fünf", "5"],
        32: ["sechs", "6"],
        33: ["sieben", "7"],
        34: ["acht", "8"],
        35: ["neun", "9"],
        36: ["zehn", "10"],
        37: ["elf", "11"],
        38: ["zwölf", "12"],
        39: ["dreizehn", "13"],
        40: ["vierzehn", "14"],
        41: ["fünfzehn", "15"],
        42: ["sechzehn", "16"],
        43: ["siebzehn", "17"],
        44: ["achtzehn", "18"],
        45: ["neunzehn", "19"],
        46: ["zwanzig", "20"],
        47: ["alt", "starý"], 
        48: ["er", "on"],
        49: ["der Monat /-e", "měsíc"], 
        50: ["sie", "ona"],
        51: ["sie", "oni"], 
        52: ["aber", "ale"],
        53: ["das Alter", "věk"], 
        54: ["auch", "také"],
        55: ["aus", "z"],      
        56: ["die Band /-s", "(hudební) skupina"],        
        57: ["chatten", "chatovat"],      
        58: ["das Computerspiel /-e", "počítačová hra"],        
        59: ["das E-Mail /-s", "e-mail"],      
        60: ["das Englisch", "angličtina"],        
        61: ["der Fan /-s", "fanoušek"],      
        62: ["das Französisch", "francouzština"],        
        63: ["der Freund /-e", "kamarád"],      
        64: ["die Freundin /-nen", "kamarádka"],        
        65: ["der Fußball", "fotbal"],      
        66: ["gehen", "jít"],        
        67: ["gern", "rád(a)"],      
        68: ["die Gitarre /-n", "kytara"],        
        69: ["das Handy /-s", "mobil"],      
        70: ["das Hobby /-s", "koníček"],        
        71: ["hören", "poslouchat"],      
        72: ["im internet surfen", "surfovat na internetu"],        
        73: ["immer", "pořád, neustále"],      
        74: ["das Jahr /-e", "rok"],        
        75: ["kein/keine/kein", "žádný/žádná/žádné"],      
        76: ["das Klavier /-e", "klavír"],        
        77: ["kommen (aus)", "pocházet (z)"],      
        78: ["das Konzert /-e", "koncert"],        
        79: ["lernen", "učit se"],      
        80: ["liegen", "ležet"],        
        81: ["der Nachname /-n", "příjmení"],      
        82: ["nicht weit von", "nedaleko (koho, čeho)"],        
        83: ["reisen", "cestovat"],      
        84: ["schreiben", "psát"],        
        85: ["die Schule /-n", "škola"],      
        86: ["spielen", "hrát"],        
        87: ["tanzen", "tancovat"],      
        88: ["der Vorname /-n", "křestní jméno"],        
        89: ["der Wohnort /-e", "bydliště"],      
        90: ["falsch", "nesprávně, chybně"],        
        91: ["die Flöte /-n", "flétna"],      
        92: ["haben", "mít"],        
        93: ["das Instrument /-e", "(hudební) nástroj"],      
        94: ["jetzt", "nyní"],        
        95: ["machen", "dělat"],      
        96: ["richtig", "správně"],        
        97: ["der Sport", "sport"],      
        98: ["Sport treiben", "sportovat"],        
        99: ["das Squash", "squash"],      
        100: ["das/der Yoga", "jóga"],      
        101: ["bald", "brzy"],          
        102: ["bis", "do"],          
        103: ["Bis bald!", "Tak zatím!"],          
        104: ["die Frau /-en", "paní"],          
        105: ["der Herr /-en", "pan"],          
        106: ["das Museum /Museen", "muzeum"],          
        107: ["schön", "hezký"],           
        108: ["Servus!", "Ahoj!"],          
        109: ["Tschüs!", "Ahoj! (při loučení)"],          
        110: ["das Wiedersehen", "shledání"],                 
        "počet": 111
    },
    2: {
        0: ["arbeiten", "pracovat"],
        1: ["das Auto /-s", "auto"],
        2: ["brauchen", "potřebovat"],
        3: ["die Britin /-nen", "Britka"],
        4: ["britisch", "britský"],
        5: ["deutsch", "německý"],
        6: ["das Deutsch", "němčina"],
        7: ["die Eisschnellläuferin /-nen", "rychlobruslařka"],
        8: ["fahren", "jet, jezdit"],
        9: ["Frankreich", "Francie"],
        10: ["für", "pro, za"],
        11: ["der Fußballspieler", "fotbalista"],
        12: ["das Jahrhunderttalent /-e", "talent století"],
        13: ["das Kind /-er", "dítě"],
        14: ["lesen", "číst"],
        15: ["das Model /-s", "model, modelka"],
        16: ["die Nummer /-n", "číslo"],
        17: ["die Schauspielerin /-nen", "herečka"],
        18: ["der Schüler", "žák"],
        19: ["die Sportinitiative /-n", "sportovní iniciativa"],
        20: ["sprechen", "mluvit"],
        21: ["der Trainer", "trenér"],
        22: ["besuchen", "navštěvovat, navštívit"],
        23: ["dort", "tam"],
        24: ["dreifach", "trojnásobný"],
        25: ["gewinnen", "vyhrát, vyhrávat"],
        26: ["die Goldmedaille /-n", "zlatá medaile"],
        27: ["das Gymnasium /Gymnasien", "gymnázium"],
        28: ["heute", "dnes"],
        29: ["das Kroatisch", "chorvatština"],
        30: ["leben", "žít"],
        31: ["die Muttersprache /-n", "mateřský jazyk"],
        32: ["oft", "často"],
        33: ["Österreich", "Rakousko"],
        34: ["die Rad(renn)fahrerin /-nen", "cyklistka"],
        35: ["das Spanisch", "španělština"],
        36: ["die Sportlerin /-nen", "sportovkyně"],
        37: ["sportlich", "sportovní"],
        38: ["tschechisch", "český"],
        39: ["das Tschechisch", "čeština"],
        40: ["das Amerika", "Amerika"],
        41: ["die Assistentin /-nen", "asistentka"],
        42: ["der Beruf /-e", "povolání"],
        43: ["Deutschland", "Německo"],
        44: ["England", "Anglie"],
        45: ["die Flagge /-n", "vlajka"],
        46: ["Griechenland", "Řecko"],
        47: ["das Griechisch", "řečtina"], 
        48: ["Großbritannien", "Velká Británie"],
        49: ["die Herkunft", "původ"], 
        50: ["Italien", "Itálie"],
        51: ["das Italienisch", "italština"], 
        52: ["Kroatien", "Chorvatsko"],
        53: ["das Land /Länder", "země, stát"], 
        54: ["der Lehrer", "učitel"],
        55: ["die Lehrerin /-nen", "učitelka"],      
        56: ["der Manager", "manažer"],        
        57: ["Polen", "Polsko"],      
        58: ["das Polnisch", "polština"],        
        59: ["das Russisch", "ruština"],      
        60: ["Russland", "Rusko"],        
        61: ["die Schweiz", "Švýcarsko"],      
        62: ["die Slowakei", "Slovensko"],        
        63: ["das Slowakisch", "slovenština"],      
        64: ["Spanien", "Španělsko"],        
        65: ["die Sprache /-n", "jazyk, řeč"],      
        66: ["der Student /-en", "student"],        
        67: ["die Studentin /-nen", "studentka"],      
        68: ["Tschechien", "Česko"],        
        69: ["die Türkei", "Turecko"],      
        70: ["das Türkisch", "turečtina"],        
        71: ["das Ungarisch", "maďarština"],      
        72: ["Ungarn", "Maďarsko"],        
        73: ["die Verkäuferin /-nen", "prodavačka"],      
        74: ["welcher/welche/welches", "jaký/jaká/jaké"],        
        75: ["das Abitur /-e", "maturita"],      
        76: ["der Austausch /-e", "výměna"],        
        77: ["ein bisschen", "trochu"],      
        78: ["finden", "shlédavat, myslet si"],        
        79: ["interessant", "zajímavý"],      
        80: ["der Kurs /-e", "kurz"],        
        81: ["leider", "bohužel"],      
        82: ["mein/meine/mein", "můj/moje/moje"],        
        83: ["der Mensch /-en", "člověk"],      
        84: ["die Mutter /Mütter", "matka"],        
        85: ["noch", "ještě"],      
        86: ["Portugal", "Portugalsko"],        
        87: ["das Portugiesisch", "portugalština"],      
        88: ["Schweden", "Švédsko"],        
        89: ["das Schwedisch", "švédština"],      
        90: ["sehr", "velmi"],        
        91: ["studieren", "studovat"],      
        92: ["super", "super, skvělý"],        
        93: ["wenig", "málo"],      
        94: ["das Wort /Wörter", "slovo"],        
        95: ["Deutscher/Deutsche", "Němec/Němka"],      
        96: ["Engländer/Engländerin", "Angličan/Angličanka"],        
        97: ["Franzose/Französin", "Prancouz/Francouzka"],      
        98: ["Italiener/Italienerin", "Ital/Italka"],        
        99: ["die Natiolität /-en", "národnost"],      
        100: ["Österreicher/Österreicherin", "Rakušan/Rakušanka"],          
        101: ["Russe/Russin", "Rus/Ruska"],          
        102: ["Schweizer/Schweizerin", "Švýcar/Švýcarka"],          
        103: ["Slowake/Slowakin", "Slovák/Slovenka"],          
        104: ["Spanier/Spanierin", "Španěl/Španělka"],          
        105: ["Tscheche/Tschechin", "Čech/Češka"],          
        106: ["dreißig", "30"],          
        107: ["vierzig", "40"],          
        108: ["fünfzig", "50"],          
        109: ["sechzig", "60"],          
        110: ["siebzig", "70"],          
        111: ["achtzig", "80"],          
        112: ["neunzig", "90"],          
        113: ["(ein) hundert", "100"],          
        114: ["(ein) tausend", "1000"],          
        115: ["das Afrika", "Afrika"],          
        116: ["die Arbeit /-en", "práce"],          
        117: ["das Asien", "Asie"],          
        118: ["das Australien", "Austrálie"],          
        119: ["beginnen", "začít, začínat"],          
        120: ["danke", "děkuji, díky"],          
        121: ["das Europa", "Evropa"],          
        122: ["ganz", "celý"],          
        123: ["gehen", "jít"],          
        124: ["genau", "přesně"],          
        125: ["morgen", "zítra"],          
        126: ["nur", "jen"],          
        127: ["der Rekord /-e", "rekord"],          
        128: ["schon", "již, už"],              
        129: ["das Semester", "semestr"],             
        130: ["das Südamerika", "Jižní Amerika"],             
        131: ["die USA (mn.č.)", "USA"],             
        132: ["viel", "hodně"],             
        133: ["die Welt", "svět"],             
        "počet": 134
    },
    3: {
        0: ["die Geburtstagsparty", "narozeninová oslava"],
        1: ["das Haustier /-e", "domácí zvíře"],
        2: ["die Aktivität /-en", "aktivita"],
        3: ["der Staummbaum /Staubäume", "rodokmen"],
        4: ["der Bruder /Brüder", "bratr"],
        5: ["der Cousin /-s", "bratranec"],
        6: ["die Cousine /-n", "sestřenice"],
        7: ["die Ehefrau /-en", "manželka"],
        8: ["der Ehemann /Ehemänner", "manžel"],
        9: ["das Einzelkind /-er", "jedináček"],
        10: ["die Eltern", "rodiče"],
        11: ["die Familie /-n", "rodina"],
        12: ["feiern", "slavit, oslavovat"],
        13: ["das Fest /-e", "oslava, slavnost"],
        14: ["der Garten /Gärten", "zahrada"],
        15: ["gehören", "patřit"],
        16: ["geschieden", "rozvedený"],
        17: ["die Geschwister", "sourozenec"],
        18: ["gleich", "stejný"],
        19: ["groß", "velký"],
        20: ["haben", "mít"],
        21: ["das Haus /Häuser", "dům"],
        22: ["hier", "zde, tady"],
        23: ["der Hund /-e", "pes"],
        24: ["ihr/ihre/ihr", "její"],
        25: ["der Iran", "Írán"],
        26: ["der Job /-s", "(pracovní) místo, zaměstnání"],
        27: ["der Kater", "kocour"],
        28: ["lange", "dlouho"],
        29: ["manchmal", "někdy, občas"],
        30: ["mehr", "více, již"],
        31: ["nämlich", "totiž"],
        32: ["natürlich", "samozřejmě"],
        33: ["neu", "nový"],
        34: ["die Oma /-s", "babička"],
        35: ["der Onkel", "strýc"],
        36: ["der Opa /-s", "dědeček"],
        37: ["die Patchworkfamilie /-n", "patchworková rodina"],
        38: ["Persisch", "perština, persky"],
        39: ["die Person /-en", "osoba"],
        40: ["die Schwester /-n", "sestra"],
        41: ["sehen", "vidět"],
        42: ["die Stiefmutter /Stiefmütter", "nevlastní matka"],
        43: ["die Stiefschwester /-n", "nevlastní sestra"],
        44: ["die Tante /-n", "teta"],
        45: ["die Tochter /Töchter", "dcera"],
        46: ["tot", "mrtvý"],
        47: ["typsich", "typický, klasický"], 
        48: ["unser, unsere, unser", "náš, naše, naše"],
        49: ["der Vater /Väter", "otec"], 
        50: ["verstehen sich", "rozumět si"],
        51: ["der/die Verwandte /-n", "příbuzný, příbuzná"], 
        52: ["die Wohngemeinschaft /-en", "společné bydlení (studentů)"],
        53: ["zusammen", "spolu, dohromady"], 
        54: ["der Zwilling /-e", "dvojče"],
        55: ["dein, deine, dein", "tvůj, tovje, tvoje"],      
        56: ["euer, eure, euer", "váš, vaše, vaše"],        
        57: ["ihr, ihre, ihr", "jejich"],      
        58: ["sein, seine, sein", "jeho"],        
        59: ["bitte", "prosím"],      
        60: ["dann", "tak, pak"],        
        61: ["dauern", "trvat"],      
        62: ["doch", "přece"],        
        63: ["ein|laden", "pozvat"],      
        64: ["die Feier /-n", "oslava, slavnost"],        
        65: ["fragen", "ptát se "],      
        66: ["der Geburtstag /-e", "narozeniny"],        
        67: ["grillen", "grilovat"],      
        68: ["die Idee /-n", "nápad, myšlenka"],        
        69: ["die Köchin /-nen", "kuchařka"],      
        70: ["der Kuchen", "koláč, moučník"],        
        71: ["das Menü /-s", "menu"],      
        72: ["ob", "jestli"],        
        73: ["der Papa /-s", "tatínek"],      
        74: ["die Party /-s", "party, večírek"],        
        75: ["das Restaurant /-s", "restaurace"],      
        76: ["schrecklich", "strašný, hrozný"],        
        77: ["die Schwarzwälder Kirschtorte", "Schwarzwaldský dort"],      
        78: ["singen", "zpívat"],        
        79: ["stimmen", "souhlasit"],      
        80: ["die Vorbereitung /-en", "příprava"],        
        81: ["wieder", "opět, zase"],      
        82: ["zu Hause", "doma"],        
        83: ["das Chamäleon /-s", "chameleon"],      
        84: ["der Goldfisch /-e", "akvarijní rybka (karas)"],        
        85: ["der Hamster", "křeček"],      
        86: ["der Kanarienvogel", "kanárek"],        
        87: ["das Kaninchen", "králík"],      
        88: ["die Katze /-n", "kočka"],        
        89: ["das Meerschweinchen", "morče"],      
        90: ["das Pferd /-e", "kůň"],        
        91: ["die Schildkröte /-n", "želva"],      
        92: ["das Tier /-e", "zvíře"],        
        93: ["das Ausflug /Ausflüge", "výlet"],      
        94: ["die Ausstellung /-en", "výstava"],        
        95: ["die Burg /-en", "hrad"],      
        96: ["cool", "cool, super"],        
        97: ["es gibt", "je, existuje"],      
        98: ["das Hochzeitsfest /-e", "svatební párty"],        
        99: ["die Hochzeitstorte /-n", "svatební dort"],      
        100: ["nach", "zde: do"],    
        101: ["nächster, nächste, nächstes", "příští"],  
        102: ["das Schloss /Schlösser", "zámek"],  
        103: ["das Schwimmbad /Schwimmbäder", "koupaliště, plavecký bazén"],  
        104: ["der Schwimmbadbesuch /-e", "návštěva koupaliště, plaveckého bazénu"],  
        105: ["schwimmen", "plavat"],        
        106: ["shoppen", "nakupovat"],
        107: ["das Sportevent /-s", "sportovní akce (zápas, závody)"],         
        108: ["der Vergnügungspark /-s", "zábavní park"],         
        109: ["wandern", "putovat, cestovat"],          
        110: ["die Woche /-n", "týden"],         
        111: ["der Zoo /-s", "zoo"],         
        112: ["der Zopobesuch /-e", "návštěva zoo"],         
        113: ["das Einkaufszentrum", "nákupní centrum"],           
        114: ["der Inliner", "inline brusle"],           
        115: ["der See /-n", "jezero"],           
        116: ["das Wochenende /-n", "víkend"],           
        117: ["das Wochenendhaus ", "chata, chalupa"],  
        "počet": 118
    },
    4: {
        0: ["die Freizeit", "volný čas"],
        1: ["", ""],
        2: ["", ""],
        3: ["", ""],
        4: ["", ""],
        5: ["", ""],
        6: ["", ""],
        7: ["", ""],
        8: ["", ""],
        9: ["", ""],
        10: ["", ""],
        11: ["", ""],
        12: ["", ""],
        13: ["", ""],
        14: ["", ""],
        15: ["", ""],
        16: ["", ""],
        17: ["", ""],
        18: ["", ""],
        19: ["", ""],
        20: ["", ""],
        21: ["", ""],
        22: ["", ""],
        23: ["", ""],
        24: ["", ""],
        25: ["", ""],
        26: ["", ""],
        27: ["", ""],
        28: ["", ""],
        29: ["", ""],
        30: ["", ""],
        31: ["", ""],
        32: ["", ""],
        33: ["", ""],
        34: ["", ""],
        35: ["", ""],
        36: ["", ""],
        37: ["", ""],
        38: ["", ""],
        39: ["", ""],
        40: ["", ""],
        41: ["", ""],
        42: ["", ""],
        43: ["", ""],
        44: ["", ""],
        45: ["", ""],
        46: ["", ""],
        47: ["", ""], 
        48: ["", ""],
        49: ["", ""], 
        50: ["", ""],
        51: ["", ""], 
        52: ["", ""],
        53: ["", ""], 
        54: ["", ""],
        55: ["", ""],      
        56: ["", ""],        
        57: ["", ""],      
        58: ["", ""],        
        59: ["", ""],      
        60: ["", ""],        
        61: ["", ""],      
        62: ["", ""],        
        63: ["", ""],      
        64: ["", ""],        
        65: ["", ""],      
        66: ["", ""],        
        67: ["", ""],      
        68: ["", ""],        
        69: ["", ""],      
        70: ["", ""],        
        71: ["", ""],      
        72: ["", ""],        
        73: ["", ""],      
        74: ["", ""],        
        75: ["", ""],      
        76: ["", ""],        
        77: ["", ""],      
        78: ["", ""],        
        79: ["", ""],      
        80: ["", ""],        
        81: ["", ""],      
        82: ["", ""],        
        83: ["", ""],      
        84: ["", ""],        
        85: ["", ""],      
        86: ["", ""],        
        87: ["", ""],      
        88: ["", ""],        
        89: ["", ""],      
        90: ["", ""],        
        91: ["", ""],      
        92: ["", ""],        
        93: ["", ""],      
        94: ["", ""],        
        95: ["", ""],      
        96: ["", ""],        
        97: ["", ""],      
        98: ["", ""],        
        99: ["", ""],      
        100: ["", ""],    
        "počet": 1
    },
    5: {
        0: ["die Lebensmittel (mn.č.)", "potraviny"],
        1: ["die Spezialität /-en", "specialita"],
        2: ["das Abendessen", "večeře"],
        3: ["die Apfelschorle /-n", "jablečný střik"],
        4: ["das Bier", "pivo"],
        5: ["der Braten", "pečeně"],
        6: ["das Brot /-e", "chléb"],
        7: ["das Brötchen", "žemle, houska"],
        8: ["die Butter", "máslo"],
        9: ["die Cola", "kola"],
        10: ["das Ei /-er", "vejce"],
        11: ["das Eis", "zmrzlina"],
        12: ["der Fisch /-e", "ryba"],
        13: ["das Fleisch", "maso"],
        14: ["die Frikadelle /-n", "karbanátek"],
        15: ["das Frühstück /-e", "snídaně"],
        16: ["das Gemüse", "zelenina"],
        17: ["der Hamburger", "hamburger"],
        18: ["der Honig", "med"],
        19: ["der/das Joghurt /-s", "jogurt"],
        20: ["der Kaffee /-s", "kafe"],
        21: ["die Kartoffel /-n", "brambor"],
        22: ["der Käse", "sýr"],
        23: ["der Kuchen", "koláč, moučník"],
        24: ["die Marmelade /-n", "marmeláda"],
        25: ["die Milch", "mléko"],
        26: ["das Mittagessen", "oběd"],
        27: ["das Müsli /-s", "müsli"],
        28: ["die Nudel /-n", "nudle, těstovina"],
        29: ["das Obst", "ovoce"],
        30: ["die Pizza /-s / Pizzen", "pizza"],
        31: ["die Pommes frites, Pommes", "hranolky"],
        32: ["der Reis", "rýže"],
        33: ["der Saft /Säfte", "šťáva, džus"],
        34: ["der Salat /-e", "salát"],
        35: ["der Schinken", "šunka"],
        36: ["das Schnitzel", "řízek"],
        37: ["die Soße /-n", "omáčka"],
        38: ["das Steak /-s", "steak"],
        39: ["der Tee /-s", "čaj"],
        40: ["die Torte /-n", "dort"],
        41: ["das Wasser /Wässer", "voda"],
        42: ["die Wurst /Würste", "salám, uzenina, klobása"],
        43: ["das Würstchen", "párek"],
        44: ["zu Mittag essen", "obědvat"],
        45: ["zu Abend essen", "večeřet"],
        46: ["ausgezeichnet", "výborný, skvělý"],
        47: ["die Banane /-n", "banán"], 
        48: ["bitter", "hořký"],
        49: ["der Chili /-s", "chilli"], 
        50: ["ekelhaft", "hnusný, odporný"],
        51: ["essen", "jíst"], 
        52: ["der Essig, -e", "ocet"],
        53: ["fade", "mdlý, bez chuti"], 
        54: ["das Gericht, -e", "jídlo, pokrm"],
        55: ["der Geschmack, Geschmäcke", "chuť"],      
        56: ["gesund", "zdravý"],        
        57: ["die Grapefruit, -s", "grapefruit"],      
        58: ["kalt", "chladný, studený"],        
        59: ["lạngweilig", "nudný"],      
        60: ["lẹcker", "chutný, lahodný"],        
        61: ["der Pfẹffer", "pepř"],      
        62: ["das Sạlz", "sůl"],        
        63: ["sạlzig", "slaný"],      
        64: ["sauer", "kyselý"],        
        65: ["schạrf", "ostrý, pálivý"],      
        66: ["schmẹcken", "chutnat"],        
        67: ["süß", "sladký"],      
        68: ["tọll", "skvělý, úžasný"],        
        69: ["trịnken", "pít"],      
        70: ["ụnappetitlich", "nechutný, nedobrý"],        
        71: ["ụngesund", "nezdravý"],      
        72: ["die Zitrone, -n", "citron"],        
        73: ["der Zụcker", "cukr"],      
        74: ["das Bestẹck, -e", "příbor"],        
        75: ["die Gabel, -n", "vidlička"],      
        76: ["das Glas, Gläser", "sklenice"],        
        77: ["lieber", "raději"],      
        78: ["der Lọ̈ffel, -", "lžíce"],        
        79: ["mạn", "(všeobecný podmět/neosobní zájmeno)"],      
        80: ["das Mẹsser, -", "nůž"],        
        81: ["das Mineralwasser, Mineralwässer", "minerální voda"],      
        82: ["die Serviẹtte, -n", "ubrousek"],        
        83: ["die Sụppe, -n", "polévka"],      
        84: ["der Teelöffel, -", "(čajová) lžička"],        
        85: ["der Tẹller, -", "talíř"],      
        86: ["der Tịsch, -e", "stůl"],        
        87: ["der Wein, -e", "víno"],      
        88: ["der Zahnstocher, -", "párátko"],        
        89: ["alkoholfrei", "nealkoholický"],      
        90: ["bezahlen", "(za)platit"],        
        91: ["der Caesar-Salat, -e", "Caesar salát"],      
        92: ["empfehlen", "doporučit"],        
        93: ["gegrịllt", "grilovaný"],      
        94: ["das Hähnchen, -", "kuře"],        
        95: ["hausgemacht", "domácí"],      
        96: ["der Kartọffelsalat, -e", "bramborový salát"],        
        97: ["der Kẹllner, -", "číšník"],      
        98: ["Lạchsfilet, -s", "filet z lososa"],        
        99: ["möcht", "chtít (podmiňovací tvar slovesa mögen), on by chtěl, on by rád, on by si přál"],      
        100: ["nehmen", "vzít, brát"],    
        101: ["sofọrt", "hned"],  
        102: ["die Speisekarte, -n", "jídelní lístek"],  
        103: ["sprịtzig", "perlivý"],  
        104: ["stịll", "neperlivý"],  
        105: ["der Tịsch, -e", "stůl"],  
        106: ["vielleicht", "asi, možná"],  
        107: ["der Ạpfel, Äpfel", "jablko"],  
        108: ["Ạpfelstrudel, -", "jablečný závin"],  
        109: ["Bauernsalat, -e", "(zeleninový) salát "],  
        110: ["Blaubeere, -n", "borůvka"],  
        111: ["Dụrst", "žízeň"], 
        112: ["gemịscht", "míchaný"],   
        113: ["das Geschẹnk, -e", "dárek"],   
        114: ["das Getrạ̈nk, -e", "nápoj"],   
        115: ["das Grịllhähnchen, -", "grilované kuře"],   
        116: ["das/der Gụlasch, -e/-s", "guláš"],   
        117: ["die Gụlaschsuppe, -n", "gulášová polévka"],   
        118: ["der Hụnger", "hlad"],   
        119: ["kaufen", "koupit, kupovat"],   
        120: ["der Knödel, -", "knedlík"], 
        121: ["kọsten", "stát (o ceně)"], 
        122: ["das Kraut, Kräuter", "zelí"],    
        123: ["die Lasạgne, -n", "lasagne"],    
        124: ["die Limonade, -n", "limonáda"],    
        125: ["die Nachspeise, -n", "zákusek, dezert"],    
        126: ["nichts", "nic"],    
        127: ["der Pfạnnkuchen, -", "palačinka; kobliha"],    
        128: ["die Plạtte, -n", "mísa, tác"],    
        129: ["das/der Radler, -", "radler (nápoj z piva a limonády)"],    
        130: ["das/der Rịndergulasch, -e/-s", "hovězí guláš"],    
        131: ["die Rọ̈stzwiebel, -n", "smažená cibule"],    
        132: ["die Sahne", "smetana"],    
        133: ["die Sạlzkartoffeln", "vařené brambory"],    
        134: ["der Schweinebraten/Schweinsbraten, -", "vepřová pečeně"],    
        135: ["die Schweinshaxe, -n", "(pečené) vepřové koleno"],    
        136: ["die Spạ̈tzle", "špecle"],    
        137: ["die Tạsse, -n", "šálek"],    
        138: ["die Tomate, -n", "rajče"],    
        139: ["die Vanịllesoße, -n", "vanilková omáčka"],    
        140: ["vegetarisch", "vegetariánský"], 
        141: ["die Vorspeise, -n", "předkrm"], 
        142: ["wạrm", "teplý"], 
        143: ["die Adrẹsse, -n", "adresa"], 
        144: ["das Ambiẹnte ", "prostředí, atmosféra"], 
        145: ["der Bescheid, -e", "zpráva, informace"], 
        146: ["der Blạttspinat", "listový špenát"], 
        147: ["Brat- (wurst, kartoffeln)", "smažený, pečený (klobása, brambory)"], 
        148: ["der Döner, -", "döner (kebab)"], 
        149: ["das Ẹssen, -", "jídlo"], 
        150: ["der Gạsthof, Gasthöfe", "hostinec"],  
        151: ["geben", "dát, dávat"],  
        152: ["das Gẹld, -er", "peníze"],  
        153: ["gemütlich", "útulný, pohodový"],  
        154: ["international", "mezinárodní"],  
        155: ["die Kẹrze, -n", "svíčka"],  
        156: ["die Kụ̈che, -n", "kuchyně"],  
        157: ["die Meeresfrüchte", "plody moře"],  
        158: ["mịt|nehmen", "vzít s sebou"],  
        159: ["der Plạtz, Plätze", "místo; náměstí"],  
        160: ["die Prüfung, -en", "zkouška"], 
        161: ["reservieren", "rezervovat"], 
        162: ["der Ruhetag, -e", "zavírací den"], 
        163: ["das Rührei, -er", "míchaná vejce"], 
        164: ["die Spaghẹtti, -", "špagety"], 
        165: ["täglich", "denní, denně"], 
        166: ["der Tịpp, -s", "tip"], 
        167: ["die Vorsicht", "opatrnost"], 
        168: ["das Zạnderfilet, -s", "filet z candáta"], 
        169: ["beidseitig", "z obou stran, oboustranný"], 
        170: ["braten", "péci, smažit"], 
        171: ["erhịtzen", "zahřát, ohřát"],
        172: ["der Ẹsslöffel, - ", "polévková lžíce"], 
        173: ["der Kọpfsalat, -e", "hlávkový salát"], 
        174: ["mịld", "jemný"], 
        175: ["die Minute, -n", "minuta"], 
        176: ["mịschen", "(s)míchat"], 
        177: ["schneiden", "(na)krájet"], 
        178: ["die Schụ̈ssel, -n", "mísa, miska"], 
        179: ["der Sẹnf, -e", "hořčice"], 
        180: ["das Stụ̈ck, -e", "kus, kousek"],  
        181: ["trọcknen", "(o)sušit, (u)sušit"],  
        182: ["wạschen", "(o)mýt, (u)mýt"],  
        183: ["wụ̈rzen", "(o)kořenit"],  
        184: ["zụpfen", "(na)trhat"],  
        185: ["am besten", "nejlépe"],  
        186: ["das/der Bịskuit, -s/-e", "biskvit, sušenka"],  
        187: ["das Cụrrypulver, -", "kari prášek"],  
        188: ["die Cụrrywurst, Currywürste", "Currywurst (klobása politá kečupem a posypaná kari kořením)"],  
        189: ["dazu", "k tomu"],  
        190: ["fạst", "skoro, téměř, málem"],  
        191: ["geschnịtten", "nakrájený"],  
        192: ["das Kạlbfleisch", "telecí maso"],  
        193: ["kẹnnen", "znát"],  
        194: ["der/das Kẹtchup, -s", "kečup"],  
        195: ["die Kịrsche, -n", "třešně"],  
        196: ["mạn", "(všeobecný podmět)"],  
        197: ["die Schokoladenraspeln", "čokoládové hobliny"],  
        198: ["speziẹll", "speciální, zvláštní"],  
        199: ["das Trịnkgeld, -er", "spropitné"], 
        200: ["verkaufen", "prod(áv)at"],  
        201: ["wụnderbar", "báječný, skvělý"],  
        "počet": 202
    },
    6: {
        0: ["die Freizeitaktivität /-en", "volnočasová aktivita"],
        1: ["die Morgenroutine /-n", ""],
        2: ["jobben", "mít brigádu"],
        3: ["die Pflicht", "povinnost"],
        4: ["am liebsten", "nejraději"],
        5: ["an|fangen", "začí(na)t"],
        6: ["an|machen", "zapnout, pustit"],
        7: ["an|rufen", "(za)volat"],
        8: ["sich an|ziehen", "obléknout se"],
        9: ["auf|räumen", "uklízet"],
        10: ["auf|stehen", "vstá(va)t"],
        11: ["auf|wachen", "probudit se"],
        12: ["aus|leeren", "vysypat, vyprázdnit"],
        13: ["aus|räumen", "vyklidit"],
        14: ["aus|sehen", "vypadat"],
        15: ["das Bad /Badër", "koupelna"],
        16: ["das Badezimmer", "koupelna"],
        17: ["das Bild /-er", "obraz"],
        18: ["dabei", "při tom"],
        19: ["drehen", "natáčet"],
        20: ["duschen", "sprchovat se"],
        21: ["ein|kaufen", "nakupovat"],
        22: ["ein|schlafen", "usnout"],
        23: ["das Ende /-n", "konec"],
        24: ["endlich", "konečně"],
        25: ["fern|sehen", "dívat se na televizi"],
        26: ["fertig", "hotový"],
        27: ["halb", "půl"],
        28: ["das Horror (j.č.)", "horor"],
        29: ["Hurra!", "Hurá!"],
        30: ["die Kamera /-s", "kamera, fotoaparát"],
        31: ["klingeln", "zvonit"],
        32: ["das Lieblingsfach /Lieblingsfächer", "oblíbený předmět"],
        33: ["mit|nehmen", "vzít s sebou"],
        34: ["müde", "unavený"],
        35: ["das Mülleimer", "odpadkový koš"],
        36: ["putzen", "(vy)čistit"],
        37: ["saugen", "vysávat"],
        38: ["schlafen", "spát"],
        39: ["(sich) schminken", "líčit se"],
        40: ["die Spülmaschine /-n", "myčka, nádobí"],
        41: ["der Staub (j.č.)", "prach"],
        42: ["der Unterricht (j.č.)", "vyučování"],
        43: ["das/der Viertel", "čtvrt"],
        44: ["vloggen", "natáčet vlog (videoblog)"],
        45: ["(sich) vor|bereiten", "připravovat (se)"],
        46: ["der Wecker", "budík"],
        47: ["zeigen", "ukázat"], 
        48: ["zu|bereiten", "připravit (jídlo)"],
        49: ["züruck|kommen", "vrátit se"], 
        50: ["aus|schalten", "vypnout"],
        51: ["ein|schalten", "zapnout"], 
        52: ["wen", "koho"],
        53: ["die Uhrzeit /-en", "(přesný) čas"], 
        54: ["das Bett /-en", "postel"],
        55: ["der Blogger", "bloger"],      
        56: ["entdecken", "objevit, najít"],        
        57: ["(sich) entschuldigen", "omluvit (se)"],      
        58: ["erzählen", "vyprávět"],        
        59: ["kommentieren", "komentovat"],      
        60: ["liken", "likovat"],        
        61: ["posten", "postovat (příspěvky)"],      
        62: ["der Trend /-s", "trend"],        
        63: ["verbringen", "strávit"],      
        64: ["vergessen", "zapomenout"],        
        65: ["weiter", "dále"],      
        66: ["wissen", "vědět"],        
        67: ["dienstags", "každé úterý"],      
        68: ["donnerstags", "každý čtvrtek"],        
        69: ["freitags", "každý pátek"],      
        70: ["der Kanal /Kanäle", "program, kanál"],        
        71: ["Lieblings-(kanal...)", "oblíbený (kanál)"],      
        72: ["die Mitternacht /Mitternächte", "půlnoc"],        
        73: ["mittwochs", "každou středu"],      
        74: ["montags", "každé pondělí"],        
        75: ["morgens", "každé ráno"],      
        76: ["der Nachmittag /-e", "odpoledne"],        
        77: ["nachmittags", "každé odpoledne"],      
        78: ["samstags", "každou sobotu"],        
        79: ["sonntags", "každou neděli"],      
        80: ["das Training /-s", "trénink"],        
        81: ["der Vormmittag /-e", "dopoledne"],      
        82: ["vormittags", "každé dopoledne"],        
        83: ["die Weltmeisterschaft /-en", "mistrovství světa"],      
        84: ["durch", "přes, skrz"],        
        85: ["die Ecke", "roh"],      
        86: ["gegen", "proti"],        
        87: ["lieb", "milý, milovaný"],      
        88: ["das Mädchen", "dívka"],        
        89: ["ohne", "bez"],      
        90: ["der Park /-s", "park"],        
        91: ["der Schatz /Schätze", "poklad, zlatíčko"],      
        92: ["der Stress /-e", "stres"],        
        93: ["die Berufsschule /-n", "učňovská škola"],      
        94: ["dumm", "hloupý"],        
        95: ["die Fachschule /-n", "odborná škola"],      
        96: ["ab|holen", "vyzvednout"],        
        97: ["der Kindergarten /Kindergärten", "mateřská škola"],      
        98: ["das Krankenhaus /Krankenhäuser", "nemocnice"],        
        99: ["sich treffen", "setkat se"],         
        "počet": 100
    },
    7: {
        0: ["die Beziehung /-en", "vztah"],
        1: ["die Eigenschaft /-en", "vlasnost"],
        2: ["arrogant", "arogantní"],
        3: ["besichtigen", "prohlédnout si"],
        4: ["doof", "pitomý hloupý"],
        5: ["echt", "fakt, opravdu"],
        6: ["einmal", "jednou"],
        7: ["die Freundesliste", "seznam přátel"],
        8: ["gefallen", "líbit se"],
        9: ["gehören", "patřit"],
        10: ["helfen", "pomoci, pomáhat (někomu)"],
        11: ["hilfsbereit", "ochotný pomoci"],
        12: ["hübsch", "hezký, pěkný"],
        13: ["humorvoll", "vtipný"],
        14: ["klicken", "kliknout"],        
        15: ["lachen", "smát se"],
        16: ["laufen", "běhat, běžet"],
        17: ["lieben", "milovat, mít rád"],
        18: ["lustig", "veselý, vtipný"],
        19: ["die Medizin (j.č)", "medicína"],
        20: ["originell", "originální, osobitý"],
        21: ["per", "čím"],
        22: ["das Reisen (j.č)", "cestování"],
        23: ["schenken", "darovat"],   
        24: ["schicken", "poslat"],
        25: ["die Süßigkeit /-en", "sladkost, cukrovinka"], 
        26: ["sympatisch", "sympatický"],
        27: ["das T-Shirt /-s", "tričko"], 
        28: ["unzufrieden", "nespokojený"],
        29: ["der Wald /Waldër", "les"], 
        30: ["das Witz /-e", "vtip"],
        31: ["das Aussehen (j.č.)", "vzhled"], 
        32: ["böse", "zlý"],
        33: ["der Charakter /-e", "charakter"], 
        34: ["dick", "tlustý"],
        35: ["frech", "drzý"], 
        36: ["hässlich", "ošklivý"],
        37: ["klein", "malý"], 
        38: ["die Persönlichkeit /-en", "osobnost"],
        39: ["schlank", "štíhlý"], 
        40: ["verschieden", "různý"],
        41: ["das Problem /-e", "problém"], 
        42: ["das Abonnement /-s", "předplatné"],
        43: ["das Armband /Armbänder", "náramek"], 
        44: ["die Blume /-n", "květina"],
        45: ["der Gutschein /-e", "poukaz"], 
        46: ["die Handyfolie /-n", "obal na mobilní telefon"],
        47: ["der Kalender", "kalendář"], 
        48: ["die Klatmotte /-n", "oblečení(hadry)"], 
        49: ["die Kosmetik (j.č.)", "kosmetika"], 
        50: ["das Kosmetik-Set /-s", "kosmetický balíček"],
        51: ["das Ladegerät", "nabíječka"], 
        52: ["der Lautsprecher", "reproduktor"],
        53: ["leer", "prázdný"], 
        54: ["der Muttertag /-e", "Den matek"],
        55: ["die Selfie-Stange /-n", "selfie tyč"],      
        56: ["das Ticket /-s", "vstupenka"],        
        57: ["das Weihnachten", "Vánoce"],      
        58: ["der Fanatiker", "fanatik"],        
        59: ["geben", "dávat, dát"],      
        60: ["insgesamt", "celkem"],        
        61: ["das Prozent", "procento"],      
        62: ["das Schuljahr", "školní rok"],        
        63: ["witzig", "vtipný"],      
        64: ["fair", "férový, spravedlivý"],        
        65: ["streng", "přísný"],      
        66: ["unfair", "nespravedlivý"],        
        67: ["unsympatisch", "nesympatický"],      
        68: ["Argentinien", "Argentina"],        
        69: ["das Märchen", "pohádka"],      
        70: ["Rad fahren", "jezdit na kole"],        
        71: ["die Sofortbildkamera /-s", "polaroid"],      
        72: ["die Spielkarte /-n", "hrací karta"],        
        73: ["das Fotografieren (j.č.)", "fotografování"],      
        74: ["die Mode /-n", "móda"],        
        75: ["das Radfahren (j.č.)", "jízda na kole (cyklistika)"],   
        76: ["die Zeitschrift /-en", "časopis"],      
        "počet": 77
    },
    8: {
        0: ["das Geshäft/-e", "obchod"],
        1: ["der Treffpunkt /-e", "místo setkání"],
        2: ["(sich) aus|denken", "vymyslet"],
        3: ["bummeln", "procházet se"],
        4: ["der Bus /-se", "autobus"],
        5: ["danach", "potom, nato"],
        6: ["entfernt (sein)", "(být) vzdálený"],
        7: ["sich freuen", "těšit se (na co)"],
        8: ["der Fuß /Füße", "noha"],
        9: ["gegenüber", "naproti"],
        10: ["hoffen", "doufat, věřit"],
        11: ["das Kaufhaus / Kaufhäuser", "obchodní dům"],
        12: ["mit|bringen", "přinést s sebou"],
        13: ["die Nachricht /-en", "zpráva"],
        14: ["die Pizzeria /Pizzerien/Pizzerias", "pizzeria"],
        15: ["die Schwimmhale /-n", "krytý bazén"],
        16: ["die Straße", "ulice"],
        17: ["übernachten", "přenocovat"],
        18: ["gerade", "právě, zrovna"],
        19: ["die Konditorei /-en", "cukrárna"],
        20: ["die Mozartschnitten", "Mozartovy řezy"],
        21: ["der Zug /Züge", "vlak"],
        22: ["direkt", "přímy, přímo"],
        23: ["der Dome /-e", "dóm, katedrála"],
        24: ["die Festung /-en", "pevnost"],
        25: ["der Flughafen /Flughäufen", "letiště"],
        26: ["die Gasse /-n", "ulička, ulice"],
        27: ["das Geburtshaus /Geburtshäuser", "rodný dům"],
        28: ["der Hauptbahnhof /Hauptbahnhöfe", "hlavní nádraží"],
        29: ["das Hotel /-s", "hotel"],
        30: ["die Mozartkugeln", "Mozartovy koule"],
        31: ["der Plan /Pläne", "plán"],
        32: ["die Wohnung /-en", "byt"],
        33: ["die Abteilung /-en", "oddělení"],
        34: ["die Apotheke /-n", "lékarna"],
        35: ["die Bäckerei /-en", "pekařství, pekárna"],
        36: ["der Bioladen /Bioläuden", "bioobchod"],
        37: ["die Buchhandlung /-en", "knihkupectví"],
        38: ["die Delikatesse /-n", "lahůdka, delikatesa"],
        39: ["dritte", "třetí"],
        40: ["die Eisdiele /-n", "zmrzlinářství"],
        41: ["die Elektronik -en", "elektronika"],
        42: ["das Erdgeschoss /-e", "přízemí"],
        43: ["erste", "první"],
        44: ["die Etage /-n", "první"],
        45: ["finden", "najít"],
        46: ["die Garage /-n", "garáž"],
        47: ["die Haustechnik", "domácí technika"], 
        48: ["der Kinderraum /Kinderräume", "dětstký koutek"],
        49: ["der Laden /Läden", "obchod"], 
        50: ["die Metzgerei /-en", "řeznictví"],
        51: ["die Mode (Damen- /Herren- /Kindermode)", "móda (dámská/ pánská / dětstká)"], 
        52: ["neben", "vedle"],
        53: ["das Parfüm /-e/-s", "parfém"], 
        54: ["der Schmuck", "šperk, klenot"],
        55: ["der Schuh /-e", "bota"],      
        56: ["der Souvenirshop /-s", "obchod se suvenýry"],        
        57: ["das Spielzeug /-e/Spielsachen", "hračka"],      
        58: ["der Supermarkt /Supermärkte", "supermarket"],        
        59: ["die Toilette /-n", "záchod"],      
        60: ["das Untergeschoss /-e", "suterén"],        
        61: ["zweit(e)", "druhý(á)"],      
        62: ["besorgen", "obstarat"],        
        63: ["die Drogerie /-n", "drogerie"],      
        64: ["die Einkaufliste /-n", "nákupní seznam"],        
        65: ["frisch", "čertsvý"],      
        66: ["das Gramm /-/-e", "gram"],        
        67: ["der Keks /-e", "keks, sušenka"],      
        68: ["die Kleidung", "oblečení oděv"],        
        69: ["der Kiosk /-e", "stánek, kiosk"],      
        70: ["der/das Liter ", "litr"],        
        71: ["der Markt /Märkte", "trh/tržiště"],      
        72: ["das Medikament /-e", "lék"],        
        73: ["die Packung /-en", "balení"],      
        74: ["der Reiseführer ", "(cestovní) průvodce"],        
        75: ["das Shampoo /-s", "šampon"],      
        76: ["das Vollkornbrot /-e", "celozrnný chléb"],        
        77: ["die Zeitung /-en", "noviny"],      
        78: ["bekommen", "dostat"],        
        79: ["der Cent /-/-s", "cent"],      
        80: ["die Dose /-n", "plechovka, konzerva; dóza"],        
        81: ["ebenfalls", "rovněž, také"],      
        82: ["eigen", "vlastní, svůj"],        
        83: ["die Flasche /-n", "láhev"],      
        84: ["das Kilo /-(s)", "kilo(gram)"],        
        85: ["der Kunde /-n", "zákazník"],      
        86: ["probieren", "ochutnat; vyzkoušet"],        
        87: ["die Schachtel /-n", "krabička, krabice, balíček"],      
        88: ["sonst", "jinak"],        
        89: ["die Tafel /-n", "tabulka"],      
        90: ["die Tüte /-n", "sáček; igelitová taška"],        
        91: ["ab|fahren", "odjet"],      
        92: ["die Briefmarke /-n", "poštovní známka"],        
        93: ["joggen", "joggovat, běhat"],      
        94: ["die Post ", "pošta"],        
        95: ["das Stadion /Stadien", "stadion"],      
        96: ["der Trilobit /-en", "trilobit"],        
        97: ["der April", "duben"],      
        98: ["der August", "srpen"],        
        99: ["die Bühne /-n", "jeviště"],      
        100: ["der Dezember", "prosinec"],
        101: ["der Februar", "únor"],    
        102: ["der Januar", "leden"],   
        103: ["der Juli", "červenec"],     
        104: ["der Juni", "červen"],   
        105: ["die Karriere /-n", "kariéra"],   
        106: ["der Kinosaal /Kinosäle", "kinosál"],   
        107: ["der Mai", "květen"],   
        108: ["der März", "březen"],   
        109: ["der November", "listopad"],   
        110: ["der Oktober", "říjen"],   
        111: ["das Publikum", "publikum"],   
        112: ["der Sänger", "zpěvák"],   
        113: ["der September", "září"],   
        114: ["der Star /-s", "star, hvězda"],   
        115: ["vor|schlagen", "navrhnout, doporučit"],   
        116: ["werden", "stát se"],   
        "počet": 117
    },
    9: {
        0: ["die Wegbeschreibung/-e", "popis cesty"],
        1: ["", ""],
        2: ["", ""],
        3: ["", ""],
        4: ["", ""],
        5: ["", ""],
        6: ["", ""],
        7: ["", ""],
        8: ["", ""],
        9: ["", ""],
        10: ["", ""],
        11: ["", ""],
        12: ["", ""],
        13: ["", ""],
        14: ["", ""],
        15: ["", ""],
        16: ["", ""],
        17: ["", ""],
        18: ["", ""],
        19: ["", ""],
        20: ["", ""],
        21: ["", ""],
        22: ["", ""],
        23: ["", ""],
        24: ["", ""],
        25: ["", ""],
        26: ["", ""],
        27: ["", ""],
        28: ["", ""],
        29: ["", ""],
        30: ["", ""],
        31: ["", ""],
        32: ["", ""],
        33: ["", ""],
        34: ["", ""],
        35: ["", ""],
        36: ["", ""],
        37: ["", ""],
        38: ["", ""],
        39: ["", ""],
        40: ["", ""],
        41: ["", ""],
        42: ["", ""],
        43: ["", ""],
        44: ["", ""],
        45: ["", ""],
        46: ["", ""],
        47: ["", ""], 
        48: ["", ""],
        49: ["", ""], 
        50: ["", ""],
        51: ["", ""], 
        52: ["", ""],
        53: ["", ""], 
        54: ["", ""],
        55: ["", ""],      
        56: ["", ""],        
        57: ["", ""],      
        58: ["", ""],        
        59: ["", ""],      
        60: ["", ""],        
        61: ["", ""],      
        62: ["", ""],        
        63: ["", ""],      
        64: ["", ""],        
        65: ["", ""],      
        66: ["", ""],        
        67: ["", ""],      
        68: ["", ""],        
        69: ["", ""],      
        70: ["", ""],        
        71: ["", ""],      
        72: ["", ""],        
        73: ["", ""],      
        74: ["", ""],        
        75: ["", ""],      
        76: ["", ""],        
        77: ["", ""],      
        78: ["", ""],        
        79: ["", ""],      
        80: ["", ""],        
        81: ["", ""],      
        82: ["", ""],        
        83: ["", ""],      
        84: ["", ""],        
        85: ["", ""],      
        86: ["", ""],        
        87: ["", ""],      
        88: ["", ""],        
        89: ["", ""],      
        90: ["", ""],        
        91: ["", ""],      
        92: ["", ""],        
        93: ["", ""],      
        94: ["", ""],        
        95: ["", ""],      
        96: ["", ""],        
        97: ["", ""],      
        98: ["", ""],        
        99: ["", ""],      
        100: ["", ""],    
        "počet": 1
    },
    10: {
        0: ["der Sommer", "léto"],
        1: ["", ""],
        2: ["", ""],
        3: ["", ""],
        4: ["", ""],
        5: ["", ""],
        6: ["", ""],
        7: ["", ""],
        8: ["", ""],
        9: ["", ""],
        10: ["", ""],
        11: ["", ""],
        12: ["", ""],
        13: ["", ""],
        14: ["", ""],
        15: ["", ""],
        16: ["", ""],
        17: ["", ""],
        18: ["", ""],
        19: ["", ""],
        20: ["", ""],
        21: ["", ""],
        22: ["", ""],
        23: ["", ""],
        24: ["", ""],
        25: ["", ""],
        26: ["", ""],
        27: ["", ""],
        28: ["", ""],
        29: ["", ""],
        30: ["", ""],
        31: ["", ""],
        32: ["", ""],
        33: ["", ""],
        34: ["", ""],
        35: ["", ""],
        36: ["", ""],
        37: ["", ""],
        38: ["", ""],
        39: ["", ""],
        40: ["", ""],
        41: ["", ""],
        42: ["", ""],
        43: ["", ""],
        44: ["", ""],
        45: ["", ""],
        46: ["", ""],
        47: ["", ""], 
        48: ["", ""],
        49: ["", ""], 
        50: ["", ""],
        51: ["", ""], 
        52: ["", ""],
        53: ["", ""], 
        54: ["", ""],
        55: ["", ""],      
        56: ["", ""],        
        57: ["", ""],      
        58: ["", ""],        
        59: ["", ""],      
        60: ["", ""],        
        61: ["", ""],      
        62: ["", ""],        
        63: ["", ""],      
        64: ["", ""],        
        65: ["", ""],      
        66: ["", ""],        
        67: ["", ""],      
        68: ["", ""],        
        69: ["", ""],      
        70: ["", ""],        
        71: ["", ""],      
        72: ["", ""],        
        73: ["", ""],      
        74: ["", ""],        
        75: ["", ""],      
        76: ["", ""],        
        77: ["", ""],      
        78: ["", ""],        
        79: ["", ""],      
        80: ["", ""],        
        81: ["", ""],      
        82: ["", ""],        
        83: ["", ""],      
        84: ["", ""],        
        85: ["", ""],      
        86: ["", ""],        
        87: ["", ""],      
        88: ["", ""],        
        89: ["", ""],      
        90: ["", ""],        
        91: ["", ""],      
        92: ["", ""],        
        93: ["", ""],      
        94: ["", ""],        
        95: ["", ""],      
        96: ["", ""],        
        97: ["", ""],      
        98: ["", ""],        
        99: ["", ""],      
        100: ["", ""],    
        "počet": 1
    },
    "slovesa":{
        1:{
            0: ["heißen", "jmenovat se"],
            1: ["wohnen", "bydlet"],
            2: ["gehen", "jít"],        
            3: ["hören", "poslouchat"],  
            4: ["im internet surfen", "surfovat na internetu"],  
            5: ["kommen (aus)", "pocházet (z)"],      
            6: ["lernen", "učit se"],    
            7: ["liegen", "ležet"],
            8: ["reisen", "cestovat"], 
            9: ["schreiben", "psát"],  
            10: ["spielen", "hrát"],  
            11: ["tanzen", "tancovat"],
            12: ["haben", "mít"],
            13: ["machen", "dělat"], 
            14: ["Sport treiben", "sportovat"], 
            "počet": 15
        },
        2:{
            0: ["arbeiten", "pracovat"],
            1: ["brauchen", "potřebovat"],
            2: ["fahren", "jet, jezdit"],
            3: ["lesen", "číst"],
            4: ["sprechen", "mluvit"],
            5: ["besuchen", "navštěvovat, navštívit"],
            6: ["gewinnen", "vyhrát, vyhrávat"],
            7: ["leben", "žít"],
            8: ["finden", "shlédavat, myslet si"],        
            9: ["studieren", "studovat"], 
            10: ["beginnen", "začít, začínat"],
            11: ["gehen", "jít"],    
            "počet": 12
        },
        3:{
            0: ["feiern", "slavit, oslavovat"],
            1: ["gehören", "patřit"],
            2: ["wandern", "putovat, cestovat"],
            3: ["haben", "mít"],
            4: ["sehen", "vidět"],
            5: ["verstehen sich", "rozumět si"],
            6: ["dauern", "trvat"],
            7: ["ein|laden", "pozvat"],
            8: ["fragen", "ptát se, zeptat se"],
            9: ["grillen", "grilovat"],
            10: ["singen", "zpívat"],
            11: ["stimmen", "souhlasit"],
            12: ["es gibt", "je, existuje"],
            13: ["schwimmen", "plavat"],
            14: ["shoppen", "nakupovat"],
            "počet": 15
        },
        4:{
            0: ["stehen", "stát"],
            1: ["bestellen", "objednat"],
            2: ["denken", "myslet"],
            3: ["suchen", "hledat"],
            4: ["können", "umět, moci"],
            5: ["wollen", "chtít"],
            6: ["dürfen", "smět, moci"],
            7: ["sollen", "mít (něco udělat)"],
            8: ["bleiben", "zůstat"],  
            "počet": 9
        },
        5:{
            0: ["essen", "jíst"],
            1: ["schmecken", "chutnat"],
            2: ["trinken", "pít"],
            3: ["mögen", "mít rád"],
            4: ["bezahlen", "(za)platit"],
            5: ["möcht", "chtít"],
            6: ["nehmen", "vzít, brát"],
            7: ["kaufen", "koupit, kupovat"],
            8: ["reservieren", "rezervovat"],
            9: ["braten", "péci, smažit"],
            10: ["erhitzen", "zahřát, ohřát"],
            11: ["kochen", "vařit"],
            12: ["mischen", "(s)míchat"],
            13: ["schneiden", "(na)krájet"],
            14: ["trocknen", "(o)sušit, (u)sušit"],
            15: ["waschen", "(o)mýt, (u)mýt"],
            16: ["würzen", "(o)kořenit"],
            17: ["zupfen", "(na)trhat"],
            18: ["verkaufen", "prod(áv)at"],  
            "počet": 19
        },
        6:{
            0: ["jobben", "mít brigádu"],
            1: ["an|fangen", "začí(na)t"],
            2: ["an|machen", "zapnout, pustit"],
            3: ["an|rufen", "(za)volat"],
            4: ["sich an|ziehen", "obléknout se"],
            5: ["auf|räumen", "uklízet"],
            6: ["auf|stehen", "vstá(va)t"],
            7: ["auf|wachen", "probudit se"],
            8: ["aus|leeren", "vysypat, vyprázdnit"],
            9: ["aus|räumen", "vyklidit"],
            10: ["aus|sehen", "vypadat"],
            11: ["drehen", "natáčet"],
            12: ["duschen", "sprchovat se"],
            13: ["ein|kaufen", "nakupovat"],
            14: ["ein|schlafen", "usnout"],
            15: ["fern|sehen", "dívat se na televizi"],
            16: ["klingeln", "zvonit"],
            17: ["mit|nehmen", "vzít s sebou"],
            18: ["putzen", "(vy)čistit"],
            19: ["saugen", "vysávat"],
            20: ["schlafen", "spát"],
            21: ["(sich) schminken", "líčit se"],
            22: ["vloggen", "natáčet vlog (videoblog)"],
            23: ["(sich) vor|bereiten", "připravovat (se)"],
            24: ["zeigen", "ukázat"], 
            25: ["zu|bereiten", "připravit (jídlo)"],
            26: ["züruck|kommen", "vrátit se"], 
            27: ["aus|schalten", "vypnout"],
            28: ["ein|schalten", "zapnout"], 
            29: ["entdecken", "objevit, najít"],        
            30: ["(sich) entschuldigen", "omluvit (se)"],      
            31: ["erzählen", "vyprávět"],     
            32: ["kommentieren", "komentovat"],    
            33: ["liken", "likovat"],       
            34: ["posten", "postovat (příspěvky)"],     
            35: ["verbringen", "strávit"],   
            36: ["vergessen", "zapomenout"],  
            37: ["wissen", "vědět"], 
            38: ["ab|holen", "vyzvednout"],        
            39: ["sich treffen", "setkat se"],    
            "počet": 40
        },
        7:{
            0: ["besichtigen", "prohlédnout si"],
            1: ["gefallen", "líbit se"],
            2: ["gehören", "patřit"],
            3: ["helfen", "pomoci, pomáhat (někomu)"],
            4: ["klicken", "kliknout"],      
            5: ["lachen", "smát se"],
            6: ["laufen", "běhat, běžet"],
            7: ["lieben", "milovat, mít rád"],
            8: ["schenken", "darovat"],   
            9: ["schicken", "poslat"],
            10: ["geben", "dávat, dát"],      
            "počet": 11
        },
        8:{
            0: ["(sich) aus|denken", "vymyslet"],
            1: ["bummeln", "procházet se"],
            2: ["entfernt (sein)", "(být) vzdálený"],
            3: ["sich freuen", "těšit se (na co)"],
            4: ["hoffen", "doufat, věřit"],
            5: ["mit|bringen", "přinést s sebou"],
            6: ["übernachten", "přenocovat"],
            7: ["finden", "najít"],
            8: ["finden", "najít"],
            9: ["bekommen", "dostat"],        
            10: ["probieren", "ochutnat; vyzkoušet"],     
            11: ["joggen", "joggovat, běhat"],      
            12: ["vor|schlagen", "navrhnout, doporučit"],   
            13: ["werden", "stát se"],   
            "počet": 14
        },
        9:{
            0: ["", ""],
            1: ["", ""],
            2: ["", ""],
            3: ["", ""],
            4: ["", ""],
            5: ["", ""],
            6: ["", ""],
            7: ["", ""],
            8: ["", ""],
            9: ["", ""],
            10: ["", ""],
            11: ["", ""],
            12: ["", ""],
            13: ["", ""],
            14: ["", ""],
            15: ["", ""],
            16: ["", ""],
            17: ["", ""],
            18: ["", ""],
            19: ["", ""],
            20: ["", ""],
            21: ["", ""],
            22: ["", ""],
            23: ["", ""],
            24: ["", ""],
            25: ["", ""],
            26: ["", ""],
            27: ["", ""],
            28: ["", ""],
            29: ["", ""],
            30: ["", ""],
            31: ["", ""],
            32: ["", ""],
            33: ["", ""],
            34: ["", ""],
            35: ["", ""],
            36: ["", ""],
            37: ["", ""],
            38: ["", ""],
            39: ["", ""],
            40: ["", ""],
            41: ["", ""],
            42: ["", ""],
            43: ["", ""],
            44: ["", ""],
            45: ["", ""],
            46: ["", ""],
            47: ["", ""], 
            48: ["", ""],
            49: ["", ""], 
            50: ["", ""],
            51: ["", ""], 
            52: ["", ""],
            53: ["", ""], 
            54: ["", ""],
            55: ["", ""],      
            56: ["", ""],        
            57: ["", ""],      
            58: ["", ""],        
            59: ["", ""],      
            60: ["", ""],        
            61: ["", ""],      
            62: ["", ""],        
            63: ["", ""],      
            64: ["", ""],        
            65: ["", ""],      
            66: ["", ""],        
            67: ["", ""],      
            68: ["", ""],        
            69: ["", ""],      
            70: ["", ""],        
            71: ["", ""],      
            72: ["", ""],        
            73: ["", ""],      
            74: ["", ""],        
            75: ["", ""],      
            76: ["", ""],        
            77: ["", ""],      
            78: ["", ""],        
            79: ["", ""],      
            80: ["", ""],        
            81: ["", ""],      
            82: ["", ""],        
            83: ["", ""],      
            84: ["", ""],        
            85: ["", ""],      
            86: ["", ""],        
            87: ["", ""],      
            88: ["", ""],        
            89: ["", ""],      
            90: ["", ""],        
            91: ["", ""],      
            92: ["", ""],        
            93: ["", ""],      
            94: ["", ""],        
            95: ["", ""],      
            96: ["", ""],        
            97: ["", ""],      
            98: ["", ""],        
            99: ["", ""],      
            100: ["", ""],    
            "počet": 1
        },
        10:{
            0: ["", ""],
            1: ["", ""],
            2: ["", ""],
            3: ["", ""],
            4: ["", ""],
            5: ["", ""],
            6: ["", ""],
            7: ["", ""],
            8: ["", ""],
            9: ["", ""],
            10: ["", ""],
            11: ["", ""],
            12: ["", ""],
            13: ["", ""],
            14: ["", ""],
            15: ["", ""],
            16: ["", ""],
            17: ["", ""],
            18: ["", ""],
            19: ["", ""],
            20: ["", ""],
            21: ["", ""],
            22: ["", ""],
            23: ["", ""],
            24: ["", ""],
            25: ["", ""],
            26: ["", ""],
            27: ["", ""],
            28: ["", ""],
            29: ["", ""],
            30: ["", ""],
            31: ["", ""],
            32: ["", ""],
            33: ["", ""],
            34: ["", ""],
            35: ["", ""],
            36: ["", ""],
            37: ["", ""],
            38: ["", ""],
            39: ["", ""],
            40: ["", ""],
            41: ["", ""],
            42: ["", ""],
            43: ["", ""],
            44: ["", ""],
            45: ["", ""],
            46: ["", ""],
            47: ["", ""], 
            48: ["", ""],
            49: ["", ""], 
            50: ["", ""],
            51: ["", ""], 
            52: ["", ""],
            53: ["", ""], 
            54: ["", ""],
            55: ["", ""],      
            56: ["", ""],        
            57: ["", ""],      
            58: ["", ""],        
            59: ["", ""],      
            60: ["", ""],        
            61: ["", ""],      
            62: ["", ""],        
            63: ["", ""],      
            64: ["", ""],        
            65: ["", ""],      
            66: ["", ""],        
            67: ["", ""],      
            68: ["", ""],        
            69: ["", ""],      
            70: ["", ""],        
            71: ["", ""],      
            72: ["", ""],        
            73: ["", ""],      
            74: ["", ""],        
            75: ["", ""],      
            76: ["", ""],        
            77: ["", ""],      
            78: ["", ""],        
            79: ["", ""],      
            80: ["", ""],        
            81: ["", ""],      
            82: ["", ""],        
            83: ["", ""],      
            84: ["", ""],        
            85: ["", ""],      
            86: ["", ""],        
            87: ["", ""],      
            88: ["", ""],        
            89: ["", ""],      
            90: ["", ""],        
            91: ["", ""],      
            92: ["", ""],        
            93: ["", ""],      
            94: ["", ""],        
            95: ["", ""],      
            96: ["", ""],        
            97: ["", ""],      
            98: ["", ""],        
            99: ["", ""],      
            100: ["", ""],    
            "počet": 1
        },
        11:{
            0: ["heißen", "jmenovat se"],
            1: ["wohnen", "bydlet"],
            2: ["gehen", "jít"],        
            3: ["hören", "poslouchat"],  
            4: ["im internet surfen", "surfovat na internetu"],  
            5: ["kommen (aus)", "pocházet (z)"],      
            6: ["lernen", "učit se"],    
            7: ["liegen", "ležet"],
            8: ["reisen", "cestovat"], 
            9: ["schreiben", "psát"],  
            10: ["spielen", "hrát"],  
            11: ["tanzen", "tancovat"],
            12: ["haben", "mít"],
            13: ["machen", "dělat"], 
            14: ["Sport treiben", "sportovat"], 
            15: ["arbeiten", "pracovat"],
            16: ["brauchen", "potřebovat"],
            17: ["fahren", "jet, jezdit"],
            18: ["lesen", "číst"],
            19: ["sprechen", "mluvit"],
            20: ["besuchen", "navštěvovat, navštívit"],
            21: ["gewinnen", "vyhrát, vyhrávat"],
            22: ["leben", "žít"],
            23: ["finden", "shlédavat, myslet si"],     
            24: ["studieren", "studovat"], 
            25: ["beginnen", "začít, začínat"],
            26: ["gehen", "jít"],
            27: ["jobben", "mít brigádu"],
            28: ["an|fangen", "začí(na)t"],
            29: ["an|machen", "zapnout, pustit"],
            30: ["an|rufen", "(za)volat"],
            31: ["sich an|ziehen", "obléknout se"],
            32: ["auf|räumen", "uklízet"],
            33: ["auf|stehen", "vstá(va)t"],
            34: ["auf|wachen", "probudit se"],
            35: ["aus|leeren", "vysypat, vyprázdnit"],
            36: ["aus|räumen", "vyklidit"],
            37: ["aus|sehen", "vypadat"],
            38: ["drehen", "natáčet"],
            39: ["duschen", "sprchovat se"],
            40: ["ein|kaufen", "nakupovat"],
            41: ["ein|schlafen", "usnout"],
            42: ["fern|sehen", "dívat se na televizi"],
            43: ["klingeln", "zvonit"],
            44: ["mit|nehmen", "vzít s sebou"],
            45: ["putzen", "(vy)čistit"],
            46: ["saugen", "vysávat"],
            47: ["schlafen", "spát"],
            48: ["(sich) schminken", "líčit se"],
            49: ["vloggen", "natáčet vlog (videoblog)"],
            50: ["(sich) vor|bereiten", "připravovat (se)"],
            51: ["zeigen", "ukázat"], 
            52: ["zu|bereiten", "připravit (jídlo)"],
            53: ["züruck|kommen", "vrátit se"], 
            54: ["aus|schalten", "vypnout"],
            55: ["ein|schalten", "zapnout"],       
            56: ["entdecken", "objevit, najít"],         
            57: ["(sich) entschuldigen", "omluvit (se)"],       
            58: ["erzählen", "vyprávět"],      
            59: ["kommentieren", "komentovat"],    
            60: ["liken", "likovat"],   
            61: ["posten", "postovat (příspěvky)"],         
            62: ["verbringen", "strávit"],          
            63: ["vergessen", "zapomenout"],   
            64: ["wissen", "vědět"],       
            65: ["ab|holen", "vyzvednout"], 
            66: ["sich treffen", "setkat se"],    
            67: ["besichtigen", "prohlédnout si"],   
            68: ["gefallen", "líbit se"],     
            69: ["gehören", "patřit"],   
            70: ["helfen", "pomoci, pomáhat (někomu)"], 
            71: ["klicken", "kliknout"],         
            72: ["lachen", "smát se"],     
            73: ["laufen", "běhat, běžet"],   
            74: ["lieben", "milovat, mít rád"],       
            75: ["schenken", "darovat"],       
            76: ["schicken", "poslat"],      
            77: ["geben", "dávat, dát"],      
            78: ["(sich) aus|denken", "vymyslet"],       
            79: ["bummeln", "procházet se"],    
            80: ["entfernt (sein)", "(být) vzdálený"],       
            81: ["sich freuen", "těšit se (na co)"],    
            82: ["hoffen", "doufat, věřit"],      
            83: ["mit|bringen", "přinést s sebou"],      
            84: ["übernachten", "přenocovat"], 
            85: ["finden", "najít"],  
            86: ["finden", "najít"],  
            87: ["bekommen", "dostat"],      
            88: ["probieren", "ochutnat; vyzkoušet"],         
            89: ["joggen", "joggovat, běhat"],     
            90: ["vor|schlagen", "navrhnout, doporučit"],        
            91: ["werden", "stát se"],       
            92: ["feiern", "slavit, oslavovat"],       
            93: ["gehören", "patřit"],     
            94: ["wandern", "putovat, cestovat"],       
            95: ["haben", "mít"],     
            96: ["sehen", "vidět"], 
            97: ["verstehen sich", "rozumět si"], 
            98: ["dauern", "trvat"],     
            99: ["ein|laden", "pozvat"],
            100: ["fragen", "ptát se, zeptat se"],
            101: ["grillen", "grilovat"],
            102: ["singen", "zpívat"],
            103: ["stimmen", "souhlasit"],
            104: ["es gibt", "je, existuje"],
            105: ["schwimmen", "plavat"],
            106: ["shoppen", "nakupovat"], 
            107: ["stehen", "stát"],
            108: ["bestellen", "objednat"],
            109: ["denken", "myslet"],
            110: ["suchen", "hledat"],
            111: ["können", "umět, moci"],
            112: ["wollen", "chtít"],
            113: ["dürfen", "smět, moci"],
            114: ["sollen", "mít (něco udělat)"],
            115: ["bleiben", "zůstat"],  
            116: ["essen", "jíst"],
            117: ["schmecken", "chutnat"],
            118: ["trinken", "pít"],
            119: ["mögen", "mít rád"],
            120: ["bezahlen", "(za)platit"],
            121: ["möcht", "chtít"],
            122: ["nehmen", "vzít, brát"],
            123: ["kaufen", "koupit, kupovat"],
            124: ["reservieren", "rezervovat"],
            125: ["braten", "péci, smažit"],
            126: ["erhitzen", "zahřát, ohřát"],
            127: ["kochen", "vařit"],
            128: ["mischen", "(s)míchat"],
            129: ["schneiden", "(na)krájet"],
            130: ["trocknen", "(o)sušit, (u)sušit"],
            131: ["waschen", "(o)mýt, (u)mýt"],
            132: ["würzen", "(o)kořenit"],
            133: ["zupfen", "(na)trhat"],
            134: ["verkaufen", "prod(áv)at"],  
            135: ["", ""], 
            136: ["", ""], 
            "počet": 135
        }

    }
}
