const lekce ={
    "lekce":[
        [
            ["Lekce 1"],
            [           
                ["der Abend", "večer"],
                ["du", "ty"],
                ["gut", "dobrý"],
                ["Guten Abend!", "Dobrý večer!"],
                ["(Es) Freut mich.", "Těší mě."],
                ["Hallo!", "Ahoj!"],
                ["heißen", "jmenovat se"],
                ["Hi!", "Ahoj!"],
                ["ich", "já"],
                ["ihr", "vy"],
                ["ja", "ano"],
                ["der Morgen", "ráno"],
                ["Guten Morgen!", "Dobré ráno!"],
                ["der Tag /-e", "den"],
                ["Guten Tag!", "Dobrý den!"],
                ["und", "a"],
                ["wer", "kdo"],
                ["Wer bist du?", "Kdo jsi?"],
                ["wie", "jak"],
                ["Wie heißt du?", "Jak se jmenuješ?"],
                ["wir", "my"],
                ["in", "v"],
                ["das Spiel /-e", "hra"],
                ["wo", "kde"],
                ["Wo wohnst du?", "Kde bydlíš?"],
                ["wohnen", "bydlet"],
                ["null", "0"],
                ["eins", "1"],
                ["zwei", "2"],
                ["drei", "3"],
                ["vier", "4"],
                ["fünf", "5"],
                ["sechs", "6"],
                ["sieben", "7"],
                ["acht", "8"],
                ["neun", "9"],
                ["zehn", "10"],
                ["elf", "11"],
                ["zwölf", "12"],
                ["dreizehn", "13"],
                ["vierzehn", "14"],
                ["fünfzehn", "15"],
                ["sechzehn", "16"],
                ["siebzehn", "17"],
                ["achtzehn", "18"],
                ["neunzehn", "19"],
                ["zwanzig", "20"],
                ["alt", "starý"], 
                ["er", "on"],
                ["der Monat /-e", "měsíc"], 
                ["sie", "ona"],
                ["sie", "oni"], 
                ["aber", "ale"],
                ["das Alter", "věk"], 
                ["auch", "také"],
                ["aus", "z"],      
                ["die Band /-s", "(hudební) skupina"],        
                ["chatten", "chatovat"],      
                ["das Computerspiel /-e", "počítačová hra"],        
                ["das E-Mail /-s", "e-mail"],      
                ["das Englisch", "angličtina"],        
                ["der Fan /-s", "fanoušek"],      
                ["das Französisch", "francouzština"],        
                ["der Freund /-e", "kamarád"],      
                ["die Freundin /-nen", "kamarádka"],        
                ["der Fußball", "fotbal"],      
                ["gehen", "jít"],        
                ["gern", "rád(a)"],      
                ["die Gitarre /-n", "kytara"],        
                ["das Handy /-s", "mobil"],      
                ["das Hobby /-s", "koníček"],        
                ["hören", "poslouchat"],      
                ["im internet surfen", "surfovat na internetu"],        
                ["immer", "pořád, neustále"],      
                ["das Jahr /-e", "rok"],        
                ["kein/keine/kein", "žádný/žádná/žádné"],      
                ["das Klavier /-e", "klavír"],        
                ["kommen (aus)", "pocházet (z)"],      
                ["das Konzert /-e", "koncert"],        
                ["lernen", "učit se"],      
                ["liegen", "ležet"],        
                ["der Nachname /-n", "příjmení"],      
                ["nicht weit von", "nedaleko (koho, čeho)"],        
                ["reisen", "cestovat"],      
                ["schreiben", "psát"],        
                ["die Schule /-n", "škola"],      
                ["spielen", "hrát"],        
                ["tanzen", "tancovat"],      
                ["der Vorname /-n", "křestní jméno"],        
                ["der Wohnort /-e", "bydliště"],      
                ["falsch", "nesprávně, chybně"],        
                ["die Flöte /-n", "flétna"],      
                ["haben", "mít"],        
                ["das Instrument /-e", "(hudební) nástroj"],      
                ["jetzt", "nyní"],        
                ["machen", "dělat"],      
                ["richtig", "správně"],        
                ["der Sport", "sport"],      
                ["Sport treiben", "sportovat"],        
                ["das Squash", "squash"],      
                ["das/der Yoga", "jóga"],      
                ["bald", "brzy"],          
                ["bis", "do"],          
                ["Bis bald!", "Tak zatím!"],          
                ["die Frau /-en", "paní"],          
                ["der Herr /-en", "pan"],          
                ["das Museum /Museen", "muzeum"],          
                ["schön", "hezký"],           
                ["Servus!", "Ahoj!"],          
                ["Tschüs!", "Ahoj! (při loučení)"],          
                ["das Wiedersehen", "shledání"]
            ]
        ],
        [
            ["Lekce 11"],
            [
                ["die Ạbfahrt, -en", "odjezd; sjezd (na lyžích)"],
                ["die Ạbreise, -n", "odjezd"],
                ["die Ạltersgruppe, -n", "věková skupina"],
                ["ạn|kommen (i. angekommen)", "přijet, dorazit"],
                ["ạnderthạlb", "jeden a půl"],
                ["anderthalb Stunden", "hodinu a půl"],
                ["der/die Ạngestellte, -n", "zaměstnanec, zaměstnankyně"],
                ["die Ạnkunft, Ankünfte", "příjezd, přílet"],
                ["die Ạnreise, -n", "příjezd; cesta/jízda (tam)"],
                ["die Ạnschrift, -en", "adresa"],
                ["die Atmosphäre, -n", "atmosféra"],
                ["auf jeden Fall", "v každém případě, na každý pád"],
                ["Auf Wiederhören!", "Na slyšenou!"],
                ["der Aufenthalt, -e", "pobyt"],
                ["aus|drucken (h. ausgedruckt)", "vytisknout"],
                ["aus|fallen (i. ausgefallen)", "vypadnout"],
                ["aus|füllen (h. ausgefüllt)", "vyplnit"],
                ["aus|halten (h. ausgehalten)", "vydržet"],
                ["aus|steigen (i. ausgestiegen)", "vystoupit"],
                ["die Bahn, -en", "vlak; železnice, dráha"],
                ["bar", "v hotovosti, hotově"],
                ["das Bargeld (j. č.)", "hotovost, hotové peníze"],
                ["die Bạstelwerkstatt, Bastelwerkstätten", "kutilská dílna"],
                ["begrẹnzt", "omezený, ohraničený"],
                ["besẹtzen (h. besetzt)", "obsadit"],
                ["bịllig", "levný"],
                ["bịtten (h. gebeten) ", "prosit (o)"],
                ["das Boot, -e", "člun"],
                ["das Budget, -s", "rozpočet"],
                ["buchen (h. gebucht)", "rezervovat"],
                ["das reicht", "to stačí"],
                ["die Daten", "data, údaje, informace"],
                ["das Dọppelzimmer, -", "dvoulůžkový pokoj"],
                ["ein Angestellter/eine Angestellte", "zaměstnanec/ zaměstnankyně"],
                ["ein Erwachsener/eine Erwachsene", "dospělý/dospělá"],
                ["der Eingang, Eingänge", "vchod, vstup, vjezd"],
                ["der Eintritt, -e", "vstup, vstupné"],
                ["die Einzelkarte, -n", "jednotlivá jízdenka/vstupenka"],
                ["das Einzelzimmer, -", "jednolůžkový pokoj"],
                ["die Entfẹrnung, -en", "vzdálenost"],
                ["die Erfahrung, -en", "zkušenost"],
                ["erlaubt", "povolený"],
                ["erreichen (h. erreicht)", "dostat se, dorazit (kam); dosáhnout"],
                ["der/die Erwạchsene, -n", "dospělý, dospělá"],
                ["die Fahrkarte, -n", "jízdenka"],
                ["die Fahrt, -en", "cesta, jízda"],
                ["der Fạll, Fälle", "pád, případ"],
                ["die Ferienwohnung, -en", "rekreační byt, prázdninový byt"], 
                ["das Fẹstival, -s", "festival"],
                ["gefährlich", "nebezpečný, riskantní"], 
                ["genügend", "dostatečný, postačující"],
                ["das Geschịrr, -e", "nádobí"], 
                ["gụ̈ltig", "platný"],
                ["gụ̈nstig", "výhodný, příznivý"], 
                ["der Hafen, Häfen", "přístav"],
                ["der Hbf = Hauptbahnhof, Hauptbahnhöfe", "hlavní (vlakové) nádraží"],      
                ["das Họstel, -s", "hostel"],        
                ["der/das Check-out, -s", "check-out"],      
                ["ịnbegriffen", "zahrnutý, včetně"],        
                ["jemand", "někdo, kdosi"],      
                ["kẹnnen|lernen (h. kennengelernt)", "poznat, seznámit se"],        
                ["klịngen (h. geklungen)", "znít"],      
                ["kọstenlos", "bezplatný, zdarma"],        
                ["die Kreditkarte, -n", "kreditní karta"],      
                ["die Kụrzstrecke, -n", "krátký úsek cesty"],        
                ["lạngsam", "pomalý"],      
                ["der Mietwagen, -", "pronajaté vozidlo"],        
                ["die Mịtfahrgelegenheit, -en", "spolujízda"],      
                ["das Motel, -s", "motel"],        
                ["das Motorrad, Motorräder", "motorka, motocykl"],      
                ["der Nahbereich, -e", "blízké okolí"],        
                ["der Nahverkehr (j. č.)", "místní doprava"],      
                ["ọ̈ffentlich", "veřejný"],        
                ["die Oper, -n", "opera"],      
                ["der Pạrkplatz, Parkplätze", "parkoviště; parkovací místo"],        
                ["pạssen (h. gepasst)", "hodit se, padnout; padnout, sedět (oblečení)"],      
                ["passieren (i. passiert)", "přihodit se, stát se"],        
                ["das Pạsswort, Passwörter", "heslo"],      
                ["die Pension, -en", "penzion"],        
                ["der Personalausweis, -e", "občanský průkaz, průkaz totožnosti"],      
                ["die PLZ = Pọstleitzahl, -en", "PSČ"],        
                ["das Privatzimmer, -", "soukromá místnost"],      
                ["reichen (h. gereicht)", "stačit"],        
                ["die Rezeption, -en", "recepce"],      
                ["der Rezeptionịst, -en", "recepční"],        
                ["die Rụ̈ckfahrkarte, -n", "zpáteční jízdenka"],      
                ["die Rụndfahrt, -en", "okružní jízda"],        
                ["die S-Bahn, -en", "rychlodráha, městská dráha"],      
                ["der Senior, -en", "senior"],        
                ["der Schlụ̈ssel, -", "klíč"],      
                ["schnẹll", "rychlý"],        
                ["schreien (h. geschrien)", "křičet, řvát"],      
                ["der Schülerausweis, -e", "žákovský/studentský průkaz"],        
                ["spạnnend", "napínavý"],      
                ["spülen (h. gespült)", "mýt, opláchnout"],        
                ["das Stạdtfest, -e", "městská slavnost"],      
                ["stạtt|finden (h. stattgefunden)", "konat se"],        
                ["der Stẹrn, -e", "hvězda"],      
                ["stornieren (h. storniert)", "stornovat, zrušit"],        
                ["die Suche, -n", "hledání, pátrání"],      
                ["die Tageskarte, -n", "celodenní jízdenka/vstupenka"],          
                ["der Teenie, -s", "teenager"],          
                ["teil|nehmen (h. teilgenommen)", "účastnit se (čeho)"],          
                ["teuer", "drahý"],          
                ["trẹffen (sich) (h. getroffen)", "potkat (koho), setkat se (s kým)"],          
                ["tun (h. getan)", "dělat, činit"],          
                ["der Tunnẹl, -", "tunel"],          
                ["ụm|steigen (i. umgestiegen)", "přestoupit"],          
                ["ụm|ziehen (i. umgezogen)", "přestěhovat se"],          
                ["ụmweltfreundlich", "ekologický, šetrný k životnímu prostředí"],          
                ["die Ụnterkunft, Unterkünfte", "ubytování"],          
                ["unternehmen (h. unternommen)", "podniknout"],          
                ["die Ụnterschrift, -en", "podpis"],          
                ["die Ụnterwelt, -en", "podzemí"],          
                ["die Verạnstaltung, -en", "akce, událost"],          
                ["verdienen (h. verdient)", "vyděl(áv)at"],          
                ["die Vorkasse, -n", "platba předem"],          
                ["wahrscheinlich", "pravděpodobně"],          
                ["wạch", "bdělý, vzhůru"],          
                ["werden (i. geworden)", "stá(va)t se"],          
                ["die Wẹrkstatt, Werkstätten", "dílna"],          
                ["der Wẹttbewerb, -e", "der Wẹttbewerb, -e"],          
                ["wiederholen (h. wiederholt)", "opakovat"],          
                ["wịld", "divoký"],          
                ["willkọmmen", "vítaný"],          
                ["der Workshop, -s", "workshop"],          
                ["zahlbar", "splatný, k zaplacení"],          
                ["die Zahlung, -en", "platba"],          
                ["ZOB = Zentraler Omnibusbahnhof", "centrální autobusové nádraží"],    
            ]
        ],
        [
            ["Lekce 12"],
            [
                ["anders", "jinak"],
                ["der Ạnschlag, Anschläge", "útok, atentát"],
                ["die Ausfahrt, -en", "exit, sjezd (z dálnice)"],
                ["die Autobahn, -en", "dálnice"],
                ["beliebt", "oblíbený, populární"],
                ["berẹchnen (h. berechnet)", "spočítat"],
                ["bestehen (h. bestanden)", "být (z čeho), skládat se, sestávat; složit (zkoušku)"],
                ["der Betonblock, Betonblöcke/-s", "betonový blok"],
                ["das Dẹnkmal, Denkmäler", "památník, pomník"],
                ["das Dịng, -e", "věc"],
                ["das Dreieck, -e", "trojúhelník, zde: křižovatka dálnic"],
                ["durchfließen (h. durchflossen)", "protékat (čím)"],
                ["der Einwohner, -", "obyvatel"],
                ["erfụ̈llen (h. erfüllt)", "splnit"],
                ["das Ergebnis, -se", "výsledek"],
                ["die Erịnnerung, -en", "památka, upomínka"],
                ["der Fẹrnsehturm, Fernsehtürme", "televizní věž"],
                ["fließen (i. geflossen)", "téci"],
                ["das Gebịrge, -", "pohoří, hory"],
                ["das Graffiti, -s", "graffiti"],
                ["grausam", "krutý, hrozný"],
                ["die Hạ̈lfte, -n", "polovina, půlka"],
                ["hạndeln (h. gehandelt)", "jednat, počínat si"],
                ["hẹrrlich", "nádherný, překrásný"],
                ["hoch", "vysoký"],
                ["hoch|fahren (i. hochgefahren) hovor.", "(vy)jet nahoru"],
                ["in der Wirklichkeit", "ve skutečnosti"],
                ["die Insel, -n", "ostrov"],
                ["kọsten (h. gekostet)", "stát (o ceně)"],
                ["der Kreisverkehr, -e", "kruhový objezd"],
                ["das Kreuz (j. č.) (zkr. z Autobahnkreuz, -e)", "kříž; křižovatka dálnic"],
                ["die Kụppel, -n", "kopule"],
                ["lạng", "dlouhý"],
                ["lebẹndig", "živý, čilý"],
                ["der Lkw (= Lạstkraftwagen)", "nákladní auto"],
                ["lösen (h. gelöst)", "(vy)řešit; uvolnit"],
                ["das Mahnmal, -e", "památník, pomník"],
                ["die Mạrke, -n", "značka; známka"],
                ["die Mauer, -n", "zeď"],
                ["das Meer, -e", "moře"],
                ["mụ̈nden (i./h. gemündet)", "ústit, vlévat se"],
                ["die Nọrdsee (j. č.)", "Severní moře"],
                ["die Ọstsee (j. č.)", "Baltské moře"],
                ["die Rạststätte, -n", "dálniční odpočívadlo, motorest"],
                ["die Reise, -n", "cesta, cestování"],
                ["der Rẹst, -e", "zbytek"],
                ["die Rẹttungsgasse, -n", "záchranná ulička"],
                ["der Rẹttungswagen, -", "záchranka, záchranné vozidlo"], 
                ["die Rịchtung, -en", "směr"],
                ["die Rụndwanderung, -en", "okružní túra"], 
                ["sạmmeln (h. gesammelt)", "sbírat"],
                ["die See (j. č.)", "moře"], 
                ["die Seilbahn, -en", "lanová dráha, lanovka"],
                ["sẹlbst", "sám, sama, osobně"], 
                ["schwer", "těžký"],
                ["sich ạn|ziehen (h. angezogen)", "obléknout seạnders"],      
                ["sich ạ̈rgern (h. geärgert)", "(roz)zlobit se"],        
                ["sich aus|kennen (h. ausgekannt)", "vyznat se, vědět si rady"],      
                ["sich beeilen (h. beeilt)", "pospíšit se"],        
                ["sich bewegen (h. bewegt)", "hýbat se"],      
                ["sich entspạnnen (h. entspannt)", "uvolnit se"],        
                ["sich erholen (h. erholt)", "odpočinout si"],      
                ["sich erkạ̈lten (h. erkältet)", "nachladit se, nastydnout"],        
                ["sich freuen (h. gefreut) ", "těšit se, mít radost"],      
                ["sich konzentrieren (h. konzentriert)", "soustředit se, koncentrovat se"],        
                ["sich verlaufen (h. verlaufen)", "zabloudit, ztratit se"],      
                ["sich vor|bereiten (h. vorbereitet)", "připravit se (na)"],        
                ["sich vor|stellen (h. vorgestellt)", "představit si"],      
                ["sich wụndern (h. gewundert)", "divit se"],        
                ["spẹrren (h. gesperrt)", "(u)zavřít"],      
                ["der Stau, -s", "dopravní zácpa"],        
                ["stọckend", "váznoucí"],      
                ["die Strẹcke, -n", "cesta, trať, úsek"],        
                ["die Teilung, -en", "rozdělení"],      
                ["der Tiergarten, Tiergärten", "zoologická zahrada"],        
                ["traurig", "smutný"],      
                ["die Tụnnelsperre, -n", "uzávěra tunelu"],        
                ["die Ụmleitung, -en", "objížďka"],      
                ["der Ụnfall, Unfälle", "nehoda, neštěstí"],        
                ["der Verkehr (j. č.)", "doprava, provoz"],      
                ["die Verkehrsmeldung, -en", "informace o dopravě"],        
                ["viereinhạlb", "čtyři a půl"],      
                ["wịchtig", "důležitý"],        
                ["die Wịrklichkeit, -en", "skutečnost"],      
                ["die Zahnradbahn, -en", "ozubnicová dráha, zubačka"]    
            ]
        ],
        [
            ["Lekce 13"],
            [
                ["4 °C (vier Grad Celsius)","4 stupně"],
                ["die Accessoires","doplňky"],
                ["aktuẹll","aktuální"],
                ["allerdịngs","ovšem, avšak"],
                ["der Ạlltag (j. č.)","všední den"],
                ["ạltmodisch","staromódní, nemoderní"],
                ["ạn|probieren (h. anprobiert)","zkusit (si), vyzkoušet si (oblečení, boty)"],
                ["der Ạnzug, Anzüge","oblek"],
                ["die Ạrmbanduhr, -en","náramkové hodinky"],
                ["auf keinen Fall","v žádném případě"],
                ["auf|passen (h. aufgepasst) (auf + 4. p.)","dávat pozor, dohlížet (na koho, co)"],
                ["die Augenbraue, -n","obočí"],
                ["aus|leihen (h. ausgeliehen)","vypůjčit, půjčit"],
                ["der Ausschnitt, -e","výstřih"],
                ["der Ausverkauf, Ausverkäufe","výprodej"],
                ["die Badehose, -n","(pánské) plavky"],
                ["der Berịcht, -e","zpráva"],
                ["betonen (h. betont)","zdůraznit"],
                ["bewọ̈lkt","zatažený"],
                ["der BH (Büstenhalter)","podprsenka"],
                ["der Bikini, -s","bikiny"],
                ["der Blazer, -","sportovní sako, blejzr"],
                ["blịtzen (h. geblitzt)","blýskat se"],
                ["die Bluse, -n","halenka, blůza"],
                ["die Bọxershorts","boxerky"],
                ["das Detail, -s","detail"],
                ["dezẹnt","decentní"],
                ["dọnnern (h. gedonnert)","hřmět"],
                ["ein|packen (h. eingepackt)","(za)balit"],
                ["einverstanden","srozuměný"],
                ["elegạnt","elegantní"],
                ["die Empfehlung, -en","doporučení, rada"],
                ["ẹng","úzký"],
                ["erfahren (h. erfahren)","dozvědět se"],
                ["extravagạnt","extravagantní"],
                ["fein","jemný"],
                ["die Figur, -en","postava"],
                ["flạch","rovný; nízký"],
                ["der Flịpflop, -s","žabka (bota)"],
                ["der Flyer, -","leták"],
                ["frieren (h. gefroren)","mrznout"],
                ["das Gefühl, -e","smysl, cit"],
                ["gepụnktet","puntíkovaný"],
                ["geschehen (i. gechehen)","dít se, stát se"],
                ["gestreift","pruhovaný"],
                ["das Gewịtter, -","bouřka"],
                ["gewöhnlich","obyčejný, normální"],
                ["das Grad","stupeň (Celsia…)"],
                ["großartig","(hovor.) úžasný, super"],
                ["die Größe, -n","velikost"],
                ["der Gụmmistiefel, -","holínka, gumák"],
                ["der Gụ̈rtel, -","pásek"],
                ["der Hạlbschuh, -e","polobotka"],
                ["der Hạndschuh, -e","rukavice"],
                ["die Hạndtasche, -n","kabelka"],
                ["heiß","horký"],
                ["heiter","jasný, slunečný"],
                ["das Hẹmd, -en","košile"],
                ["die Höchsttemperatur, -en","nejvyšší teplota"],
                ["die Hose, -n","kalhoty"],
                ["das Höschen, -","kalhotky"],
                ["der Hut, Hüte","klobouk"],
                ["die Jạcke, -n","bunda"],
                ["die Jeans","džíny"],
                ["die Jọgginghose, -n","sportovní kalhoty, tepláky"],
                ["die Kạppe, -n","čapka, kšiltovka"],
                ["die Kẹtte, -nv","řetízek"],
                ["das Kleid, -er","šaty"],
                ["das Kleidungsstück, -e","kus oděvu, oděv (např. tričko)"],
                ["kombinieren (h. kombiniert)","kombinovat"],
                ["der Kragen, -/Krägen","límec"],
                ["die Krawạtte, -n","kravata"],
                ["kühl","chladný"],
                ["das Leben, -","život"],
                ["die Lederhose, -n","kožené kalhoty"],
                ["leger","ležérní"],
                ["die Lẹggins","legíny"],
                ["das Make-up, -s","make-up"],
                ["der Mạntel, Mäntel","kabát"],
                ["die Mạrkenkleidung (j. č.)","značkové oblečení"],
                ["die Modepolizei (j. č.)","módní policie"],
                ["die Mụ̈tze, -n","čepice"],
                ["neblig","mlhavý"],
                ["nẹnnen (h. genannt)","(po)jmenovat, naz(ý)vat"],
                ["der Ohrring, -e","náušnice"],
                ["das Outfit, -s","outfit"],
                ["pạssen (h. gepasst)","padnout, sedět (oblečení)"],
                ["das Piercing, -s","piercing"],
                ["der Pullover, -","svetr"],
                ["der Pụmps, -","lodička (bota)"],
                ["der Regenschirm, -e","deštník"],
                ["regnen (h. geregnet)","pršet"],
                ["der Rịng, -e","prsten"],
                ["der Rọck, Röcke","sukně"],
                ["der Rụcksack, Rucksäcke","batoh"],
                ["das/der Sạkko, -s","sako"],
                ["die Sandale, -n","sandál"],
                ["seriös","seriózní"],
                ["die Shorts","šortky"],
                ["der Schal, -s","šála"],
                ["der Schauer, -","přeháňka"],
                ["scheinen (h. geschienen)","svítit"],
                ["schịck","šik, elegantní"],
                ["der Schlafanzug, Schlafanzüge","pyžamo"],
                ["schneien (h. geschneit)","sněžit"],
                ["der Schnürschuh, -e","šněrovací bota"],
                ["die Skinny-Jeans","úzké džíny, skinny džíny"],
                ["die Sọcke, -n","ponožka"],
                ["sogar","dokonce (i)"],
                ["die Sohle, -n","podrážka"],
                ["die Sọnne (j. č.)","slunce"],
                ["die Sọnnenbrille, -n","sluneční brýle"],
                ["sọnnig","slunečný"],
                ["der Spọrtschuh, -e","sportovní bota"],
                ["das Sprịchwort, Sprichwörter","přísloví, pořekadlo"],
                ["stehen (h. gestanden)","zde: padnout, sedět (o oblečení)"],
                ["steigen (i. gestiegen)","stoupat"],
                ["der Stiefel, -","kozačka, vysoká bota"],
                ["der Stil, -e","styl"],
                ["stilgerecht","stylový"],
                ["der Strịckpullover, -","pletený svetr"],
                ["die Strụmpfhose, -n","punčocháče"],
                ["stụ̈rmisch","bouřlivý, rozbouřený"],
                ["stylen (h. gestylt)","upravit, zkrášlit"],
                ["das Sweatshirt, -s","mikina"],
                ["teilweise bedẹckt","částečně zataženo"],
                ["die Temperatur, -en","teplota"],
                ["das Tọp, -s","top"],
                ["der Trẹkkingschuh, -e","treková bota"],
                ["das Tuch, Tücher","šátek"],
                ["die Tunika, Tuniken","tunika"],
                ["der Typ, -en","typ"],
                ["die Ụmkleidekabine, -n","převlékací kabina"],
                ["die Wahl, -en","volba, výběr"],
                ["die Wạrnung, -en","výstraha, varování"],
                ["wẹchselhaft","proměnlivý"],
                ["weit","široký"],
                ["das Wẹtter (j. č.)","počasí"],
                ["die Wẹtter-App, -s","aplikace na počasí"],
                ["die Wẹttervorhersage, -n","předpověď počasí"],
                ["wịndig","větrný"],
                ["wọlkig","oblačný, zamračený"],
                ["zerrịssen","roztrhaný"],
                ["zusạmmen|passen (h. zusammengepasst)","hodit se k sobě"],
                ["der Niederschlag","srážka"],
                ["der Regen","déšť"],
                ["der Blitz","blesk"],
                ["der Schnee","sníh"],
                ["die Sonne","slunce"],
                ["der Frost","mráz"],
                ["der Donner","hrom"],
                ["die Wolke","mrak"],
                ["der Nebel","mlha"],
                ["der Wind","vítr"],
                ["der Hagel","kroupy"],
                ["der Schneeschauer","sněhová přeháňka"]
            ]
        ],
        [
            ["Lekce 14"],
            [
                ["ạbhängig sein (von + 3. p.)","být závislý (na)"],
                ["der Alkohol (j. č.)","alkohol"],
                ["die Allergie, -n","alergie"],
                ["ạn|führen (h. angeführt)","uvést, vyjmenovat"],
                ["die Angina, Anginen","angína"],
                ["ạnstrengend","namáhavý"],
                ["der Ạrm, -e","paže, ruka"],
                ["der Arzt, Ärzte","lékař"],
                ["atmen (h. geatmet)","dýchat"],
                ["auf|hören (h. aufgehört) (mit + 3. p.)","skončit (s čím)"],
                ["das Auge, -n","oko"],
                ["außerdem","mimo to, kromě toho"],
                ["der Bart, Bärte","vousy"],
                ["der Bauch, Bäuche","břicho"],
                ["die Behạndlung, -en","léčba, ošetření"],
                ["das Bein, -e","noha"],
                ["die Beschwerde, -n","potíže, bolesti"],
                ["die Bịndehautentzündung, -en","zánět spojivek"],
                ["blọnd","blond"],
                ["bluten (h. geblutet)","krvácet"],
                ["brẹnnen (h. gebrannt)","pálit"],
                ["die Brụst (j. č.)/ Brüste","hrudník/prsa"],
                ["dafür","pro (to)"],
                ["dagegen","proti (tomu)"],
                ["dẹnn","neboť, protože, poněvadž"],
                ["dẹshạlb","proto, tedy, tudíž"],
                ["die Diät, -en","dieta"],
                ["dịcht","hustý"],
                ["die Droge, -n","droga"],
                ["dụ̈nn","hubený, vyzáblý"],
                ["der Dụrchfall, Durchfälle","průjem"],
                ["dụrchschnittlich","průměrný, průměrně"],
                ["der Ẹllbogen, -","loket"],
                ["erkạ̈ltet","nachlazený"],
                ["faulenzen (h. gefaulenzt)","lenošit"],
                ["das Faultier, -e","(hovor.) lenoch, povaleč"],
                ["fehlen (h. gefehlt)","chybět"],
                ["das Fẹtt, -e","tuk"],
                ["fẹttarm","nízkotučný"],
                ["das Fieber (j. č.)","horečka"],
                ["der Fịnger, -","prst"],
                ["fọlgend","následující"],
                ["der Freak, -s","nadšenec, fanoušek"],
                ["froh","rád"],
                ["gamen (h. gegamt)","hrát na počítači"],
                ["der Gamer, -","počítačový hráč"],
                ["die Gạ̈nsehaut (j. č.)","husí kůže"],
                ["das Gehịrn, -e","mozek"],
                ["genug","dost, dostatečně"],
                ["das Gesäß, -e","hýždě, zadek"],
                ["das Gesịcht, -er","obličej"],
                ["die Gesụndheit","(j. č.) zdraví"],
                ["der Gịps (j. č.)","sádra"],
                ["glạtt","hladký, rovný (vlasy)"],
                ["die Glạtze, -n","pleš"],
                ["der Glụ̈ckwunsch, Glückwünsche","gratulace, blahopřání"],
                ["die Grịppe, -n","chřipka"],
                ["Gute Besserung!","Brzké uzdravení!"],
                ["das Haar, -e","vlas, chlup"],
                ["der Hạls, Hälse","krk"],
                ["hạssen (h. gehasst)","nenávidět"],
                ["die Hụ̈lsenfrüchte","luštěniny"],
                ["der Husten (j. č.)","kašel"],
                ["der Hustensaft, Hustensäfte","sirup proti kašli"],
                ["die Ịmpfung, -en","očkování"],
                ["ịrgendwie","nějak"],
                ["der/die Jugendliche, -n","mladistvý, mladistvá"],
                ["kapụtt","zničený, vyčerpaný"],
                ["das Kịnn, -e","brada"],
                ["das Knie, -","koleno"],
                ["der Kọpf, Köpfe","hlava"],
                ["der Kọ̈rper, -","tělo"],
                ["krạnk","nemocný"],
                ["die Krạnkenkasse, -n","zdravotní pojišťovna"],
                ["die Krạnkheit, -en","nemoc, choroba"],
                ["die Leistung, -en","výkon"],
                ["die Lịppe, -n","ret"],
                ["lösen (h. gelöst)","uvolnit"],
                ["die Lụtschtablette, -n","cucací tableta"],
                ["die Magen-Dạrm-Grippe, -n","střevní chřipka"],
                ["die Meinung, -en","názor, mínění"],
                ["mẹnschlicher Kọ̈rper","lidské tělo"],
                ["der Mụnd, Münder","ústa"],
                ["die Nạrbe, -n","jizva"],
                ["die Nase, -n","nos"],
                ["der/das Nasenspray, -s","nosní sprej"],
                ["niesen (h. geniest)","kýchat"],
                ["der Notarzt, Notärzte","lékař pohotovostní služby"],
                ["der Oberkörper, -","horní část těla, trup"],
                ["das Ohr, -en","ucho"],
                ["oval","oválný"],
                ["der Patiẹnt, -en","pacient"],
                ["das Pflạster, -","náplast"],
                ["regelmäßig","pravidelně, pravidelný"],
                ["das Rọ̈ntgenbild, -er","rentgenový snímek"],
                ["rot","zrzavý (vlasy)"],
                ["der Rụ̈cken, -","záda"],
                ["rụnd","kulatý"],
                ["die Sạlbe, -n","mast"],
                ["schaden (h. geschadet) (+ 3. p.)","škodit, ubližovat (komu, čemu)"],
                ["schädigen (h. geschädigt) (+ 4. p.)","poškodit (koho, co)"],
                ["der Schmẹrz, -en","bolest"],
                ["der Schnụpfen, -","rýma"],
                ["die Schụlter, -n","rameno"],
                ["schwạch","slabý"],
                ["schwịndelig","špatně, mdlo"],
                ["schwịtzen (h. geschwitzt)","potit se"],
                ["(sich) brẹchen (h. gebrochen)","zlomit (si)"],
                ["sich erbrẹchen (h. erbrochen)","zvracet"],
                ["(sich) fühlen (h. gefühlt)","cítit (se)"],
                ["(sich) verbrẹnnen (h. verbrannt)","spálit (se), popálit (se)"],
                ["(sich) verlẹtzen (h. verletzt)","zranit (se)"],
                ["die Social Media","sociální média"],
                ["die Sọmmersprosse, -n","piha"],
                ["sọndern","nýbrž"],
                ["soziales Netzwerk / soziale Netzwerke","sociální síť / sociální sítě"],
                ["die Sprịtze, -n","injekce, injekční stříkačka"],
                ["die Stịmme, -n","hlas"],
                ["die Stịrn, -en","čelo"],
                ["der Stụrz, Stürze","pád"],
                ["die Sụcht, Süchte","závislost"],
                ["die Tablẹtte, -n","tableta"],
                ["Tabletten nehmen","brát tabletky"],
                ["teilen (h. geteilt)","sdílet"],
                ["das/der Thermometer, -","teploměr"],
                ["die Trọpfen","kapky"],
                ["trotzdem","přesto"],
                ["übel","zle, špatně"],
                ["der Ụmschlag, Umschläge","obklad, zábal"],
                ["untersuchen (h. untersucht)","prohlédnout vyšetřit (pacienta)"],
                ["der Verbạnd, Verbände","obvaz"],
                ["verbrauchen (h. verbraucht)","spotřebovat, vyčerpat"],
                ["verschreiben (h. verschrieben)","předepsat, naordinovat"],
                ["die Versịcherung, -en","pojištění"],
                ["verstauchen (h. verstaucht)","vymknout, vyvrtnout"],
                ["die Verstọpfung, -en","zácpa"],
                ["vorbei|kommen (i. vorbeigekommen)","hovor. zastavit se, krátce navštívit"],
                ["die Wạnge, -n","tvář, líce"],
                ["weh|tun (h. wehgetan)","j-m bolet"],
                ["die Wịmper, -n","řasa"],
                ["wohl","dobře"],
                ["der Zahn, Zähne","zub"],
                ["der Zeh, -en","prst (na noze)"],
                ["die Zigarẹtte, -n","cigareta"],
                ["die Zụnge, -n","jazyk"],
                ["zweieinhạlb","dva a půl"],
                ["die Zwischenmenschlichen Beziehungen","mezilidské vztahy"]
            ]
        ],
        [
            ["Lekce 15"],
            [
                ["die Abfahrt, -en", "sjezd (na lyžích)"],
                ["als", "když"],
                ["ändern (h. geändert)", "(z)měnit, upravit"],
                ["anerkannt", "uznaný"],
                ["der Anfänger, -", "začátečník"],
                ["das Angeln (j. č.)", "rybolov"],
                ["die Angst, Ängste", "strach"],
                ["der Artikel, -", "článek"],
                ["die Athletik (j. č.)", "atletika"],
                ["die Ausrüstung, -en", "výstroj, vybavení"],
                ["das Autorennen (j. č.)", "automobilové závody"],
                ["der Bach, Bäche", "potok"],
                ["der Ball, Bälle", "míč"],
                ["der Basketball (j. č.)", "basketbal"],
                ["die Belohnung, -en (für + 4. p.)", "odměna (za co)"],
                ["die Bewegung, -en", "pohyb"],
                ["der/das Biathlon (j. č.)", "biatlon"],
                ["Billard-, Federball", "kulečníková koule, badmintonový míček"],
                ["das Boxen (j. č.)", "box"],
                ["die Buchung, -en", "rezervace"],
                ["dar|stellen (h. dargestellt)", "představovat"],
                ["der Diabetes (j. č.)", "diabetes, cukrovka"],
                ["eher", "spíše"],
                ["ein Tor schießen", "dát gól, dát branku"],
                ["der Einzelsport (j. č.)", "individuální sport"],
                ["der Eiskunstlauf (j. č.)", "krasobruslení"],
                ["der Elfmeter, -", "pokutový kop, penalta"],
                ["das Ereignis, -se", "událost"],
                ["das Fechten (j. č.)", "šerm"],
                ["das Fitnessstudio, -s", "fitness studio"],
                ["fleißig", "pilný, pracovitý"],
                ["der Floorball (j. č.)", "florbal"],
                ["die Folge, -n (von + 3. p.)", "následek, důsledek (čeho)"],
                ["der Fortgeschrittene, -n", "pokročilý"],
                ["das Foul, -s", "faul"],
                ["foulen (h. gefoult)", "faulovat"],
                ["die Funktionswäsche, -n", "funkční prádlo"],
                ["genießen (h. genossen)", "užívat (si), vychutnávat (si)"],
                ["gesellig", "společenský, družný"],
                ["der Gleichstand, Gleichstände", "vyrovnaný stav (zápasu)"],
                ["das Golf (j. č.)", "golf"],
                ["der Grund, Gründe", "důvod"],
                ["die Gruppenermäßigung, -en", "skupinová sleva"],
                ["die Gymnastik, -en", "gymnastika"],
                ["die Halle, -n", "hala"],
                ["halten (h. gehalten) (von + 3. p.)", "myslet si, soudit (o kom, čem)"],
                ["der Handball (j. č.)", "házená"],
                ["der Handschuh, -e", "rukavice"],
                ["die Heimatstadt, Heimatstädte", "rodné město"],
                ["der Helm, -e", "helma, přilba"],
                ["das Herz, -en", "srdce"],
                ["die Hoffnung (j. č.)", "naděje"],
                ["kämpfen (h. gekämpft) (gegen + 4. p.)", "bojovat (proti komu)"],
                ["Knie-, Handgelenk-, Ellbogenschützer", "chrániče kolen, zápěstí, loktů"],
                ["der Knochen, -", "kost"],
                ["die Kondition (j. č.)", "kondice"],
                ["Kondition aufbauen/verbessern", "vybudovat/zlepšit kondici"],
                ["das Krafttraining, -s", "posilování"],
                ["der Krebs (j. č.)", "rakovina"],
                ["der Lebensstil, -e", "životní styl"],
                ["die Luft (j. č.)", "vzduch"],
                ["der Mannschaftssport (j. č.)", "týmový sport"],
                ["die Milliarde, -n", "miliarda"],
                ["mindestens", "nejméně, aspoň, přinejmenším"],
                ["der Muskel, -n", "sval"],
                ["die Nationalmannschaft, -en", "národní mužstvo, reprezentace"],
                ["der Neoprenanzug, Neoprenanzüge", "neopren"],
                ["die Nerven", "nervy"],
                ["das Netz, -e", "síť"],
                ["obwohl", "ačkoli, třebaže, přestože"],
                ["passiv", "pasivní"],
                ["die Piste, -n", "sjezdovka"],
                ["der Rabatt, -e", "sleva"],
                ["das Reiten (j. č.)", "jízda na koni"],
                ["das Remis, -", "remíza"],
                ["rennen (i. gerannt)", "běžet, běhat"],
                ["das Segeln (j. č.)", "jachting"],
                ["das Seil, -e", "lano"],
                ["das/der Set, -s", "set, sada, souprava"],
                ["der Schiedsrichter, -", "rozhodčí"],
                ["schießen (h. geschossen)", "střílet"],
                ["der Schläger, -", "raketa, hokejka, pálka"],
                ["der Schützer, -", "chránič"],
                ["sich befinden (h. sich befunden)", "nacházet se, být"],
                ["Ski-, Box-, Halbhandschuhe", "lyžařské rukavice, boxerské rukavice, rukavice s ustřiženými prsty"],
                ["das Skispringen (j. č.)", "skoky na lyžích"],
                ["der Skistock, Skistöcke", "lyžařská hůlka"],
                ["das Spielfeld, -er", "hřiště"],
                ["die Spielregel, -n", "pravidlo hry"],
                ["der Spielschluss, Spielschlüsse", "konec hry"],
                ["die Sportergebnisse", "sportovní výsledky"],
                ["der Sportplatz, Sportplätze", "sportovní hřiště"],
                ["die Sportsachen", "sportovní potřeby, pomůcky"],
                ["stark", "silný"],
                ["die Strafe, -n", "trest"],
                ["der Stürmer, -", "útočník"],
                ["die Taktik, -en", "taktika"],
                ["das Tauchen (j. č.)", "potápění"],
                ["Tennis-, Baseball-, Golf-, Hockeyschläger", "tenisová raketa, baseballová pálka, golfová hůl, hokejka"],
                ["die Thermowäsche (j. č.)", "termoprádlo"],
                ["das Tischtennis (j. č.)", "stolní tenis"],
                ["das Tor, -e", "branka, brána"],
                ["der Torwart, -e", "brankář"],
                ["trainieren (h. trainiert)", "trénovat"],
                ["das Trikot, -s", "trikot, dres"],
                ["das Turnier, -e", "turnaj, soutěž"],
                ["der Turnschuh, -e", "teniska"],
                ["überhaupt", "vůbec"],
                ["überspringen (h. übersprungen)", "přeskočit"],
                ["übertrieben", "přehnaný"],
                ["das Unentschieden, -", "remíza"],
                ["der Verein, -e", "spolek, klub"],
                ["der Verleih, -e", "půjčovna"],
                ["verlieren (h. verloren)", "prohrát"],
                ["veröffentlichen (h. veröffentlicht)", "zveřejnit, publikovat"],
                ["der Verteidiger, -", "obránce"],
                ["der Volleyball (j. č.)", "volejbal"],
                ["weinen (h. geweint)", "plakat"],
                ["wenn", "když"],
                ["der Wettkampf, Wettkämpfe", "závod, soutěž, zápas"],
                ["zaubern (h. gezaubert)", "kouzlit"],
                ["zugleich", "zároveň, současně"],
                ["der Zuschauer, -", "divák"],
                ["die Zuschauerin, -nen", "divačka"]

            ]
        ],
        [
            ["Lekce 16"],
            [
                ["das Akkordeon, -s", "akordeon"],
                ["auf|passen (h. aufgepasst) (auf + 4. p.)", "dávat pozor, dohlížet (na koho, co)"],
                ["die Aufnahme, -n", "záběr, snímek, nahrávka"],
                ["die Bassgitarre, -n", "basová kytara"],
                ["die Castingshow, -s", "castingová/talentová show"],
                ["damit", "aby"],
                ["deutlich", "jasný, zřetelný"],
                ["ein|stimmen (h. eingestimmt)", "(na)ladit"],
                ["die Einladung, -en", "pozvánka, pozvání"],
                ["einzigartig", "jedinečný"],
                ["das Erlebnis, -se", "zážitek"],
                ["Es geht ihnen darum, die Welt zu verändern.", "Jde jim o změnu světa."],
                ["der Familienstand (j. č.)", "rodinný stav"],
                ["die Fantasie, -n", "fantazie"],
                ["die Flamme, -n", "plamen"],
                ["fördern (h. gefördert)", "podporovat"],
                ["der Frühling, -e", "jaro"],
                ["das Gefängnis, -se", "vězení"],
                ["gehen (i. gegangen) (um + 4. p.)", "jít, jednat se (o)"],
                ["das Genre, -s", "žánr"],
                ["die Geschichte, -n", "příběh; povídka"],
                ["der Geschmack, Geschmäcke", "vkus"],
                ["die Handlung, -en", "děj"],
                ["hin|gehen (i. hingegangen)", "jít (tam)"],
                ["das Interesse, -n", "zájem"],
                ["der Irrtum, Irrtümer", "omyl, mýlka"],
                ["die Jägerin, -nen", "lovkyně"],
                ["das Keyboard, -s", "klávesy"],
                ["die Komödie, -n", "komedie"],
                ["der Krieg, -e", "válka"],
                ["der Krimi, -s", "detektivka, krimi"],
                ["die Kunst, Künste", "umění"],
                ["ledig", "svobodný"],
                ["das Lied, -er", "píseň"],
                ["die Literatur (j. č.)", "literatura"],
                ["der Maler, -", "malíř"],
                ["melden (h. gemeldet)", "ohlásit, oznámit"],
                ["die Messe, -n", "veletrh"],
                ["die Mundharmonika, -s/-en", "foukací harmonika"],
                ["das Musical, -s", "muzikál"],
                ["niemals", "nikdy"],
                ["die Orgel, -n", "varhany"],
                ["die Premiere, -n", "premiéra"],
                ["der Regisseur, -e", "režisér"],
                ["die Regisseurin, -nen", "režisérka"],
                ["retten (h. gerettet)", "zachránit"],
                ["die Rezension, -en", "recenze"],
                ["die Rolle, -n", "role"],
                ["der Roman, -e", "román"],
                ["das Saxofon, -e", "saxofon"],
                ["die Serie, -n", "seriál"],
                ["das Schlagzeug, -e", "bicí"],
                ["schlau", "mazaný, chytrý"],
                ["sich handeln (h. gehandelt) (um + 4. p.)", "jednat se, jít (o koho, co)"],
                ["die Trompete, -n", "trubka"],
                ["um … zu", "aby"],
                ["unterhaltsam", "zábavný"],
                ["unterstützen (h. unterstützt) (+ 4. p.)", "podporovat"],
                ["das Verbot, -e", "zákaz"],
                ["verfilmen (h. verfilmt)", "zfilmovat"],
                ["die Vernissage, -n", "vernisáž"],
                ["verraten (h. verraten)", "zradit"],
                ["verstecken (h. versteckt)", "schovat, ukrýt"],
                ["vor|haben (h. vorgehabt)", "zamýšlet, mít v úmyslu"],
                ["die Vorstellung, -en", "představení"],
                ["der Vorverkauf, Vorverkäufe", "předprodej"],
                ["wunderschön", "překrásný, nádherný"],
                ["der Zirkus, -se", "cirkus"],
                ["zurück|geben (h. zurückgegeben)", "vrátit"]
            ]
        ],
        [
            ["Lekce 17"],
            [
              ["ab und zu", "tu a tam"],
              ["die Ạbsicht, -en", "záměr, úmysl"],
              ["die Ạchtung (j. č.)", "pozor"],
              ["ạn|locken (h. angelockt)", "přilákat"],
              ["der Ạnrufbeantworter, -", "telefonní záznamník"],
              ["die Auszeichnung, -en", "pocta, uznání, vyznamenání"],
              ["bedeuten (h. bedeutet)", "znamenat"],
              ["die Bedịngung, -en", "podmínka"],
              ["die Bẹrgwacht, -en", "horská služba"],
              ["bestehen (h. bestanden)", "složit (zkoušku)"],
              ["der Bịldschirm, -e", "obrazovka, monitor"],
              ["die Bitte, -n (an + 4. p.)", "prosba, žádost"],
              ["blạ̈ttern (h. geblättert)", "listovat"],
              ["die Boulevardzeitung, -en", "bulvární noviny"],
              ["der Brief, -e", "dopis"],
              ["der Browser, -", "prohlížeč"],
              ["der Buchdruck, -e", "knihtisk"],
              ["die CD, -s", "CD"],
              ["das Cỵbermobbing (j. č.)", "kyberšikana"],
              ["der Delfin, -e", "delfín"],
              ["derjenige, diejenige, dạsjenige", "ten, ta, to; onen, ona, ono"],
              ["der Drụcker, -", "tiskárna"],
              ["dụrch|fallen (i. durchgefallen) hovor.", "propadnout, proletět (u zkoušky)"],
              ["der Dụrchschnitt, -e", "průměr"],
              ["die DVD, -s", "DVD"],
              ["ein|führen (h. eingeführt)", "zavést, zavádět"],
              ["die Eins, -en", "jednička (známka)"],
              ["entwịckeln (h. entwickelt)", "vyvíjet"],
              ["erfịnden (h. erfunden)", "vynalézt, objevit"],
              ["der Erfịnder, -", "vynálezce"],
              ["die Erfịndung, -en", "vynález"],
              ["erọ̈ffnen (h. eröffnet)", "otevřít, zahájit"],
              ["die Fake News", "fake news"],
              ["fọlgen (i. gefolgt)", "sledovat"],
              ["gedrụckt", "tištěný"],
              ["das Gerät, -e", "přístroj, nástroj"],
              ["der Gọldschmied, -e", "zlatník"],
              ["googeln (h. gegoogelt)", "(vy)googlovat"],
              ["die Grafik, -en", "grafika"],
              ["grụ̈nden (h. gegründet)", "založit, zřídit"],
              ["das Hạndwerk, -e", "řemeslo"],
              ["häufig", "častý"],
              ["her|stellen (h. hergestellt)", "vyrobit, vyrábět"],
              ["heraus|geben (h. herausgegeben)", "vydat, vydávat"],
              ["hinterlạssen (h. hinterlassen)", "zanechat (po sobě)"],
              ["hochwertig", "kvalitní, hodnotný"],
              ["das Họlz, Hölzer", "dřevo"],
              ["der Hubschrauber, -", "vrtulník, helikoptéra"],
              ["der Ịnfluencer, -", "influencer"],
              ["die Ịnfluencerin, -nen", "influencerka"],
              ["intim", "intimní, soukromý, důvěrný"],
              ["das Jahrtausend, -e", "tisíciletí"],
              ["die Kassẹtte, -n", "kazeta"],
              ["die Korrektur, -en", "korektura"],
              ["krạss", "extrémní, evidentní, křiklavý"],
              ["der Lịnk, -s", "link"],
              ["die Mạilbox, -en", "e-mailová schránka; poštovní schránka"],
              ["das Medium, Medien/Media", "médium"],
              ["die Mẹnsa, -s/Mensen", "jídelna, menza"],
              ["missbrauchen (h. missbraucht)", "zneužít"],
              ["mutig", "smělý, odvážný"],
              ["der Nachteil, -e", "nevýhoda"],
              ["neidisch", "závistivý"],
              ["die Note,- n", "známka"],
              ["das Pẹch (j. č.)", "smůla, pech"],
              ["Pech haben", "mít smůlu"],
              ["peinlich", "trapný"],
              ["die Produktion (j. č.)", "produkce, výroba"],
              ["der Profi, -s", "profík"],
              ["prüfen (h. geprüft)", "ověřit"],
              ["der Ratschlag, Ratschläge", "rada, doporučení"],
              ["der Redakteur, -e", "redaktor"],
              ["die Redakteurin, -nen", "redaktorka"],
              ["recherchieren (h. recherchiert)", "pátrat, hledat (informace)"],
              ["rein|legen (h. reingelegt) hovor.", "napálit"],
              ["die Rẹttung, -en", "záchrana; záchranná služba (Rakousko)"],
              ["die Ruhe (j. č.)", "klid"],
              ["sauber", "čistý"],
              ["die Schạllplatte, -n", "gramofonová deska"],
              ["schmụtzig", "špinavý"],
              ["schnịtzen (h. geschnitzt)", "vyřezat, vyřezávat"],
              ["schụ̈chtern", "plachý, ostýchavý, nesmělý"],
              ["(sich) kụ̈mmern (h. gekümmert) (um + 4. p.)", "starat se, pečovat (o)"],
              ["der Sieger, -", "vítěz"],
              ["sich erịnnern (h. erinnert)", "vzpomenout si, pamatovat si"],
              ["sich schämen (h. geschämt)", "stydět se, ostýchat sep"],
              ["das Smartphone, -s", "smartphone, chytrý telefon"],
              ["die Spur, -en", "stopa"],
              ["das Tạblet, -s", "tablet"],
              ["tatsächlich", "skutečně, opravdu"],
              ["das Telefon, -e", "telefon"],
              ["das Telegrạmm, -e", "telegram"],
              ["der Überblick, -e", "přehled"],
              ["überprüfen (h. überprüft)", "zkontrolovat, ověřit"],
              ["die Überrạschung, -en", "překvapení"],
              ["die Überschrift, -en", "nadpis"],
              ["übrigens", "mimochodem, ostatně"],
              ["das Ụnglück, -e", "neštěstí"],
              ["der Ụnsinn (j. č.)", "nesmysl, hloupost"],
              ["der Ụnterschied, -e", "rozdíl"],
              ["ursprünglich", "původní, prvotní"],
              ["verschwịnden (i. verschwunden)", "zmizet"],
              ["vor|kommen (i. vorgekommen)", "vyskytovat se, existovat"],
              ["vor|tragen (h. vorgetragen)", "přednést, prezentovat"],
              ["vorbei", "pryč, u konce"],
              ["der Vorteil, -e", "výhoda"],
              ["die Wẹrbung, -en", "reklama"],
              ["zu fünft", "v pěti, po pěti"],
              ["zusạmmen|stellen (h. zusammengestellt)", "sestavit, naplánovat"],
              ["die Zusạmmenfassung, -en", "shrnutí"]
            ]
        ],
        [
            ["Lekce 18"],
            [
              ["ạb|legen (h. abgelegt)", "složit, vykonat (zkoušku)"],
              ["ạb|schließen (h. abgeschlossen)", "uzavřít, dokončit"],
              ["der Ạbschluss, Abschlüsse", "závěrečná zkouška; konec, ukončení"],
              ["absolutes/eingeschränktes Halteverbot", "zákaz zastavení/stání"],
              ["ạn|halten (h. angehalten)", "zastavit"],
              ["ạn|nehmen (h. angenommen)", "přijmout"],
              ["die Anatomie (j. č.)", "anatomie"],
              ["aus|üben (h. ausgeübt)", "vykonávat"],
              ["die Ausbildung, -en", "vzdělání, vzdělávání"],
              ["der Ausgangspunkt, -e", "východisko, počátek, výchozí bod"],
              ["das Ausland (j. č.)", "zahraničí, cizina"],
              ["der Bạchelor (j. č.)", "bakalář (titul)"],
              ["beạchten (h. beachtet) (+ 4. p.)", "dbát (čeho), respektovat (co)"],
              ["die Beschreibung, -en", "popis"],
              ["besprẹchen (h. besprochen) (+ 4. p. mit + 3. p.)", "prodiskutovat,promluvit si (o čem s kým)"],
              ["die Besprẹchung, -en", "rozmluva, diskuze, rozhovor"],
              ["betrẹffen (h. betroffen) (+ 4. p.)", "týkat se (koho, čeho)"],
              ["die Bewẹrbung, -en", "žádost, ucházení se o (např. přijetí)"],
              ["bewerten (h. bewertet)", "(o)hodnotit, ocenit"],
              ["die Bewertung, -en", "hodnocení"],
              ["der/die Büroangestellte, -n", "úředník/úřednice"],
              ["der Dienst, -e", "služba"],
              ["duales System, duales Studium", "duální systém, duální studium (studium, při kterém žák/student zároveň pracuje)"],
              ["EDV-Kenntnisse", "znalost výpočetní techniky"],
              ["ein Büroangestellter/eine Büroangestellte, viele Büroangestellte", "úředník/úřednice, mnoho úředníků"],
              ["die Einbahnstraße, -n", "jednosměrná ulice, jednosměrka"],
              ["die Elẹktrotechnik (j. č.)", "elektrotechnika"],
              ["die Entscheidung, -en", "rozhodnutí"],
              ["erfọlgreich", "úspěšný"],
              ["erziehen (h. erzogen)", "vycho(vá)vat"],
              ["der Erzieher, -", "vychovatel"],
              ["die Fahrschule, -n", "autoškola"],
              ["die Fạchhochschule, -n", "vysoká škola, univerzita aplikovaných věd"],
              ["die Fạchhochschulreife (j. č.)", "doklad o kvalifikaci pro přijetí na vysokou školu"],
              ["die Fakultät, -en", "fakulta"],
              ["fließend", "plynně"],
              ["fließend in Wort und Schrift", "plynně slovem i písmem"],
              ["die Fọrschung, -en", "výzkum"],
              ["fọrt|setzen (h. fortgesetzt) (+ 4. p.)", "pokračovat (v čem)"],
              ["der Fragebogen, Fragebögen", "dotazník"],
              ["der Freiwilligendienst, -e", "dobrovolná služba"],
              ["der Friseur, -e", "kadeřník, holič"],
              ["der Führerschein, -e", "řidičský průkaz"],
              ["geboren", "narozený"],
              ["die Gebühr, -en", "poplatek"],
              ["die Gegenrichtung, -en", "protisměr"],
              ["die Gesạmtschule, -n", "integrovaná škola"],
              ["geschịckt", "šikovný"],
              ["gleichzeitig", "současný, souběžný"],
              ["das Hạlteverbot, -e", "zákaz zastavení"],
              ["das Hạndbuch, Handbücher", "příručka, manuál"],
              ["die Hạndelsakademie, -n", "obchodní akademie"],
              ["hạndwerklich", "řemeslný, řemeslnický"],
              ["die Hauptschule, -n", "obdoba našeho 2. stupně základní školy"],
              ["der Hausarzt, Hausärzte", "obvodní lékař"],
              ["der Haushalt, -e", "domácnost"],
              ["heraus|kommen (i. herausgekommen)", "zde: hovor. vyjít, vylézt"],
              ["die Höflichkeitsformel, -n", "zdvořilostní fráze"],
              ["der Hörsaal, Hörsäle", "posluchárna"],
              ["die Journalịstik (j. č.)", "žurnalistika"],
              ["die Journalịstin, -nen", "novinářka"],
              ["der Kaufmann, Kaufleute/Kaufmänner", "obchodník, kupec"],
              ["die Kẹnntnisse", "znalosti, vědomosti"],
              ["der Kfz-Mechaniker, - / Krạftfahrzeugmechaniker, -", "automechanik"],
              ["die Kịndheit (j. č.)", "dětství"],
              ["die Klausur, -en", "klauzura (písemná práce)"],
              ["der Kọch, Köche", "kuchař"],
              ["der Kommilitone, -n", "kolega, spolužák na VŠ"],
              ["die Korporation, -en", "korporace"],
              ["der Krạnkenpfleger, -", "ošetřovatel"],
              ["der Lackierer, -", "lakýrník"],
              ["die Lạndwirtschaft (j. č.)", "zemědělství"],
              ["die Lạ̈nge, -n", "délka"],
              ["der Lebenslauf, Lebensläufe", "životopis"],
              ["die Lehre, -n", "(vy)učení"],
              ["das Leistungsfach, Leistungsfächer", "předmět z nadstavbového kurzu (na gymnáziích)"],
              ["das Lyzeum, Lyzeen", "lyceum"],
              ["der Maschinenbau (j. č.)", "strojírenství"],
              ["die Massage-Therapie, -n", "masážní terapie"],
              ["der Master (j. č.)", "magistr (titul)"],
              ["mehrsprachig", "vícejazyčný"],
              ["mịt|teilen (h. mitgeteilt)", "sdělit, oznámit"],
              ["mụ̈ndlich", "ústní"],
              ["der Nụmerus clausus (NC) (j. č.)", "numerus clausus, omezený počet (maximální počet studentů přijímaných na určitý obor)"],
              ["die Physiologie (j. č.)", "fyziologie"],
              ["der Physiotherapeut, -en", "fyzioterapeut"],
              ["das Prạktikum, Praktika", "praxe, stáž"],
              ["die Prạxis (j. č.)", "praxe"],
              ["der Programmierer, -", "programátor"],
              ["der Prüfungszeitraum, Prüfungszeiträume", "zkouškové období"],
              ["die Psychologie (j. č.)", "psychologie"],
              ["die Qualifikation, -en", "kvalifikace"],
              ["der Ratgeber, -", "rádce, poradce, příručka"],
              ["die Realschule, -n", "reálná škola, reálka"],
              ["die Referẹnzen", "reference, doporučení, posudek"],
              ["die Rehabilitation, -en", "rehabilitace"],
              ["das Rẹchnungswesen (j. č.)", "účetnictví"],
              ["die Sạckgasse, -n", "slepá ulice"],
              ["das Seminar, -e", "seminář"],
              ["die Schlạnge, -n", "had"],
              ["schrịftlich", "písemný"],
              ["der Schulberater, -", "školní poradce"],
              ["das Schulsystem, -e", "školský systém"],
              ["sich erkụndigen (h. erkundigt)", "informovat se, zeptat se"],
              ["sich überlegen (h. überlegt)", "rozmyslet, promyslet, uvážit"],
              ["das Skrịpt, -e/-s", "skripta"],
              ["die Spịnne, -n", "pavouk"],
              ["die Strafe, -n", "pokuta, trest"],
              ["der Strạnd, Strände", "pláž"],
              ["das Studienfach, Studienfächer", "studijní obor"],
              ["der Studiengang, Studiengänge", "plán studia"],
              ["das Studium, Studien", "studium"],
              ["der Termin, -e", "schůzka, termín"],
              ["die Theorie, -n", "teorie"],
              ["der Tịschler, -", "truhlář"],
              ["träumen (h. geträumt) (von + 3. p.)", "snít (o čem)"],
              ["Träumst du nicht mehr davon, Journalistin zu werden?", "Už nesníš o tom, že se staneš novinářkou?"],
              ["überein|stimmen (h. übereingestimmt) (mit + 3. p.)", "shodovat se, souhlasit (s kým, čím)"],
              ["überholen (h. überholt)", "předjet, předjíždět"],
              ["ụm|gehen (i. umgegangen) (mit + 3. p.)", "zacházet, nakládat (s kým, čím)"],
              ["ụnbedingt", "bezpodmínečně, nutně"],
              ["die Universität, -en", "univerzita"],
              ["verbịnden (h. verbunden)", "spojit"],
              ["das Verkehrszeichen, -", "dopravní značka"],
              ["verlaufen (i. verlaufen)", "probíhat, konat se"],
              ["verschieben (h. verschoben)", "přesunout, posunout"],
              ["verzweifeln (i. verzweifelt) (an + 3. p. / über + 4. p.)", "zoufat si, být zoufalý (z koho, čeho)"],
              ["verzweifelt", "zoufalý"],
              ["die Vorlesung, -en", "přednáška"],
              ["die Weiterbildung (j. č.)", "další vzdělávání"],
              ["die Wịrtschaftslehre, -n", "ekonomika"],
              ["das Zeugnis, -se", "vysvědčení"],
              ["zụ̈chten (h. gezüchtet)", "chovat (zvířata), pěstovat (rostliny)"],
              ["die Zulassung (j. č.)", "přijetí, schválení"],
              ["zusạmmen|hängen (h. zusammengehangen) (mit + 3. p.)", "souviset (s čím)"]
            ]
        ],
        [
            ["Lekce 19"],
            [
            ]
        ]
    ],
}
