const lekce ={
    "lekce":[
        [
            ["Lekce 1"],
            [           
                ["der Abend", "večer"],
                ["du", "ty"],
                ["gut", "dobrý"],
                ["Guten Abend!", "Dobrý večer!"],
                ["(Es) Freut mich.", "Těší mě."],
                ["Hallo!", "Ahoj!"],
                ["heißen", "jmenovat se"],
                ["Hi!", "Ahoj!"],
                ["ich", "já"],
                ["ihr", "vy"],
                ["ja", "ano"],
                ["der Morgen", "ráno"],
                ["Guten Morgen!", "Dobré ráno!"],
                ["der Tag /-e", "den"],
                ["Guten Tag!", "Dobrý den!"],
                ["und", "a"],
                ["wer", "kdo"],
                ["Wer bist du?", "Kdo jsi?"],
                ["wie", "jak"],
                ["Wie heißt du?", "Jak se jmenuješ?"],
                ["wir", "my"],
                ["in", "v"],
                ["das Spiel /-e", "hra"],
                ["wo", "kde"],
                ["Wo wohnst du?", "Kde bydlíš?"],
                ["wohnen", "bydlet"],
                ["null", "0"],
                ["eins", "1"],
                ["zwei", "2"],
                ["drei", "3"],
                ["vier", "4"],
                ["fünf", "5"],
                ["sechs", "6"],
                ["sieben", "7"],
                ["acht", "8"],
                ["neun", "9"],
                ["zehn", "10"],
                ["elf", "11"],
                ["zwölf", "12"],
                ["dreizehn", "13"],
                ["vierzehn", "14"],
                ["fünfzehn", "15"],
                ["sechzehn", "16"],
                ["siebzehn", "17"],
                ["achtzehn", "18"],
                ["neunzehn", "19"],
                ["zwanzig", "20"],
                ["alt", "starý"], 
                ["er", "on"],
                ["der Monat /-e", "měsíc"], 
                ["sie", "ona"],
                ["sie", "oni"], 
                ["aber", "ale"],
                ["das Alter", "věk"], 
                ["auch", "také"],
                ["aus", "z"],      
                ["die Band /-s", "(hudební) skupina"],        
                ["chatten", "chatovat"],      
                ["das Computerspiel /-e", "počítačová hra"],        
                ["das E-Mail /-s", "e-mail"],      
                ["das Englisch", "angličtina"],        
                ["der Fan /-s", "fanoušek"],      
                ["das Französisch", "francouzština"],        
                ["der Freund /-e", "kamarád"],      
                ["die Freundin /-nen", "kamarádka"],        
                ["der Fußball", "fotbal"],      
                ["gehen", "jít"],        
                ["gern", "rád(a)"],      
                ["die Gitarre /-n", "kytara"],        
                ["das Handy /-s", "mobil"],      
                ["das Hobby /-s", "koníček"],        
                ["hören", "poslouchat"],      
                ["im internet surfen", "surfovat na internetu"],        
                ["immer", "pořád, neustále"],      
                ["das Jahr /-e", "rok"],        
                ["kein/keine/kein", "žádný/žádná/žádné"],      
                ["das Klavier /-e", "klavír"],        
                ["kommen (aus)", "pocházet (z)"],      
                ["das Konzert /-e", "koncert"],        
                ["lernen", "učit se"],      
                ["liegen", "ležet"],        
                ["der Nachname /-n", "příjmení"],      
                ["nicht weit von", "nedaleko (koho, čeho)"],        
                ["reisen", "cestovat"],      
                ["schreiben", "psát"],        
                ["die Schule /-n", "škola"],      
                ["spielen", "hrát"],        
                ["tanzen", "tancovat"],      
                ["der Vorname /-n", "křestní jméno"],        
                ["der Wohnort /-e", "bydliště"],      
                ["falsch", "nesprávně, chybně"],        
                ["die Flöte /-n", "flétna"],      
                ["haben", "mít"],        
                ["das Instrument /-e", "(hudební) nástroj"],      
                ["jetzt", "nyní"],        
                ["machen", "dělat"],      
                ["richtig", "správně"],        
                ["der Sport", "sport"],      
                ["Sport treiben", "sportovat"],        
                ["das Squash", "squash"],      
                ["das/der Yoga", "jóga"],      
                ["bald", "brzy"],          
                ["bis", "do"],          
                ["Bis bald!", "Tak zatím!"],          
                ["die Frau /-en", "paní"],          
                ["der Herr /-en", "pan"],          
                ["das Museum /Museen", "muzeum"],          
                ["schön", "hezký"],           
                ["Servus!", "Ahoj!"],          
                ["Tschüs!", "Ahoj! (při loučení)"],          
                ["das Wiedersehen", "shledání"]
            ]
        ],
        [
            ["Lekce 11"],
            [
                ["die Ạbfahrt, -en", "odjezd; sjezd (na lyžích)"],
                ["die Ạbreise, -n", "odjezd"],
                ["die Ạltersgruppe, -n", "věková skupina"],
                ["ạn|kommen (i. angekommen)", "přijet, dorazit"],
                ["ạnderthạlb", "jeden a půl"],
                ["anderthalb Stunden", "hodinu a půl"],
                ["der/die Ạngestellte, -n", "zaměstnanec, zaměstnankyně"],
                ["die Ạnkunft, Ankünfte", "příjezd, přílet"],
                ["die Ạnreise, -n", "příjezd; cesta/jízda (tam)"],
                ["die Ạnschrift, -en", "adresa"],
                ["die Atmosphäre, -n", "atmosféra"],
                ["auf jeden Fall", "v každém případě, na každý pád"],
                ["Auf Wiederhören!", "Na slyšenou!"],
                ["der Aufenthalt, -e", "pobyt"],
                ["aus|drucken (h. ausgedruckt)", "vytisknout"],
                ["aus|fallen (i. ausgefallen)", "vypadnout"],
                ["aus|füllen (h. ausgefüllt)", "vyplnit"],
                ["aus|halten (h. ausgehalten)", "vydržet"],
                ["aus|steigen (i. ausgestiegen)", "vystoupit"],
                ["die Bahn, -en", "vlak; železnice, dráha"],
                ["bar", "v hotovosti, hotově"],
                ["das Bargeld (j. č.)", "hotovost, hotové peníze"],
                ["die Bạstelwerkstatt, Bastelwerkstätten", "kutilská dílna"],
                ["begrẹnzt", "omezený, ohraničený"],
                ["besẹtzen (h. besetzt)", "obsadit"],
                ["bịllig", "levný"],
                ["bịtten (h. gebeten) ", "prosit (o)"],
                ["das Boot, -e", "člun"],
                ["das Budget, -s", "rozpočet"],
                ["buchen (h. gebucht)", "rezervovat"],
                ["das reicht", "to stačí"],
                ["die Daten", "data, údaje, informace"],
                ["das Dọppelzimmer, -", "dvoulůžkový pokoj"],
                ["ein Angestellter/eine Angestellte", "zaměstnanec/ zaměstnankyně"],
                ["ein Erwachsener/eine Erwachsene", "dospělý/dospělá"],
                ["der Eingang, Eingänge", "vchod, vstup, vjezd"],
                ["der Eintritt, -e", "vstup, vstupné"],
                ["die Einzelkarte, -n", "jednotlivá jízdenka/vstupenka"],
                ["das Einzelzimmer, -", "jednolůžkový pokoj"],
                ["die Entfẹrnung, -en", "vzdálenost"],
                ["die Erfahrung, -en", "zkušenost"],
                ["erlaubt", "povolený"],
                ["erreichen (h. erreicht)", "dostat se, dorazit (kam); dosáhnout"],
                ["der/die Erwạchsene, -n", "dospělý, dospělá"],
                ["die Fahrkarte, -n", "jízdenka"],
                ["die Fahrt, -en", "cesta, jízda"],
                ["der Fạll, Fälle", "pád, případ"],
                ["die Ferienwohnung, -en", "rekreační byt, prázdninový byt"], 
                ["das Fẹstival, -s", "festival"],
                ["gefährlich", "nebezpečný, riskantní"], 
                ["genügend", "dostatečný, postačující"],
                ["das Geschịrr, -e", "nádobí"], 
                ["gụ̈ltig", "platný"],
                ["gụ̈nstig", "výhodný, příznivý"], 
                ["der Hafen, Häfen", "přístav"],
                ["der Hbf = Hauptbahnhof, Hauptbahnhöfe", "hlavní (vlakové) nádraží"],      
                ["das Họstel, -s", "hostel"],        
                ["der/das Check-out, -s", "check-out"],      
                ["ịnbegriffen", "zahrnutý, včetně"],        
                ["jemand", "někdo, kdosi"],      
                ["kẹnnen|lernen (h. kennengelernt)", "poznat, seznámit se"],        
                ["klịngen (h. geklungen)", "znít"],      
                ["kọstenlos", "bezplatný, zdarma"],        
                ["die Kreditkarte, -n", "kreditní karta"],      
                ["die Kụrzstrecke, -n", "krátký úsek cesty"],        
                ["lạngsam", "pomalý"],      
                ["der Mietwagen, -", "pronajaté vozidlo"],        
                ["die Mịtfahrgelegenheit, -en", "spolujízda"],      
                ["das Motel, -s", "motel"],        
                ["das Motorrad, Motorräder", "motorka, motocykl"],      
                ["der Nahbereich, -e", "blízké okolí"],        
                ["der Nahverkehr (j. č.)", "místní doprava"],      
                ["ọ̈ffentlich", "veřejný"],        
                ["die Oper, -n", "opera"],      
                ["der Pạrkplatz, Parkplätze", "parkoviště; parkovací místo"],        
                ["pạssen (h. gepasst)", "hodit se, padnout; padnout, sedět (oblečení)"],      
                ["passieren (i. passiert)", "přihodit se, stát se"],        
                ["das Pạsswort, Passwörter", "heslo"],      
                ["die Pension, -en", "penzion"],        
                ["der Personalausweis, -e", "občanský průkaz, průkaz totožnosti"],      
                ["die PLZ = Pọstleitzahl, -en", "PSČ"],        
                ["das Privatzimmer, -", "soukromá místnost"],      
                ["reichen (h. gereicht)", "stačit"],        
                ["die Rezeption, -en", "recepce"],      
                ["der Rezeptionịst, -en", "recepční"],        
                ["die Rụ̈ckfahrkarte, -n", "zpáteční jízdenka"],      
                ["die Rụndfahrt, -en", "okružní jízda"],        
                ["die S-Bahn, -en", "rychlodráha, městská dráha"],      
                ["der Senior, -en", "senior"],        
                ["der Schlụ̈ssel, -", "klíč"],      
                ["schnẹll", "rychlý"],        
                ["schreien (h. geschrien)", "křičet, řvát"],      
                ["der Schülerausweis, -e", "žákovský/studentský průkaz"],        
                ["spạnnend", "napínavý"],      
                ["spülen (h. gespült)", "mýt, opláchnout"],        
                ["das Stạdtfest, -e", "městská slavnost"],      
                ["stạtt|finden (h. stattgefunden)", "konat se"],        
                ["der Stẹrn, -e", "hvězda"],      
                ["stornieren (h. storniert)", "stornovat, zrušit"],        
                ["die Suche, -n", "hledání, pátrání"],      
                ["die Tageskarte, -n", "celodenní jízdenka/vstupenka"],          
                ["der Teenie, -s", "teenager"],          
                ["teil|nehmen (h. teilgenommen)", "účastnit se (čeho)"],          
                ["teuer", "drahý"],          
                ["trẹffen (sich) (h. getroffen)", "potkat (koho), setkat se (s kým)"],          
                ["tun (h. getan)", "dělat, činit"],          
                ["der Tunnẹl, -", "tunel"],          
                ["ụm|steigen (i. umgestiegen)", "přestoupit"],          
                ["ụm|ziehen (i. umgezogen)", "přestěhovat se"],          
                ["ụmweltfreundlich", "ekologický, šetrný k životnímu prostředí"],          
                ["die Ụnterkunft, Unterkünfte", "ubytování"],          
                ["unternehmen (h. unternommen)", "podniknout"],          
                ["die Ụnterschrift, -en", "podpis"],          
                ["die Ụnterwelt, -en", "podzemí"],          
                ["die Verạnstaltung, -en", "akce, událost"],          
                ["verdienen (h. verdient)", "vyděl(áv)at"],          
                ["die Vorkasse, -n", "platba předem"],          
                ["wahrscheinlich", "pravděpodobně"],          
                ["wạch", "bdělý, vzhůru"],          
                ["werden (i. geworden)", "stá(va)t se"],          
                ["die Wẹrkstatt, Werkstätten", "dílna"],          
                ["der Wẹttbewerb, -e", "der Wẹttbewerb, -e"],          
                ["wiederholen (h. wiederholt)", "opakovat"],          
                ["wịld", "divoký"],          
                ["willkọmmen", "vítaný"],          
                ["der Workshop, -s", "workshop"],          
                ["zahlbar", "splatný, k zaplacení"],          
                ["die Zahlung, -en", "platba"],          
                ["ZOB = Zentraler Omnibusbahnhof", "centrální autobusové nádraží"],    
            ]
        ],
        [
            ["Lekce 12"],
            [
                ["anders", "jinak"],
                ["der Ạnschlag, Anschläge", "útok, atentát"],
                ["die Ausfahrt, -en", "exit, sjezd (z dálnice)"],
                ["die Autobahn, -en", "dálnice"],
                ["beliebt", "oblíbený, populární"],
                ["berẹchnen (h. berechnet)", "spočítat"],
                ["bestehen (h. bestanden)", "být (z čeho), skládat se, sestávat; složit (zkoušku)"],
                ["der Betonblock, Betonblöcke/-s", "betonový blok"],
                ["das Dẹnkmal, Denkmäler", "památník, pomník"],
                ["das Dịng, -e", "věc"],
                ["das Dreieck, -e", "trojúhelník, zde: křižovatka dálnic"],
                ["durchfließen (h. durchflossen)", "protékat (čím)"],
                ["der Einwohner, -", "obyvatel"],
                ["erfụ̈llen (h. erfüllt)", "splnit"],
                ["das Ergebnis, -se", "výsledek"],
                ["die Erịnnerung, -en", "památka, upomínka"],
                ["der Fẹrnsehturm, Fernsehtürme", "televizní věž"],
                ["fließen (i. geflossen)", "téci"],
                ["das Gebịrge, -", "pohoří, hory"],
                ["das Graffiti, -s", "graffiti"],
                ["grausam", "krutý, hrozný"],
                ["die Hạ̈lfte, -n", "polovina, půlka"],
                ["hạndeln (h. gehandelt)", "jednat, počínat si"],
                ["hẹrrlich", "nádherný, překrásný"],
                ["hoch", "vysoký"],
                ["hoch|fahren (i. hochgefahren) hovor.", "(vy)jet nahoru"],
                ["in der Wirklichkeit", "ve skutečnosti"],
                ["die Insel, -n", "ostrov"],
                ["kọsten (h. gekostet)", "stát (o ceně)"],
                ["der Kreisverkehr, -e", "kruhový objezd"],
                ["das Kreuz (j. č.) (zkr. z Autobahnkreuz, -e)", "kříž; křižovatka dálnic"],
                ["die Kụppel, -n", "kopule"],
                ["lạng", "dlouhý"],
                ["lebẹndig", "živý, čilý"],
                ["der Lkw (= Lạstkraftwagen)", "nákladní auto"],
                ["lösen (h. gelöst)", "(vy)řešit; uvolnit"],
                ["das Mahnmal, -e", "památník, pomník"],
                ["die Mạrke, -n", "značka; známka"],
                ["die Mauer, -n", "zeď"],
                ["das Meer, -e", "moře"],
                ["mụ̈nden (i./h. gemündet)", "ústit, vlévat se"],
                ["die Nọrdsee (j. č.)", "Severní moře"],
                ["die Ọstsee (j. č.)", "Baltské moře"],
                ["die Rạststätte, -n", "dálniční odpočívadlo, motorest"],
                ["die Reise, -n", "cesta, cestování"],
                ["der Rẹst, -e", "zbytek"],
                ["die Rẹttungsgasse, -n", "záchranná ulička"],
                ["der Rẹttungswagen, -", "záchranka, záchranné vozidlo"], 
                ["die Rịchtung, -en", "směr"],
                ["die Rụndwanderung, -en", "okružní túra"], 
                ["sạmmeln (h. gesammelt)", "sbírat"],
                ["die See (j. č.)", "moře"], 
                ["die Seilbahn, -en", "lanová dráha, lanovka"],
                ["sẹlbst", "sám, sama, osobně"], 
                ["schwer", "těžký"],
                ["sich ạn|ziehen (h. angezogen)", "obléknout seạnders"],      
                ["sich ạ̈rgern (h. geärgert)", "(roz)zlobit se"],        
                ["sich aus|kennen (h. ausgekannt)", "vyznat se, vědět si rady"],      
                ["sich beeilen (h. beeilt)", "pospíšit se"],        
                ["sich bewegen (h. bewegt)", "hýbat se"],      
                ["sich entspạnnen (h. entspannt)", "uvolnit se"],        
                ["sich erholen (h. erholt)", "odpočinout si"],      
                ["sich erkạ̈lten (h. erkältet)", "nachladit se, nastydnout"],        
                ["sich freuen (h. gefreut) ", "těšit se, mít radost"],      
                ["sich konzentrieren (h. konzentriert)", "soustředit se, koncentrovat se"],        
                ["sich verlaufen (h. verlaufen)", "zabloudit, ztratit se"],      
                ["sich vor|bereiten (h. vorbereitet)", "připravit se (na)"],        
                ["sich vor|stellen (h. vorgestellt)", "představit si"],      
                ["sich wụndern (h. gewundert)", "divit se"],        
                ["spẹrren (h. gesperrt)", "(u)zavřít"],      
                ["der Stau, -s", "dopravní zácpa"],        
                ["stọckend", "váznoucí"],      
                ["die Strẹcke, -n", "cesta, trať, úsek"],        
                ["die Teilung, -en", "rozdělení"],      
                ["der Tiergarten, Tiergärten", "zoologická zahrada"],        
                ["traurig", "smutný"],      
                ["die Tụnnelsperre, -n", "uzávěra tunelu"],        
                ["die Ụmleitung, -en", "objížďka"],      
                ["der Ụnfall, Unfälle", "nehoda, neštěstí"],        
                ["der Verkehr (j. č.)", "doprava, provoz"],      
                ["die Verkehrsmeldung, -en", "informace o dopravě"],        
                ["viereinhạlb", "čtyři a půl"],      
                ["wịchtig", "důležitý"],        
                ["die Wịrklichkeit, -en", "skutečnost"],      
                ["die Zahnradbahn, -en", "ozubnicová dráha, zubačka"]    
            ]
        ],,
        [
            ["Lekce 13 - důležité"],
            [
                ["4 °C (vier Grad Celsius)","4 stupně"],
                ["die Accessoires","doplňky"],
                ["der Ạnzug, Anzüge","oblek"],
                ["die Ạrmbanduhr, -en","náramkové hodinky"],
                ["die Augenbraue, -n","obočí"],
                ["der Ausschnitt, -e","výstřih"],
                ["der Ausverkauf, Ausverkäufe","výprodej"],
                ["die Badehose, -n","(pánské) plavky"],
                ["bewọ̈lkt","zatažený"],
                ["der BH (Büstenhalter)","podprsenka"],
                ["der Bikini, -s","bikiny"],
                ["der Blazer, -","sportovní sako, blejzr"],
                ["blịtzen (h. geblitzt)","blýskat se"],
                ["die Bluse, -n","halenka, blůza"],
                ["die Bọxershorts","boxerky"],
                ["dọnnern (h. gedonnert)","hřmět"],
                ["ẹng","úzký"],
                ["fein","jemný"],
                ["die Figur, -en","postava"],
                ["flạch","rovný; nízký"],
                ["der Flịpflop, -s","žabka (bota)"],
                ["frieren (h. gefroren)","mrznout"],
                ["gepụnktet","puntíkovaný"],
                ["gestreift","pruhovaný"],
                ["das Gewịtter, -","bouřka"],
                ["das Grad","stupeň (Celsia…)"],
                ["die Größe, -n","velikost"],
                ["der Gụmmistiefel, -","holínka, gumák"],
                ["der Gụ̈rtel, -","pásek"],
                ["der Hạlbschuh, -e","polobotka"],
                ["der Hạndschuh, -e","rukavice"],
                ["die Hạndtasche, -n","kabelka"],
                ["heiß","horký"],
                ["heiter","jasný, slunečný"],
                ["das Hẹmd, -en","košile"],
                ["die Höchsttemperatur, -en","nejvyšší teplota"],
                ["die Hose, -n","kalhoty"],
                ["das Höschen, -","kalhotky"],
                ["der Hut, Hüte","klobouk"],
                ["die Jạcke, -n","bunda"],
                ["die Jeans","džíny"],
                ["die Jọgginghose, -n","sportovní kalhoty, tepláky"],
                ["die Kạppe, -n","čapka, kšiltovka"],
                ["die Kẹtte, -nv","řetízek"],
                ["das Kleid, -er","šaty"],
                ["das Kleidungsstück, -e","kus oděvu, oděv (např. tričko)"],
                ["der Kragen, -/Krägen","límec"],
                ["die Krawạtte, -n","kravata"],
                ["kühl","chladný"],
                ["die Lederhose, -n","kožené kalhoty"],
                ["die Lẹggins","legíny"],
                ["das Make-up, -s","make-up"],
                ["der Mạntel, Mäntel","kabát"],
                ["die Mạrkenkleidung (j. č.)","značkové oblečení"],
                ["die Mụ̈tze, -n","čepice"],
                ["neblig","mlhavý"],
                ["der Ohrring, -e","náušnice"],
                ["das Outfit, -s","outfit"],
                ["das Piercing, -s","piercing"],
                ["der Pullover, -","svetr"],
                ["der Pụmps, -","lodička (bota)"],
                ["der Regenschirm, -e","deštník"],
                ["regnen (h. geregnet)","pršet"],
                ["der Rịng, -e","prsten"],
                ["der Rọck, Röcke","sukně"],
                ["der Rụcksack, Rucksäcke","batoh"],
                ["das/der Sạkko, -s","sako"],
                ["die Sandale, -n","sandál"],
                ["die Shorts","šortky"],
                ["der Schal, -s","šála"],
                ["der Schauer, -","přeháňka"],
                ["scheinen (h. geschienen)","svítit"],
                ["der Schlafanzug, Schlafanzüge","pyžamo"],
                ["schneien (h. geschneit)","sněžit"],
                ["der Schnürschuh, -e","šněrovací bota"],
                ["die Skinny-Jeans","úzké džíny, skinny džíny"],
                ["die Sọcke, -n","ponožka"],
                ["die Sohle, -n","podrážka"],
                ["die Sọnne (j. č.)","slunce"],
                ["die Sọnnenbrille, -n","sluneční brýle"],
                ["sọnnig","slunečný"],
                ["der Spọrtschuh, -e","sportovní bota"],
                ["der Stiefel, -","kozačka, vysoká bota"],
                ["der Stil, -e","styl"],
                ["stilgerecht","stylový"],
                ["der Strịckpullover, -","pletený svetr"],
                ["die Strụmpfhose, -n","punčocháče"],
                ["das Sweatshirt, -s","mikina"],
                ["teilweise bedẹckt","částečně zataženo"],
                ["die Temperatur, -en","teplota"],
                ["das Tọp, -s","top"],
                ["der Trẹkkingschuh, -e","treková bota"],
                ["das Tuch, Tücher","šátek"],
                ["die Tunika, Tuniken","tunika"],
                ["die Ụmkleidekabine, -n","převlékací kabina"],
                ["weit","široký"],
                ["das Wẹtter (j. č.)","počasí"],
                ["die Wẹtter-App, -s","aplikace na počasí"]
                ["die Wẹttervorhersage, -n","předpověď počasí"],
                ["wịndig","větrný"],
                ["wọlkig","oblačný, zamračený"],
                ["zerrịssen","roztrhaný"],
                ["zusạmmen|passen (h. zusammengepasst)","hodit se k sobě"],
                ["der Niederschlag","srážka"],
                ["der Regen","déšť"],
                ["der Blitz","blesk"],
                ["der Schnee","sníh"],
                ["die Sonne","slunce"],
                ["der Frost","mráz"],
                ["der Donner","hrom"],
                ["die Wolke","mrak"],
                ["der Nebel","mlha"],
                ["der Wind","vítr"],
                ["der Hagel","kroupy"],
                ["der Schneeschauer","sněhová přeháňka"]
            ]
        ],
        [
            ["Lekce 13"],
            [
                ["4 °C (vier Grad Celsius)","4 stupně"],
                ["die Accessoires","doplňky"],
                ["aktuẹll","aktuální"],
                ["allerdịngs","ovšem, avšak"],
                ["der Ạlltag (j. č.)","všední den"],
                ["ạltmodisch","staromódní, nemoderní"],
                ["ạn|probieren (h. anprobiert)","zkusit (si), vyzkoušet si (oblečení, boty)"],
                ["der Ạnzug, Anzüge","oblek"],
                ["die Ạrmbanduhr, -en","náramkové hodinky"],
                ["auf keinen Fall","v žádném případě"],
                ["auf|passen (h. aufgepasst) (auf + 4. p.)","dávat pozor, dohlížet (na koho, co)"],
                ["die Augenbraue, -n","obočí"],
                ["aus|leihen (h. ausgeliehen)","vypůjčit, půjčit"],
                ["der Ausschnitt, -e","výstřih"],
                ["der Ausverkauf, Ausverkäufe","výprodej"],
                ["die Badehose, -n","(pánské) plavky"],
                ["der Berịcht, -e","zpráva"],
                ["betonen (h. betont)","zdůraznit"],
                ["bewọ̈lkt","zatažený"],
                ["der BH (Büstenhalter)","podprsenka"],
                ["der Bikini, -s","bikiny"],
                ["der Blazer, -","sportovní sako, blejzr"],
                ["blịtzen (h. geblitzt)","blýskat se"],
                ["die Bluse, -n","halenka, blůza"],
                ["die Bọxershorts","boxerky"],
                ["das Detail, -s","detail"],
                ["dezẹnt","decentní"],
                ["dọnnern (h. gedonnert)","hřmět"],
                ["ein|packen (h. eingepackt)","(za)balit"],
                ["einverstanden","srozuměný"],
                ["elegạnt","elegantní"],
                ["die Empfehlung, -en","doporučení, rada"],
                ["ẹng","úzký"],
                ["erfahren (h. erfahren)","dozvědět se"],
                ["extravagạnt","extravagantní"],
                ["fein","jemný"],
                ["die Figur, -en","postava"],
                ["flạch","rovný; nízký"],
                ["der Flịpflop, -s","žabka (bota)"],
                ["der Flyer, -","leták"],
                ["frieren (h. gefroren)","mrznout"],
                ["das Gefühl, -e","smysl, cit"],
                ["gepụnktet","puntíkovaný"],
                ["geschehen (i. gechehen)","dít se, stát se"],
                ["gestreift","pruhovaný"],
                ["das Gewịtter, -","bouřka"],
                ["gewöhnlich","obyčejný, normální"],
                ["das Grad","stupeň (Celsia…)"],
                ["großartig","(hovor.) úžasný, super"],
                ["die Größe, -n","velikost"],
                ["der Gụmmistiefel, -","holínka, gumák"],
                ["der Gụ̈rtel, -","pásek"],
                ["der Hạlbschuh, -e","polobotka"],
                ["der Hạndschuh, -e","rukavice"],
                ["die Hạndtasche, -n","kabelka"],
                ["heiß","horký"],
                ["heiter","jasný, slunečný"],
                ["das Hẹmd, -en","košile"],
                ["die Höchsttemperatur, -en","nejvyšší teplota"],
                ["die Hose, -n","kalhoty"],
                ["das Höschen, -","kalhotky"],
                ["der Hut, Hüte","klobouk"],
                ["die Jạcke, -n","bunda"],
                ["die Jeans","džíny"],
                ["die Jọgginghose, -n","sportovní kalhoty, tepláky"],
                ["die Kạppe, -n","čapka, kšiltovka"],
                ["die Kẹtte, -nv","řetízek"],
                ["das Kleid, -er","šaty"],
                ["das Kleidungsstück, -e","kus oděvu, oděv (např. tričko)"],
                ["kombinieren (h. kombiniert)","kombinovat"],
                ["der Kragen, -/Krägen","límec"],
                ["die Krawạtte, -n","kravata"],
                ["kühl","chladný"],
                ["das Leben, -","život"],
                ["die Lederhose, -n","kožené kalhoty"],
                ["leger","ležérní"],
                ["die Lẹggins","legíny"],
                ["das Make-up, -s","make-up"],
                ["der Mạntel, Mäntel","kabát"],
                ["die Mạrkenkleidung (j. č.)","značkové oblečení"],
                ["die Modepolizei (j. č.)","módní policie"],
                ["die Mụ̈tze, -n","čepice"],
                ["neblig","mlhavý"],
                ["nẹnnen (h. genannt)","(po)jmenovat, naz(ý)vat"],
                ["der Ohrring, -e","náušnice"],
                ["das Outfit, -s","outfit"],
                ["pạssen (h. gepasst)","padnout, sedět (oblečení)"],
                ["das Piercing, -s","piercing"],
                ["der Pullover, -","svetr"],
                ["der Pụmps, -","lodička (bota)"],
                ["der Regenschirm, -e","deštník"],
                ["regnen (h. geregnet)","pršet"],
                ["der Rịng, -e","prsten"],
                ["der Rọck, Röcke","sukně"],
                ["der Rụcksack, Rucksäcke","batoh"],
                ["das/der Sạkko, -s","sako"],
                ["die Sandale, -n","sandál"],
                ["seriös","seriózní"],
                ["die Shorts","šortky"],
                ["der Schal, -s","šála"],
                ["der Schauer, -","přeháňka"],
                ["scheinen (h. geschienen)","svítit"],
                ["schịck","šik, elegantní"],
                ["der Schlafanzug, Schlafanzüge","pyžamo"],
                ["schneien (h. geschneit)","sněžit"],
                ["der Schnürschuh, -e","šněrovací bota"],
                ["die Skinny-Jeans","úzké džíny, skinny džíny"],
                ["die Sọcke, -n","ponožka"],
                ["sogar","dokonce (i)"],
                ["die Sohle, -n","podrážka"],
                ["die Sọnne (j. č.)","slunce"],
                ["die Sọnnenbrille, -n","sluneční brýle"],
                ["sọnnig","slunečný"],
                ["der Spọrtschuh, -e","sportovní bota"],
                ["das Sprịchwort, Sprichwörter","přísloví, pořekadlo"],
                ["stehen (h. gestanden)","zde: padnout, sedět (o oblečení)"],
                ["steigen (i. gestiegen)","stoupat"],
                ["der Stiefel, -","kozačka, vysoká bota"],
                ["der Stil, -e","styl"],
                ["stilgerecht","stylový"],
                ["der Strịckpullover, -","pletený svetr"],
                ["die Strụmpfhose, -n","punčocháče"],
                ["stụ̈rmisch","bouřlivý, rozbouřený"],
                ["stylen (h. gestylt)","upravit, zkrášlit"],
                ["das Sweatshirt, -s","mikina"],
                ["teilweise bedẹckt","částečně zataženo"],
                ["die Temperatur, -en","teplota"],
                ["das Tọp, -s","top"],
                ["der Trẹkkingschuh, -e","treková bota"],
                ["das Tuch, Tücher","šátek"],
                ["die Tunika, Tuniken","tunika"],
                ["der Typ, -en","typ"],
                ["die Ụmkleidekabine, -n","převlékací kabina"],
                ["die Wahl, -en","volba, výběr"],
                ["die Wạrnung, -en","výstraha, varování"],
                ["wẹchselhaft","proměnlivý"],
                ["weit","široký"],
                ["das Wẹtter (j. č.)","počasí"],
                ["die Wẹtter-App, -s","aplikace na počasí"],
                ["die Wẹttervorhersage, -n","předpověď počasí"],
                ["wịndig","větrný"],
                ["wọlkig","oblačný, zamračený"],
                ["zerrịssen","roztrhaný"],
                ["zusạmmen|passen (h. zusammengepasst)","hodit se k sobě"],
                ["der Niederschlag","srážka"],
                ["der Regen","déšť"],
                ["der Blitz","blesk"],
                ["der Schnee","sníh"],
                ["die Sonne","slunce"],
                ["der Frost","mráz"],
                ["der Donner","hrom"],
                ["die Wolke","mrak"],
                ["der Nebel","mlha"],
                ["der Wind","vítr"],
                ["der Hagel","kroupy"],
                ["der Schneeschauer","sněhová přeháňka"]
            ]
        ],
        [
            ["Lekce 14"],
            [
            ]
        ]
    ],
}
